### ISSUE TITLE
Módulo não sai do Sandbox. Erro (53122)

### ISSUE THREAD

**Issue by elielcezar** [r-martins/PagSeguro-Magento-Transparente#100]
Eu testei o módulo em modo sandbox e tudo correu bem. Depois dos testes, estou tentando colocar o site em produção, mas não consigo.

Já alterei a opção "Ambiente de testes?" Para "Não" e atualizei o token do Pagseguro para o token gerado na minha conta oficial.

Porém após tentar fazer uma compra vejo a seguinte mensagem: "Problemas ao processar seu pagamento. sender email invalid domain:  You must use an email @sandbox.pagseguro.com.br(53122)" como se ele ainda estivesse em sandbox.

Já tentei substituir todos os arquivos do módulo por arquivos atualizados do Github e os arquivos da versão pró que recebi por email, porém sem sucesso.

Também notei que o moto Aplicação não funciona, mesmo eu tendo adquirido o token do módulo. Já vi em outro tópico que ele não fuinciona em modo Sandbox, o que me leva a crer que essa opção está configurada em algum lugar que não seja na própria página do módulo.

**Comment by elielcezar** [comment]
Ok, erro de iniciante. Eu esqueci de marcar a opção "Main Website" antes de salvar as configurações. Eu estava fazendo tudo e salvando na opção "Todas as Lojas". 

Tudo funcionando corretamente agora.

**Comment by r-martins** [comment]
acontece nas melhores familias
