### ISSUE TITLE
Checkout Transparente não habilitado!!!!

### ISSUE THREAD

**Issue by rodolfoagomes** [r-martins/PagSeguro-Magento-Transparente#101]
Boa tarde, instalei o módulo e configurei perfeitamente, mas ao realizar a primeira transação ou consulta se o cartão é valido o log do modulo informa que a Pagseguro não reconhece o meu Token e usuário, pesquisei e percebi que isso é devido ao Checkout Transparente não esta habilitado na Pagseguro, gostaria de saber o que preciso para habilitar esse módulo pois já liguei para a pagseguro mais de 6 vezes e eles não sabem me dizer sobre isso, como eu habilito?

**Comment by marcelloinfoweb** [comment]
Vc tem que ir no site do PagSeguro e ir na página de desenvolvedor e lá tem um formulário exatamente para isso.

**Comment by rodolfoagomes** [comment]
Eu já fui, já solicitei umas 10 vezes e ninguém me responde, não sei mais com quem falar e onde ir....o formulário de solicitação é preenchido e eu não tenho resposta deles.....estou meio desesperado ja

**Comment by marcelloinfoweb** [comment]
Cara,  onde trabalho o pessoal de administração envio na quinta feira e deram um prazo até o dia 28. Paciência e esperar.

**Comment by rodolfoagomes** [comment]
O mais interessante é que eles não me deram prazo nenhum....nem respondem meus email

**Comment by phdiegues** [comment]
Bem vindo a UOL!

**Comment by renatoaleksander** [comment]
Por gentileza colabore com o projeto e instale a versão de aplicação do checkout transparente pois nesta vc não irá precisar esperar por ele.

Veja: http://r-martins.github.io/PagSeguro-Magento-Transparente/pro/app.html

**Comment by phdiegues** [comment]
Já a tenho! :)

**Comment by r-martins** [comment]
Vale pra vocês, mas posso ajudar na liberação.
Me passem os e-mails das contas e urls das lojas a habilitar por chamado, e tento agilizar.
