### ISSUE TITLE
Retorno de Status Pagamento BOLETO ou TEF

### ISSUE THREAD

**Issue by rodolfoagomes** [r-martins/PagSeguro-Magento-Transparente#102]
Bom dia, como teste, porem no ambiente de produção, efetuei uma compra na minha loja por boleto bancario, o boleto foi pago, o pagseguro constatou o pagamento, porem o status do meu pedido no magento continua como "Pendente Aguardando", essa comunicação existe ou deve ficar assim mesmo e eu devo acompanhar meu PagSeguro manualmente e alimentar meu ecommerce com os boletos já pagos ou as TEFs realizadas?

**Comment by r-martins** [comment]
@rodolfoagomes, confira as url's de retorno de acordo com as instruções na pagina do modulo.
Vamos tentar usar esse canal apenas para bugs.
