### ISSUE TITLE
 Call to undefined method - módulo PRO - Pagamento via boleto

### ISSUE THREAD

**Issue by marcelodeandrade** [r-martins/PagSeguro-Magento-Transparente#105]
Ao instalar o módulo PRO e ativar o módulo do boleto, recebo o seguinte erro ao efetuar uma compra:

Fatal error: Call to undefined method RicardoMartins_PagSeguro_Helper_Data::getPagSeguroScriptBlock() in /home/acessov/public_html/app/code/community/RicardoMartins/PagSeguroPro/Block/Form/Boleto.php on line 23

**Comment by r-martins** [comment]
Olá @marcelodeandrade ,
Isso ocorre pois você não deve estar usando a ultima versão (2.1.0) do modulo principal.
Atualize o modulo principal (RicardoMartins_PagSeguro).
