### ISSUE TITLE
Sender hash is required

### ISSUE THREAD

**Issue by color350** [r-martins/PagSeguro-Magento-Transparente#106]
Olá.
Como resolver?
Desde já, obrigado.

**Comment by Rafaelolmartins** [comment]
Estou com o mesmo problema... No chrome funciona direito, no firefox não!

**Comment by r-martins** [comment]
Provavelmente algo errado com o token ou liberação da conta.
Deem uma olhada em https://pagsegurotransparente.zendesk.com/hc/pt-br/search?utf8=%E2%9C%93&query=sender+hash&commit=Pesquisa

Se não resolver, peço que reabram passando mais detalhes de como reproduzir.
