### ISSUE TITLE
Campo Telefone(Quando esta sem DDD)  e Complemeto não são integrados com PagSeguro

### ISSUE THREAD

**Issue by rodolfoagomes** [r-martins/PagSeguro-Magento-Transparente#107]
Bom dia, para geração do boleto é necessário que alguns dados sejam enviados como o número do endereço, o magento por default vem com o campo de endereço apenas, deixando aberto a digitação, o usuário pode simplesmente digitar o nome da rua da seguinte forma: 

RUA DA MINHA CASA ao invés de RUA DA MINHA CASA, 56, AP 35, JD MEU BAIRRO.

Baseado nisso modifiquei meu formulário com a solução no link abaixo, o problema é que na integração com o PagSeguro o campo complemento não é enviado e no caso de um apartamento ou vilarejo o endereço de entrega fica incompleto podendo até desviar o pedido.

Obs: Com a alteração abaixo o meu campo ENDEREÇO, foi dividido em ENDEREÇO, NUMERO, COMPLEMENTO e BAIRRO

http://www.bling.com.br/manuais.bling.php?p=api.magento.desenvolvedor 

Alguém pode me ajudar?

**Comment by rodolfoagomes** [comment]
Alguem poderia me dar uma luz? Estou perdendo muitas vendas pelo problema da integração com o DDD e complemento.

Obrigado

**Comment by rodolfoagomes** [comment]
Amigos, abaixo segue os campo do XML que  o modulo envia para o Magento:

'shippingAddressStreet' => 'Rua X',
  'shippingAddressNumber' => '25',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => '25',
  'shippingAddressPostalCode' => '04468010',
  'shippingAddressCity' => 'S�o Paulo',
  'shippingAddressState' => 'SP',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '7.48',
  'billingAddressStreet' => 'Rua X',
  'billingAddressNumber' => '25',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => '25',

Podemos ver que o campo "shippingAddressComplement" está indo vazio, sendo que na tela foi cadastrado e o campo 'billingAddressDistrict' => '25', esta indo com o valor do campo number.

**Comment by r-martins** [comment]
@rodolfoagomes 
Você deve mapear os campos dos atributos no admin da loja.
[Nesse vídeo](https://www.youtube.com/watch?v=sPyTsXW7JbI) mostro como fazê-lo.

Por favor, use esse canal para reportar bugs, e não suporte.
Mais informações em https://pagsegurotransparente.zendesk.com/hc/pt-br
