### ISSUE TITLE
OneStepCheckout trava quando eu escolho a opção de pagar com cartão de credito

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#109]
Pessoal, boa noite 

Sou programador responsável da loja brasilmoedas.com.br e recentemente instalei o modulo de checkout transparente do ricardo martins , até ai tudo certo. Porém quando eu seleciono a opção de pagar com cartão de crédito e clico em finalizar pedido, parece que o botão fica sem função alguma e não vai pra lugar nenhum. Não gera log nem nada, estou usando o onestepcheckout do deivison. Vcs podem me ajudar com isso ? 

Abs

Rafael

**Comment by magnored** [comment]
tenta abrir o debug ve se ele ta fazendo alguma funcao qdo vc clica no botao.
Esse projeto (pagseguro transparente) parece que foi abandonado, enviei um email para o desenvolvedor e nao tive retorno ... 
uma pena um projeto tão bom como esse ficar sem suporte.

**Comment by r-martins** [comment]
Olá @magnored,
Não sei por onde você mandou e-mail, mas respondo todos os chamados de suporte (que é uma cortesia) em meu tempo livre - afinal também tenho emprego - em média em 3 dias, usando 3G dentro do onibus. Lamento pelo seu depoimento.

A finalidade desta área do github é para reporte de bugs do modulo, e não para suporte. Como não tenho a resposta para o @rafatriolo, deixo em aberto para quem puder ajudá-lo. Tenho planos de fazer um video sobre a instalação com o modulo do Deivison, mas por enquanto estou empenhado em finalizar as gravações dos videos do curso de Magento para lojista que disponibilizarei em breve no udemy.com.

Obrigado pela compreensão @rafatriolo .

**Comment by magnored** [comment]
desculpe @r-martins r-martins... nao quis ofender, é que estou precisando de uma ajuda quanto o problema #47 e vi que ninguem estava mais postando nada, logo, subentendi que o projeto morreu
O email eu estava mandando para suporte@pagsegurotransparente.com

**Comment by rafatriolo** [comment]
@r-martins obrigado pela resposta, acho seu modulo muito bom e melhor ainda a ideia de fazer um curso de magento no udemy. Voltando ao problema, eu consegui resolver removendo as classes validate-cc-number e validate-cc-type do campo de preenchimento do numero do cartão de crédito. Por algum motivo desconhecido , qdo eu removo essas classes, o magento reconhece o require-entry ai ele valida os campos e tudo acontece como deveria. Entendo que é uma solução paliativa , mas agora ja sei onde fica o problema. Tem algum javascript pra essas classes? Abs

**Comment by rafatriolo** [comment]
@r-martins melhorando ainda meu comentário acima , é o problema é na classe validate-cc-number.
Abs

**Comment by r-martins** [comment]
Oi @rafatriolo,
As classes validate-cc-type e validate-cc-number são nativas do magento, e apenas validam se o nr digitado corresponde ao tipo de cartão selecionado e se o nr é válido.
Receio que vc deva ter customizado algo no checkout e removeu o campo do cc_type, ou desagrupou o nr do cartao em mais de um campo, ou ainda utilizando mascaras de cartão. Isso geralmente é o que causa esse tipo de problema.
Se quiser ver o funcionamento dessas validações, veja em js/prototype/validation.js.

Forte abraço!

**Comment by r-martins** [comment]
@rafatriolo 
Há alguns dias notei que o OSC remove o ccard.js no checkout.
Siga as instruções que eu comentei [aqui](https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/170#issuecomment-241139612) e deve resolver.
