### ISSUE TITLE
Sem download da última versão

### ISSUE THREAD

**Issue by isaacqueiroz** [r-martins/PagSeguro-Magento-Transparente#111]
Oi Martins, é coisa atoa. 

Fui baixar manualmente a última versão do módulo usando o link da página oficial (https://github.com/r-martins/PagSeguro-Magento-Transparente/downloads), descrito por "Faça download da última versão aqui" e o resultado é "There aren’t any uploads for this repository.". 

Eu geralmente uso o do repositório mesmo, mas pode ser que outra pessoa veja o erro e fique na dúvida de o que fazer. Enfim... Só notificando por aqui para não atrapalhar por outros meios, pode fechar a issue quando ler.

Continue com o ótimo trabalho! o7

**Comment by r-martins** [comment]
Obrigado pelo feedback.
