### ISSUE TITLE
Boleto não é gerado abre uma páginal "about:blank" 

### ISSUE THREAD

**Issue by davirs** [r-martins/PagSeguro-Magento-Transparente#112]
Estou com magento 1.9
ao finalizar o pedido com boleto, o pedido é gerado normalmente, a tela success aparece..
ao clicar no botão "imprimir boleto" abre uma nova aba "about:blank"

algumas vezes funciona 90% não funciona

o que será que tem errado?

**Comment by davirs** [comment]
poxa.. tenho o PRO e nem assim um feedback... tenso.

**Comment by davirs** [comment]
2015-07-22T00:56:16+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Problemas ao processar seu pagamento. Estado de entrega com valor inválido:  RIO DE	JANEIRO(53034)' in /chroot/home/metamorf/metamorfosebrasil.com/html/app/Mage.php:595
Stack trace:
#0 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/community/RicardoMartins/PagSeguro/Model/Abstract.php(13): Mage::throwException('Problemas ao pr...')
#1 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/community/RicardoMartins/PagSeguro/Model/Payment/Cc.php(101): RicardoMartins_PagSeguro_Model_Abstract->proccessNotificatonResult(Object(SimpleXMLElement))
#2 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Order/Payment.php(1035): RicardoMartins_PagSeguro_Model_Payment_Cc->order(Object(Mage_Sales_Model_Order_Payment), 139.9)
#3 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Order/Payment.php(339): Mage_Sales_Model_Order_Payment->_order(139.9)
#4 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#5 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#6 [internal function]: Mage_Sales_Model_Order->place()
#7 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#8 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(784): Mage_Sales_Model_Service_Quote->submitAll()
#12 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/community/Inovarti/Onestepcheckout/controllers/AjaxController.php(406): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_AjaxController->placeOrderAction()
#14 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('placeOrder')
#15 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /chroot/home/metamorf/metamorfosebrasil.com/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 /chroot/home/metamorf/metamorfosebrasil.com/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /chroot/home/metamorf/metamorfosebrasil.com/html/index.php(87): Mage::run('', 'store')
#19 {main}

**Comment by r-martins** [comment]
Olá @davirs, tudo bom?
Como podemos ver no seu log, a loja está enviando o estado do cliente incorretamente.
Verifique se as queries do pacote de tradução foram inseridas corretamente, para que o cliente selecione o estado no dropdown, e não digitando manualmente.

Sobre o suporte que mencionou, ele não existe nem mesmo no PRO. O suporte é oferecido por outro canal, e é uma cortesia para os usuários de todas as versões, fornecida no meu tempo livre.
Esta área é destinada apenas à reporte de erros no módulo, e contribuições de correções.

Espero ter ajudado.
Grande abraço e boas vendas.

**Comment by davirs** [comment]
eu já testei o campo estado e está certo.
A única coisa diferente que tenho nesta loja é o modulo do pedro 
teixeira para correios, mas creio que não interfere em nada.

o texto está correto, apenas no log parece que tem 2 espaços.. nas 
outras 2 lojas funciona perfeito com mesmo pacote de tradução e mesmo 
checkout



On 22/07/2015 19:18, Ricardo Martins wrote:
>
> Olá @davirs <https://github.com/davirs>, tudo bom?
> Como podemos ver no seu log, a loja está enviando o estado do cliente 
> incorretamente.
> Verifique se as queries do pacote de tradução foram inseridas 
> corretamente, para que o cliente selecione o estado no dropdown, e não 
> digitando manualmente.
>
> Sobre o suporte que mencionou, ele não existe nem mesmo no PRO. O 
> suporte é oferecido por outro canal, e é uma cortesia para os usuários 
> de todas as versões, fornecida no meu tempo livre.
> Esta área é destinada apenas à reporte de erros no módulo, e 
> contribuições de correções.
>
> Espero ter ajudado.
> Grande abraço e boas vendas.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/112#issuecomment-123886355>.
>

-- 
	
*DAVI REINOLDO DOS SANTOS*
	
	
/Tecnólogo em Sistemas para Internet/
	
/Especialista em Gestão e Estratégia em E-commerce./
	
/(47) 9989-5219/
	
/davi.reinoldo/
	
/davi.reinoldo@outlook.com/
