### ISSUE TITLE
Valor da parcela inválido ao usar módulo de fidelidade

### ISSUE THREAD

**Issue by edmarholanda** [r-martins/PagSeguro-Magento-Transparente#113]
Olá Ricardo,

Eu uso o módulo Reward Points desenvolvido pela Magestore. O funcionamento do módulo é simples: toda compra gera créditos que podem ser usados em compras futuras. Ocorre que a forma como o desconto (uso de pontos) é feito parece ser incompatível com a PagSeguro Transparente.

Todas as vezes que os clientes tentam fazer o pagamento e usar seus créditos no sistema de fidelidade, aparece este erro: "Problemas ao processar seu pagamento. Valor da parcela inválido: 41.70(53041)".

Quando desmarcada a opção de resgatar os pontos, o pagamento é aprovado imediatamente e sem qualquer erro.

Sinceramente não sei se se trata de bug ou incompatibilidade com outro módulo, mas preferi relatar o caso aqui, pois vi que outros usuários estão com problemas similares (e eles podem usar módulos de fidelidade ou de descontos). Se o caso for de suporte feito à parte, basta me informar seu contato para contratação.

**Comment by magnored** [comment]
Acho que o que aconteceu é que o modulo nao fez o "refresh" após o desconto do pedido..
tente usar esse fix https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/110#issuecomment-119758970 juntamente com esse https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/47#issuecomment-67471889

Qualquer coisa me chama no skype (dizero.infoeng), nao sou expert mas posso tentar te ajudar

**Comment by edmarholanda** [comment]
Muito obrigado, @magnored.

Uso o RWD padrão do Magento (não uso OSC). Qual desses dois arquivos devo alterar para implementar a solução do #47 ?

/app/design/frontend/base/default/template/checkout/onepage/review/totals.phtml
/app/design/frontend/base/default/template/checkout/cart/totals.phtml
/app/design/frontend/default/iphone/template/checkout/onepage/review/totals.phtml

**Comment by magnored** [comment]
verifica se tem onepagecheckout/onepage/reviews/totals.phtml

**Comment by edmarholanda** [comment]
Não tenho nenhuma pasta chamada "onepagecheckout".

**Comment by edmarholanda** [comment]
Tentei usar apenas a solução do #110 e o erro persiste. 

Adicionei o código da solução #47 em todos os arquivos totals.phtml e ainda no carrinho aparece um erro (o código inserido aparece como erro perto do botão Finalizar compra). Talvez eu não tenha inserido no local correto ou da forma coreta... Vou continuar tentando.

**Comment by magnored** [comment]
@edmarholanda possivelmente entao a pasta seria essa:
/app/design/frontend/base/default/template/checkout/onepage/review/totals.phtml

Mas se nao deu certo entao tente o seguinte (lembre-se de retirar tudo o que vc ja tentou anteriormente e voltar para o default):

no arquivo pagseguro.js, apos a linha 110 (var grandTotal = response.responseJSON.total;) insira estes campos:

               grandTotal = parseFloat(grandTotal);
               grandTotal = grandTotal + window.dez_conto;
               window.granTotal = grandTotal;

Procure pelo arquivo payment_method.phtml (ou talvez no seu checkout é apenas method.phtml) e insira no final do arquivo:

<script type="text/javascript">
	jQuery('#p_method_pagseguro_cc').click(function() {
		jQuery('.onestepcheckout-cart-table tfoot tr:nth-child(2)').hide();
		jQuery('.onestepcheckout-cart-table tfoot tr:last-child .price').html(jQuery('.onestepcheckout-cart-table tfoot tr:first-child .price').html());
		var desconto = jQuery('.onestepcheckout-cart-table tfoot tr:last-child .price').html();
		valor_total = desconto.substring(2).replace(/\,/g, '.');
		valor_total = parseFloat(valor_total);
		valor_total = valor_total * 0.1;
		window.dez_conto = valor_total;
	});
</script>

**Comment by edmarholanda** [comment]
payment_method.phtml realmente não tenho (até tenho, mas é do OSC que eu não habilito).

Os únicos aquivos method.phtml que tenho estão nas pastas do PayPal (default/template/paypal/express).

**Comment by r-martins** [comment]
@edmarholanda, o @magnored  está certo no primeiro comentário. Provavelmente o metodo de pagamento não está sendo atualizado quando a pessoa muda a forma de pagamento pra usar os reward points.
Faça um teste:
- logo após aplicar os descontos, acesse sualoja.com/pseguro/ajax/getGrandTotal e veja se o total está correto, já com os descontos.
Se estiver correto, então o @magnored está certo. Você precisa encontrar um jeito de chamar o RMPagSeguro.getInstallments() no javascript logo após aplicar os descontos. Isso fará com que o total das parcelas seja atualizado.

Agora, se o total nessa url estiver errado, aí você vai precisar analisar o que o modulo faz, e implementar em \RicardoMartins_PagSeguro_AjaxController::getGrandTotalAction pra que ele devolva o total certo. É com esse total que o modulo pedirá ao PagSeguro os totais das parcelas.

Grande abraço e sucesso nas vendas.
