### ISSUE TITLE
Problema na URL de retorno do pagseguro

### ISSUE THREAD

**Issue by magnored** [r-martins/PagSeguro-Magento-Transparente#114]
Ola a todos...tenho observado que o status dos meus pedidos no pagseguro nao estao sendo atualizados no magento... 
observei que no pagseguro é exibido a seguinte imagem:
![image](https://cloud.githubusercontent.com/assets/7586874/8932612/983992d4-3514-11e5-88d7-56445f8941e9.png)
Pelo erro 403, minha loja estaria negando o acesso ao pagseguro ? 
Eu utilizo cloudflare, poderia ser ele que esta negando o acesso ?

Quando eu tento acessar o endereço diretamente, é exibido a mensagem:
![image](https://cloud.githubusercontent.com/assets/7586874/8932640/bc4d30e0-3514-11e5-9edb-761962967cf2.png)

**Comment by magnored** [comment]
Pessoal...problema solucionado
Era o cloudflare mesmo que estava bloqueando, coloquei uma excessao para nao fazer cache da URL de retorno e agora esta dando certo

**Comment by r-martins** [comment]
Obrigado pelo feedback.
