### ISSUE TITLE
SenderHash não funciona no Firefox e Chrome

### ISSUE THREAD

**Issue by Guuedes** [r-martins/PagSeguro-Magento-Transparente#115]
Olá, estou precisando de uma grande ajuda se puder me ajudar ficarei grato.
Estou a alguns dias tentando encontrar a solução para o meu problema mas não encontro uma solução, instalei o modulo Checkout Transparente e habilitei a API tudo certo, mas no Firefox e no Chrome a validação do campo onde o cliente insere os numeros do cartão não reconhece a bandeira e não aparece as parcelas, já no IE funciona perfeitamente.
Inspecionando o elemento identifiquei que esses navegadores não estão carregado o SenderHash e pude identificar o erro abaixo, acredito que seja este o problema, verifiquei se estava faltando arquivo no hiden e está tudo Ok aparentemente,  poderia me ajudar?

Google Chrome:
Uncaught ReferenceError: RMPagSeguro is not defined = RMPagSeguro.updateSenderHash();
(anonymous function) @ inline-f4bed71860.js:10

Esse erro aparece em => (directpayment.phtml) acusando o campo abaixo como ser o erro:

                clearInterval(iid);
                RMPagSeguro.updateSenderHash();  <= "AQUI ESTÁ O ERRO NO CHROME"
                RMPagSeguro.addBrandObserver();
                RMPagSeguro.addCardFieldsObserver();
            }
        }, 4000);
    }
    preparePagSeguro();

Firefox:
Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.

Log:
Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário. Um problema de JavaScript pode ter ocorrido.".

Encontrei a sugestão abaixo mas não está claro para mim:
https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203887479-Problemas-ao-processar-seu-pagamento-sender-hash-is-required-53150-

Fico no aguardo, obrigado
Guedes

**Comment by Guuedes** [comment]
Ricardo, desde já agradeço pelo módulo com certeza irá me ajudar bastante com as vendas..  Desde quando surgiu o erro acima estou tentando encontrar uma solução, identifiquei que pode ser devido minha loja utilizar SSL (https) e dessa forma não funciona, fiz o teste utilizando apenas http e quando digito o numero do cartão nada acontece de primeiro, mas se dou um refresh na página funciona, o meu problema é semelhante ao da pergunta #24 mas preciso que funcione com o SSL, lembrando que este erro acontece no Chrome e Firefox, no IE está normal com ou sem SSL.

Obrigado
Guedes

**Comment by Guuedes** [comment]
Boa noite, @r-martins referente o erro mencionado acima, consegui resolver e gostaria de compartilhar caso alguém passe pela mesma situação.
Descobri que o que estava causando este erro não era nem o modulo nem o magento e sim Cloudflare, logando na conta na aba Speed existe a opção Rocket Loader e por padrão estava habilitada como automático, após alterar para Off o site passou a funcionar normalmente.
Com isso o site perdeu volocidade de YSlow mas não muito significante.
Abraço a todos!

**Comment by davirs** [comment]
Aqui eu estou tendo exatamente a mesma dificuldade e não tenho cloud flare.
meu servidor é um nexcess sip-200...

eu já tentei usar sem sucesso a sugestão do ricardo
"Você pode contornar o problema chamando o metodo "RMPagSeguro.updateSenderHash()" antes de realizar o submit do form do pedido, por exemplo no botão de finalizar pedido do seu checkout."

simplesmente tem hora que funciona tem hora que não..

**Comment by Guuedes** [comment]
@davirs Pelo pouco que entendo sobre o assunto, este erro é cusado por algum arquivo Java, se voce tiver algum modulo ou modificou sua loja para otimizar velocidade, isto pode ter causado o problema, nomeu caso desabilitei uma função que otimizava os arquivos Java, perdi um pouco de velocidade mas a loja funcionou, não sei se posso lhe ajudar mas espero que consiga resolver o seu problema.
Boa sorte!

**Comment by davirs** [comment]
@Guuedes valeu as dicas brother!!! pior que não tem nada no servidor.. não tem nenhum booster, nenhum compressor de arquivos etc..
eu cheguei a usar o magento pelado pra testes inclusive. 

Eu acho que na verdade por algum motivo o erro do senderhash ocorre somente com que se cadastra pela forma nativa do magento (criar conta)
Quem se cadastra pelo OSC nunca deu problema... Foi o único padrão que identifiquei.

**Comment by r-martins** [comment]
@Guuedes, @davirs 
Qual OSC estão utilizando nos testes?

**Comment by Guuedes** [comment]
@r-martins Obrigado pela atenção, estou usando = "deivisonarthur-OSC-Magento-Brasil-6-Pro."
No meu caso o problema foi resolvido desabilitando a opção Rocket Loader em minha conta Cloudflare.

**Comment by r-martins** [comment]
Obrigado @Guuedes,
Documentei sua solução na central de ajuda.

Obrigado.

**Comment by magnored** [comment]
Coloca a pagina do checkout como excessao no cloudflare pq ai vc nao perde
a velocidade do rocket launcher
Em 30/09/2015 3:46 PM, "Ricardo Martins" <notifications@github.com>
escreveu:

**Comment by Guuedes** [comment]
Ok @r-martins, e obrigado @magnored sua dica ajudou a melhorar a velocidade do meu site, habilitei novamente o Rocket Launcher e adicionei a exeção do checkout no Page Rules em minha conta Cloudflare, deu certo muito obrigado!

**Comment by marcosnolasco** [comment]
@Guuedes , desculpe minha ignorância, mais qual regra você utilizou no Page Rules para adicionar essa exceção no checkout?
