### ISSUE TITLE
Pedido Cancelado pelo Pagseguro produtos não Retornam pro Estoque

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#116]
Ricardo, bom dia 

Tudo bem ?

Primeiramente, obrigado pelo módulo realmente estou muito satisfeito.Porém, venho relatar um problema que tem ocorrido com frequência. Quando pedido é cancelado pelo pagseguro, ele altera o status do pedido no magento para cancelado, mas os produtos desse pedido não voltam para o estoque automaticamente. Tem como você me ajudar a resolver? 

Abs 

Rafael

**Comment by magnored** [comment]
Somente para constar...
Estou utilizando o modulo apenas para TEF atualmente e tive esse problema tbm!

**Comment by r-martins** [comment]
Acho que está duplicado com o #6, mas vou ver com mais calma esta questão.
Hoje eu sei que o módulo não faz a devolução, pois envolveria um estorno. Preciso analisar direitinho e resolver isso.
Qualquer contribuição é bem-vinda.

**Comment by magnored** [comment]
Somente para constar tbm, nao utilizo mais o pagseguro (somente para tef) uso o modulo do mercado pago e tive um pedido rejeitado (cancelado) e o mesmo nao estou os produtos para estoque
Acredito que seja algo que envolva mais o magento do que o proprio plugin

**Comment by rafatriolo** [comment]
Fala Ricardo , Feliz ano novo !!! 

Seguinte , o problema acontece na seguinte situação: quando o cliente faz a compra com o cartao de credito , o pedido fica com o status de 'review' , e se a transação é recusada , o pagseguro retorna o cancelamento do pedido , mas os produtos do pedido ficam com estoque 0 e ficamo como esgotados. 

Vou ver se encontro alguma coisa , mas por enquanto é só. 

Abs

**Comment by luizwbr** [comment]
Acredito que o problema possa estar no retorno da url. Testei aqui tanto no ambiente sandbox quanto no de produção e o plugin está funcionando corretamente.

Fiz uma correção para deixar o pedido como 'closed' também

**Comment by lab12web** [comment]
Mesmo problema aqui, quando o pedido é cancelado pelo PagSeguro o status muda para cancelado no Magento mas os produtos do pedido não voltam para o estoque.

Ricardo, chegou a avaliar o pull request do @luizwbr?

**Comment by filipenunes75** [comment]
Bom dia ! estou à mais de 6 meses tentando resolver um problema e ninguem do PAGSEGURO me ajuda! 

Tenho Magento 1.9.0.1  - Versão do do PS 3.5.0.

Após a compra, se o PS não autorizar a compra, o pedido é cancelado automaticamente.

Ao cancelar, o produto que o cliente comprou não volta ao estoque! 

isso esta me causando um baita problema! 

Pagar para usar eu pago, só que ninguem resolve meu problema onde devo recorrer???

 Fico no aguardo de alguem do PagSeguro que possa resolver ! pois estou muito bravo com isso!

**Comment by r-martins** [comment]
@filipenunes75 tudo bom?
Você chegou a ver se o retorno está funcionando corretamente na sua loja?
Acabei de realizar um teste na [loja teste](http://pagseguro-exemplo-osc.ricardomartins.net.br/), com o produto [abl002](http://pagseguro-exemplo-osc.ricardomartins.net.br/catalog/product/view/id/372/s/leather-tablet-sleeve/category/21/).
Ao submeter o pedido com cartão 4111111111111111 o mesmo foi deduzido do estoque, e retornado automaticamente após o pagseguro devolver o retorno de Cancelado.

Se o problema persistir, abra uma [solicitação de suporte](https://suporte.contabilizei.com.br/hc/pt-br/requests/new) antes de seguir por aqui.

Grande abraço e sucesso nas vendas.
