### ISSUE TITLE
Retorno "Chave Publica inválida. Re-autentique a aplicação" e Cartão Crédito Inválido.

### ISSUE THREAD

**Issue by wabreu** [r-martins/PagSeguro-Magento-Transparente#118]
Olá
Estou com problemas no checkout de uma loja Magento 1.6.2 com OSC e o Pagseguro Transparente Pro.

Os cartões não são validados e nenhuma forma de pagamento funciona.

No log abaixo (com algumas da loja e cliente informações suprimidas) recebo a mensagem de Chave Publica Inválida.

O ambiente é produção.

Alguém tem ideia do que pode estar ocorrendo?
Já verifiquei o token e email na Faq do site do Ricardo e estão ok.

Obrigado

2015-08-28T15:27:55+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => 'emailpagseguro',
  'token' => 'tokenpagseguro',
  'paymentMode' => 'default',
  'paymentMethod' => 'boleto',
  'receiverEmail' => 'emailr',
  'currency' => 'BRL',
  'reference' => '100000017',
  'extraAmount' => '0.00',
  'notificationURL' => 'http://www.siter.com.br/pseguro/notification/',
  'itemId1' => '17',
  'itemDescription1' => 'Vaso Amarelo Em Cerâmica 3143',
  'itemAmount1' => '0.10',
  'itemQuantity1' => '1',
  'senderName' => 'Nome Cliente',
  'senderEmail' => 'email@gmail.com',
  'senderHash' => '98b3609401ef2403e11181923aa9ae328c5cb578902f31b8a0025c7e92806ffe',
  'senderCPF' => '01201201212',
  'senderAreaCode' => '31',
  'senderPhone' => '32323232',
  'shippingAddressStreet' => 'Rua',
  'shippingAddressNumber' => '300',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => 'Bairro',
  'shippingAddressPostalCode' => '3000130',
  'shippingAddressCity' => 'Belo Horizonte',
  'shippingAddressState' => 'MG',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '14.80',
  'billingAddressStreet' => 'Rua e',
  'billingAddressNumber' => '300',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => 'Bairro',
  'billingAddressPostalCode' => '30000130',
  'billingAddressCity' => 'Belo Horizonte',
  'billingAddressState' => 'MG',
  'billingAddressCountry' => 'BRA',
  'public_key' => 'nr.chavepublica',
)
2015-08-28T15:27:55+00:00 DEBUG (7): Retorno PagSeguro (/transactions): 'a:2:{s:4:"auth";b:0;s:10:"xmlRetorno";s:132:"<auth><error><message>Chave Publica invÃ¡lida. Se necessÃ¡rio, re-autentique a aplicaÃ§Ã£o.</message><code>101</code></error></auth>";}'
2015-08-28T15:27:55+00:00 DEBUG (7): Retorno inesperado do PagSeguro. Retorno: a:2:{s:4:"auth";b:0;s:10:"xmlRetorno";s:132:"<auth><error><message>Chave Publica invÃ¡lida. Se necessÃ¡rio, re-autentique a aplicaÃ§Ã£o.</message><code>101</code></error></auth>";}

**Comment by r-martins** [comment]
Olá @wabreu,
Parece que a licença está com o codigo incorreto ou inválido.
Refaça a autenticação da aplicação em http://r-martins.github.io/PagSeguro-Magento-Transparente/pro/app.html.

Lembrando que esse canal é destinado apenas a bugs.
O suporte é uma cortesia oferecido no pagseguro-transparente@ricardomartins.net.br. ;)
