### ISSUE TITLE
Erro no modulo pagseguro

### ISSUE THREAD

**Issue by Marcoscavd** [r-martins/PagSeguro-Magento-Transparente#119]
Rodrigo,
Primeiramente parabéns pelo modulo ele nos ajuda bastante.

Estou com erro de cartão inválido e o modulo não abre a opção de selecionar qual o cartão.

magento 1.9.1.1
modulo atual do magento connect

**Comment by lhcarvalho** [comment]
@Marcoscavd, estou tendo o mesmo problema. Você conseguiu alguma solução?

**Comment by dandara6** [comment]
Eu também estou com o mesmo problema! :(

**Comment by r-martins** [comment]
Senhores, vocês chegaram a ver esse link na central de ajuda?
https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203585029--Cart%C3%A3o-inv%C3%A1lido-aparece-para-qualquer-cart%C3%A3o-digitado

Reabram se necessario.
