### ISSUE TITLE
Erro no Checkout Transparente

### ISSUE THREAD

**Issue by dandara6** [r-martins/PagSeguro-Magento-Transparente#120]
Após digitar todos os dados e ao clicar em "finalizar compra", nada acontece.

Segue o log:

Retorno PagSeguro (/transactions): 'Forbidden'
Acesso nÃ£o autorizado Ã  Api Pagseguro. Verifique se vocÃª tem permissÃ£o para usar este serviÃ§o. Retorno: 'Forbidden'
Falha na autenticaÃ§Ã£o com API do PagSeguro. Verifique email e token cadastrados. Retorno pagseguro: Forbidden

Porém, o pagseguro já autorizou. Já fiz aquele teste do token para verificar se estava autorizado e está. 
@r-martins 
Outro problema que apareceu no log, foi que algumas informações não são mais as mesmas e gostaria de saber como alterar, pois apareceu no log as informações antigas:

  'email' => '(o e-mail antigo)',
  'token' => '(o token antigo)',
  'paymentMode' => 'default',
  'paymentMethod' => 'boleto',
  'receiverEmail' => '(o email antigo',

Como faço para alterar essas informações,logo que no Magento => Sistemas => Configurações => Metodo de pagamento.. eu já alterei. Já limpei os caches, atualizei e etc.

**Comment by r-martins** [comment]
Olá @dandara6,
Receio que já estejamos tratando disso via chamado.
Vamos manter esse canal apenas para bugs, ok?

Grande abraço! ;)

**Comment by dandara6** [comment]
Otimo! Obrigada!

2015-09-28 13:29 GMT-03:00 Ricardo Martins <notifications@github.com>:
