### ISSUE TITLE
 Hash de comprador inválido.(53091)

### ISSUE THREAD

**Issue by edmarholanda** [r-martins/PagSeguro-Magento-Transparente#121]
É a primeira vez que recebo este erro. 

Log:
2015-10-06T12:09:10+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53091</code><message>sender hash invalid.</message></error></errors>'

**Comment by r-martins** [comment]
Veja se sua chave/token são validos. Ou acesse https://pagsegurotransparente.zendesk.com/hc/pt-br/search?utf8=%E2%9C%93&query=hash&commit=Pesquisa

**Comment by edmarholanda** [comment]
Bom, antes de ocorrer este problema pela primeira vez recebi centenas de pagamentos.

O token pode se tornar inválido "do nada"?

**Comment by r-martins** [comment]
Do nada, não.
Mas se migrar de servidor e usar uma <key> no xml diferente, ou se salvar as configuracoes mudando um pouquinho o token, já ocasiona o problema.
Acesse sualoja.com/pseguro/ajax/getSessionId e veja se retorna false ou o session_id.

**Comment by edmarholanda** [comment]
Retornou uma session_id.

Não fiz nenhuma alteração de servidor nem nas configurações.

Vou aguardar pela próxima tentativa de pagamento.

**Comment by r-martins** [comment]
Pode ser que o session-id tenha expirado durante o checkout.
