### ISSUE TITLE
Problema com sender name invalid

### ISSUE THREAD

**Issue by maaxxicarvalho** [r-martins/PagSeguro-Magento-Transparente#122]
Olá estou usando a versão 2.2.0, instalado via modman e estou recebendo o erro abaixo:

DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>sender name invalid value: MICHEL  Beluche</message></error></errors>

**Comment by r-martins** [comment]
Bacana @maaxxicarvalho,
Realmente nem sabia que isso daria erro também.
Farei o fix na proxima versão.
Por ora, você pode adicionar um ucfirst() e strtolower() no Params.php, onde tem o tratamento do sender name se não quiser esperar pela correção.

**Comment by maaxxicarvalho** [comment]
@r-martins você não concorda que seria necessário um trim tbm?

```
'senderName'    => ucfirst(strtolower(trim($senderName))),
```

Por que o erro que o PagSeguro retorna mostra que ele encontrou um espaço a mais entre nome e sobrenome.

Eu particularmente entendo que o próprio PagSeguro deveria tratar isso mas....

**Comment by r-martins** [comment]
Esse trim pra remover espaços duplicados foi adicionado na ultima versao no metodo removeDuplicatedSpaces

**Comment by maaxxicarvalho** [comment]
@r-martins Ok, ok. Estou questionado por que se você reparar na mensagem de erro ele tem um espaço a mais entre o nome e sobrenome, confira:

```xml
<message>sender name invalid value: MICHEL  Beluche</message>

**Comment by r-martins** [comment]
Estranho, pq no teste que fiz aqui ele tirou certinho...
Até pensei que fosse por causa do maiusculo... Mas nao..
4:42:32 PM Magicento Notification
           string 'MICHEL Beluche' (length=14)

**Comment by maaxxicarvalho** [comment]
@r-martins Realmente ele não está removendo os espaços, fiz um teste adicionando o código abaixo. Sem o código ele gera erro de sender name, com o código ele corrige os espaços a mais e a capitalização e o boleto é gerado.

```php
$senderName = sprintf(
            '%s %s',
            ucfirst(strtolower($this->removeDuplicatedSpaces(trim($order->getCustomerFirstname())))),
            ucfirst(strtolower($this->removeDuplicatedSpaces(trim($order->getCustomerLastname()))))
        );

**Comment by maaxxicarvalho** [comment]
@r-martins outro "problema" que encontrei. Quando o sender name gera erro, ou mesmo quando um CPF inválido é inserido. Ele gera o pedido normalmente, rediciona para a tela de boleto. Porém nesse caso não é possível imprimir o boleto uma vez que o número de transação não foi gerado pelo PagSeguro. Alguma dica para resolver isso?

Obrigado!

**Comment by r-martins** [comment]
Vamos por partes. Nessa issue estamos falando dos espaços.
Vc consegue debugar o metodo removeDuplicatedSpaces e ver se ele está removendo os espaços duplicados?
Qual versao do php?

**Comment by maaxxicarvalho** [comment]
@r-martins Desculpe por misturar os assuntos. Não consigo debugar agora por que estou sem ambiente local. Versão do PHP 5.5.12.

Fiz uns testes locais com um script e a função não está removendo os espaços mesmo.

**Comment by r-martins** [comment]
Testei agora na 5.5.26 e foi.
Certeza que não é cache da versao antiga?!?

**Comment by maaxxicarvalho** [comment]
Não por que eu não tinha a versão antiga instalada. Eu usava iPagare nessa loja, inclusive conversei com vc ontem a respeito no Meet Magento.
A loja está hospedada na Nexcess e eu fiz um upgrade do Magendo e passei a usar seu módulo.

**Comment by r-martins** [comment]
Bacana,
Agradeceria se você conseguisse debugar isso pra mim, pois em todos os testes que fiz o espaço duplo foi removido...
Consegue dar um feedback quando descobrir?

**Comment by maaxxicarvalho** [comment]
ok Ricardo, vou fazer os testes e te dou um retorno.
Por hora resolvi da maneira que te passei.

Mais um detalhe, estou usando o One Step Checkout da Inovarti, não sei se isso pode exercer alguma influência.

**Comment by edmarholanda** [comment]
Também estou com a versão 2.2.0 e ocorreu o mesmo problema hoje em dois pedidos diferentes.

Problemas ao processar seu pagamento. Nome do comprador com valor inválido: Xxxxxxx Xxxxxx Xxxxx Xxxxxx (53015)

Não sei se ajuda, mas... No log aparece o nome do cliente com os dois espaço, mas no e-mail que recebo informando o erro aparece o nome do cliente com apenas um espaço.

**Comment by r-martins** [comment]
@maaxxicarvalho e @edmarholanda, se um de vocês puder abrir um chamado informando os dados de acesso ssh e como posso fazer para simular, eu agradeço. Não consegui simular nos meus ambientes.

**Comment by edmarholanda** [comment]
Como abro um chamado?

Curiosamente, tive milhares de transações sem este problema, mas desde a última versão do módulo já tive várias transações com o erro 53015.

**Comment by marcostae** [comment]
Também tive esse problema... Acho que ele acontece porque no fim do 1o nome do cliente ele adicionou um espaço. Como a função está só removendo os espaçamentos duplos esse espaço final acaba passando, e somado com o espaçamento entre o nome e o sobrenome acaba formando o espaçamento duplo...

**Comment by edmarholanda** [comment]
Bem pontuado, @marcostae . Em todos os meus casos ocorreu exatamente isso (estou corrigindo manualmente o nome de cada cliente).

**Comment by redati** [comment]
uso php 5.6
Sabem se essa solução que estou tentando pode resultar em outros erros ? 

//return preg_replace('/\s+/', ' ', $string);
return preg_replace_callback('/\s+/',function ($matches) {global $replacements;return $replacements[$matches[0]];},$string);

**Comment by edmarholanda** [comment]
Olá @redati depois que implementou esta solução não teve mais problemas?

**Comment by redati** [comment]
@edmarholanda Não implementei pois  so estou com o ambiente de produção e preciso ter certeza antes de mudar. Sim é neste arquivo no método removeDuplicatedSpaces.  
A função preg_replace no php 5.6 não funciona, deve usar preg_replace_callback e fiz teste em uma string e está funcionando mas não sei se aplico ao módulo.

**Comment by edmarholanda** [comment]
Retornei para vesão 2.1.0 e o problema parou. Já tive dois pagamentos hoje onde o primeiro campo (nome) tinha um espaço no final e o pagamento foi aprovado normalmente.

**Comment by redati** [comment]
@edmarholanda como consigo essa verão? essa minha correção resultou em mais vendas perdidas :/ 
amigo @r-martins desculpa incomodar ai, rs, mas tem previsão ou alguma correção temporária que eu poderia fazer ?

**Comment by edmarholanda** [comment]
Remova o módulo. Vá à Magento Connect e baixe por lá a versão antiga. Na aba Release Notes aparecerão as versões anteriores.
