### ISSUE TITLE
Valor total não atualiza ao parcelar com juros.

### ISSUE THREAD

**Issue by mefornazari** [r-martins/PagSeguro-Magento-Transparente#123]
Bom, estou com um problema ao utilizar o módulo com o OSC do Deivison.. (ambos estão com a última versão).

Quando o cliente seleciona o pagamento com parcelamento com juros o valor total no OSC não atualiza, o mesmo continua mostrando o valor total sem os juros.
Aí quando o cliente finaliza a compra o valor total fica errado e isso acaba me trazendo prejuízos.. :(

Já tentei de tudo, inclusive as soluções informadas aqui no github e no FAQ do módulo e nada até agora.. Se alguém souber alguma solução, talvez alguém que já passou pelo mesmo problema..

**Comment by tavinus** [comment]
@mefornazari , notei que você fechou o tópico. Conseguiu resolver o problema? Aqui está acontecendo a mesma coisa (praticamente). 

O meu problema é que ao selecionar as parcelas de pagamento depois de digitar os dados do cartão, o total com juros não é carregado como total do pedido. Isso ocorre tanto no OSC quanto com ele desativado. Sem o OSC ele me fala o valor das parcelas correto com juros, mas o total não bate com as parcelas (sem juros). Estou achando que pode ser conflito com algum outro módulo mas não tenho certeza.

Aparentemente ele carrega o valor correto para pagamento (não fechei uma venda pra testar), mas o total no fechamento do pedido do magento nao considera o valor dos juros.

Vou tentar atualizar o módulo. Se não resolver acho que vou ter que desinstalar outros módulos e ir testando. Nao tem nada nos logs. Alguém tem alguma dica de como eu debugo isso? Talvez em alguma totals.phtm? Eu não achei a call Javascript das parcelas (achei dos outros campos do cartao na pagseguro.js).

A pagina do OSC até dá refresh na tela de review do total quando as parcelas são selecionadas, mas carrega o valor sem os juros como total do pedido, independente do que foi selecionado. Joguei a var do getInstallments no console e pra ele chega tudo certinho. Aí não sei se ele não passa o valor pra quem devia ou o que...
