### ISSUE TITLE
Botão de Imprimir Boleto em Imagem

### ISSUE THREAD

**Issue by mefornazari** [r-martins/PagSeguro-Magento-Transparente#124]
Ao finalizar pedido em boleto ou tef aparece o botão "Clique aqui para imprimir seu boleto" ou "Clique aqui para realizar o pagamento".

Tem como transformar esses 2 botões em imagem?
De qualquer forma fica como sugestão para a próxima atualização :D

**Comment by r-martins** [comment]
Olá @mefornazari 
Na verdade esta é uma customização que pode ser feita pelo seu desenvolvedor frontend.
Basta copiar o arquivo app/design/frontend/base/default/template/ricardomartins_pagseguropro/payment/info.phtml para app/design/frontend/**seuPackage**/**seuTema**/template/ricardomartins_pagseguropro/payment/info.phtml e alterar a gosto.

Obrigado pelo feedback mesmo assim.
Sucesso nas vendas!
