### ISSUE TITLE
Status de pedido sendo repetidamente alterado..

### ISSUE THREAD

**Issue by mefornazari** [r-martins/PagSeguro-Magento-Transparente#125]
Olá gente, estou com um problema, os status dos pedidos estão sendo alterados e atualizados toda hora repetidamente, vi que isso é um retorno do pagseguro, mas como fazer ele parar de se repetir? Isso trás muitos problemas..

Segue anexos:
Pedidos sendo cancelado a cada 1 hora:
![01](https://cloud.githubusercontent.com/assets/15149180/10561577/b172c136-7505-11e5-97f1-5acf455514d8.png)

Pedidos atualizando fatura e pagamento toda hora:
![02](https://cloud.githubusercontent.com/assets/15149180/10561578/b1789458-7505-11e5-96c2-40113061d2e4.png)

**Comment by mefornazari** [comment]
Faturas repetidas:
![03](https://github-cloud.s3.amazonaws.com/assets/15149180/10566427/b1db0280-75c5-11e5-9900-97ca223db69d.png)

**Comment by r-martins** [comment]
Sua loja está no cloudflare?
É possivel que o seu servidor esteja devolvendo status de falha para o PagSeguro, e o mesmo fica insistindo em reenviar a transação.

**Comment by r-martins** [comment]
Por favor reabra quando interagir novamente.
