### ISSUE TITLE
Ajuda com CSS

### ISSUE THREAD

**Issue by magnored** [r-martins/PagSeguro-Magento-Transparente#130]
Galera... me da um help com o CSS como no exemplo abaixo:
![image](https://cloud.githubusercontent.com/assets/7586874/11154732/4f5348d0-8a28-11e5-93f3-2f275c5391ff.png)
Queria deixar os campos MES e ANO na mesma linha e o campo CVV ao lado do numero do cartao de credito

Exemplo do que eu tentei:
#pagseguro_cc_cc_number {
    float: left;
}

Eu nao manjo muito, mas ja googleei varias coisas e consegui ajustar diversos campos no meu checkout, contudo, os do pagseguro sao os unicos que nao consigo mexer

Se alguem puder colocar um exemplo eu me viro com o resto...

Abs

**Comment by r-martins** [comment]
Use o width também.
Se ainda tiver dúvidas, pede uma ajuda no [magentobr](http://groups.google.com/group/magentobr).
Vamos manter esta área (issues) destinadas apenas à bugs do módulo. ;)

Grande abraço!
