### ISSUE TITLE
Após atualização não finaliza Pedido com o Pagseguro

### ISSUE THREAD

**Issue by renatoaleksander** [r-martins/PagSeguro-Magento-Transparente#131]
Boa Noite

Após a atualização para versão 2.3.1 não consigo finalizar os pedidos por Boleto, conforme segue abaixo, sem o link para o boleto e qdo na loja virtual ao clicar em imprimir boleto abre-se uma página em branco.

Qdo a venda é feita por Cartão de Crédito volta para a página de pagamento não finalizando o pedido.

Gostaria de saber se houve alguma mudança drástica no módulo.

No aguardo

Renato Aleksander

Boleto Bancário - à Vista 
Id da Transação: 
Exibir Boleto

Retornei para versão 2.2.0 voltou a funcionar versão do magento 1.9.1.1

**Comment by r-martins** [comment]
Oi @renatoaleksander,
Não vi sua issue antes, mas receio que não tenha tido mudanças que causassem esse tipo de erro.
Se puder, vamos tratar deste caso via chamado, pois preciso entender melhor o que houve.
Pode ser?

Obrigado.
