### ISSUE TITLE
Erro ao emitir boleto

### ISSUE THREAD

**Issue by phdiegues** [r-martins/PagSeguro-Magento-Transparente#133]
Boa tarde pessoal.

Aqui em minha loja, alguns pedidos simplesmente não emitem o boleto. Quando clico em "Exibir Boleto" ele abre novamente o pedido em uma nova janela. Acontece isso com mais alguem?

**Comment by diegobarbetta** [comment]
Aqui também acontece o mesmo problema. No log do PagSeguro o retorno acontece normal, mas o botão da página sucesso exibe uma janela em branco...

**Comment by phdiegues** [comment]
Exatamente isso. A taxa de desistência dos meus pedidos caiu muuuuito por conta disso.

**Comment by r-martins** [comment]
O problema foi relatado no #131.
Se voces puderem interagir comigo via chamado, eu gostaria de analizar o problema mais a fundo.
Ou se já foi resolvido - mesmo que via chamado - peço que finalizem a issue.

Conto com vocês. ;)

**Comment by diegobarbetta** [comment]
Ok @r-martins, vou abrir um chamado.

Abs

**Comment by r-martins** [comment]
Valeu @diegobarbetta

**Comment by r-martins** [comment]
Em tempo: espera-se que esse erro tenha sido corrigido na versão 2.3.1 do modulo PRO. Por favor, veja se o modulo PRO de vocês é > 2.3.1 e reabram se necessário, fornecendo mais detalhes.
