### ISSUE TITLE
Fatura gerada mais de uma vez (inclusive e-mails para o cliente)

### ISSUE THREAD

**Issue by luciosribeiro** [r-martins/PagSeguro-Magento-Transparente#134]
O módulo está gerando várias faturas com valor (0,00) e enviando vários e-mails de fatura para o cliente.

**Comment by Pirula** [comment]
Aqui também e alguns pagamentos o magento não confirma, tenho que confirmar manualmente na página do PagSeguro

**Comment by r-martins** [comment]
Tentem ver na tela de pedido no pagseguro, qual status que o servidor de vocês devolveu ao pagseguro quando ele enviou a notificação do pedido.
Receio que o servidor de vocês está processando a notificação do PagSeguro, mas devolvendo algum status que não o 200, fazendo com que o Pagseguro fique tentando enviar várias vezes a mesma notificação.

**Comment by arthurmartins** [comment]
@luciosribeiro também passei por este problema.

Isto ocorre pois por algum motivo o PagSeguro envia novamente a notificação de pagamento aprovado e para cada nova notificação o módulo gera um novo invoice, com o valor zerado.

Já corrigi este problema e fiz um pull request para o @r-martins.

**Comment by r-martins** [comment]
Resolvido no pull request do @arthurmartins e publicado na ultima versão.
