### ISSUE TITLE
Falha ao obter o token do cartao ou sender_hash

### ISSUE THREAD

**Issue by rose200** [r-martins/PagSeguro-Magento-Transparente#135]
Instalei o módulo no meu servidor local e tudo funciona ok. Quando, finalmente, coloquei o site na hospedagem, nem chego a colocar dados do cartão, basta selecionar a forma de pagamento para receber a mensagem de erro. Já desinstalei e o erro persiste. 
Onde está o problema? Alguma configuração do servidor? Uso Magento 1.9.2. Alguém pode dar uma luz?

**Comment by rose200** [comment]
A quem interessar possa, resolvi o problema trocando a versão do php de 5.5 para 5.3.

**Comment by r-martins** [comment]
Obrigado por compartilhar sua solução @rose200.
De qualquer forma, acredito que este problema geralmente é gerado por problemas de JavaScript, e não de PHP.
De qualquer forma, seu feedback é muito bem-vindo.
Obrigado.
