### ISSUE TITLE
Parcelamento customizado

### ISSUE THREAD

**Issue by matneves** [r-martins/PagSeguro-Magento-Transparente#136]
Olá Ricardo,

Estou configurando o módulo do pagseguro transparente para calcular parcelas com base num outro módulo que temos. Ele irá calcular a parcela com valor mínimo de 50 reais, por exemplo, e por isso não fica com algo fixo como 6x sem juros sempre, fica dependente to valor total. Enfim, tudo funciona bem, até o momento de enviar para o pagseguro. Estou enviando o valor do produto + frete + extraAmount (com o juros) e ele sempre me retorna que o valor da parcela não bate. É possível configurar um parcelamento personalizado desta forma ou o pagseguro sempre vai esperar a configuração de parcelamento feita no painel dele?

**Comment by r-martins** [comment]
Oi @matneves,
O Magento vai bater nas parcelas configuradas no backend dele.
De acordo com a documentação do módulo, dá pra ser diferente, informando a qtd de parcelas sem juros no atributo **noInterestInstallmentQuantity**, mas eu não uso isso no módulo. Sempre vou buscar do que está configurado no painel do pagseguro.
Pode ser uma melhoria interessante pra se pensar...
