### ISSUE TITLE
Problema com nome inválido quando digitado Nome'espaço'

### ISSUE THREAD

**Issue by Lemondr2** [r-martins/PagSeguro-Magento-Transparente#137]
Estou tendo problemas com alguns clientes com o erro 53015. Refiz o percurso realizado e quando se digita o 'Nome' + espaço, ocorre esse erro.
![erro 53015](https://cloud.githubusercontent.com/assets/10519663/12481033/a527e65e-c02d-11e5-8f3e-b7c55953b583.png)

**Comment by r-martins** [comment]
@Lemondr2 
Estranho estar tendo esse problema com uma versão recente do módulo.
Esse problema foi corrigido.
Tente executar um 
`Mage::helper('ricardomartins_pagseguro/params')->removeDuplicatedSpaces('Ana Paula  Almeida de Menezes')`
e veja se o nome retorna algo errado.

De acordo com a documentação, tem que ser assim:

Parâmetro HTTP:
senderName
Elemento XML:
<payment> <sender> <name>
￼
Nome completo do comprador.
Especifica o nome completo do comprador que está realizando o pagamento.
Presença: Obrigatório.
Tipo: Texto.
Formato: No mínimo duas sequências de caracteres, com o limite total de 50 caracteres.
