### ISSUE TITLE
Erro com o nome do estado

### ISSUE THREAD

**Issue by apzeiro** [r-martins/PagSeguro-Magento-Transparente#138]
Ao finalizar o pedido via cartão de crédito dá o seguinte erro:
"Problema ao processar seu pedido. Estado de entrega com inválido: PARANá(53034)".

Já testei com estados que não possuem acento e dá o mesmo erro. verifiquei minha tabela de estados e está correta. Lembrando que eu uso a tradução do Mario Sam onde as estados são apresentados em uma combo-box ao usuário, ou seja, não precisa digitar.

Estou anexando uma imagem do erro.
![erro-estado](https://cloud.githubusercontent.com/assets/11969850/12511473/b039140c-c0f8-11e5-861f-cdadc1432a26.jpg)

**Comment by r-martins** [comment]
Conforme comentado via chamado, foi corrigido na versão 2.3.3. 
Me avise se ainda estiver enfrentando problemas.

Obrigado por avisar de qualquer forma.
