### ISSUE TITLE
Problemas com Notificacoes PagSeguro

### ISSUE THREAD

**Issue by carlo-isengard** [r-martins/PagSeguro-Magento-Transparente#139]
Estou com problema no retorno das notificacoes do pagseguro depois de instalar o certificado ssl no meu site. Nas transações do pagseguro constam as informacoes 

![image](https://cloud.githubusercontent.com/assets/15998053/12725604/b04762dc-c8fa-11e5-86a5-c2d4e4e6eb61.png)

E no painel do magento eu nao recebo nenhuma informacao sobre a transacao.

**Comment by r-martins** [comment]
Tente acessar manualmente essa url de notificação, a fim de tentar descobrir pq seu servidor está dando erro 403.
Em último caso tente usar /index.php/pseguro/notification.
Entendo que não conseguir acessar a url não seja um bug do módulo, certo?
Se eu puder ajudar mais, falamos via chamado, tudo bem?
