### ISSUE TITLE
Saldo do pagseguro

### ISSUE THREAD

**Issue by LBCorr** [r-martins/PagSeguro-Magento-Transparente#141]
Pessoal, é possível liberar o pagamento com saldo do pagseguro (na versão pro, aplicação)? Encontrei em Paymentmethods a opção ($options[] = array('value'=>'401','label'=>'Saldo PagSeguro');), tem como liberar o uso, seja como nova opção de pagamento ou listado em debito/tef?
Abraço

**Comment by r-martins** [comment]
Olá @LBCorr,
Embora o retorno dos meios possa incluir outros métodos, na [documentação](http://download.uol.com.br/pagseguro/docs/pagseguro-checkout-transparente.pdf) só consta creditCard, boleto ou eft, como mostrado na página 18.

Seria meio surreal se permitisse, né? =)

**Comment by LBCorr** [comment]
Ah, tranquilo Ricardo, como vi no arquivo seria mais uma opção, mas seria surreal mesmo kkk
Abraço
