### ISSUE TITLE
Nao recebimento de Status

### ISSUE THREAD

**Issue by carlo-isengard** [r-martins/PagSeguro-Magento-Transparente#143]
Estou com problemas no recebimento das notificacoes do pagseguro. Dentro da transacao, indica o seguinte
![image](https://cloud.githubusercontent.com/assets/15998053/13249867/6a392d0e-da05-11e5-9300-d3e3d5efe9ef.png)
 e dentro do magento nao foi recebida nenhuma notificacao

**Comment by r-martins** [comment]
Não consegui ver a imagem que tentou postar (aparece um thumb do png gigante).
Se possível, mande por chamado. Embora não tenha visto a imagem, não me parece ser um bug.
