### ISSUE TITLE
Não consigo fazer Upgrade so Pag Seguro

### ISSUE THREAD

**Issue by mauretex** [r-martins/PagSeguro-Magento-Transparente#144]
Ola Ricardo não consigo fazer o upgrade para uma versão mais atual quando mando ele fazer ele instala mas depois o magento não funciona mais e retorna uma mensagem escrita que é requerido o modulo do Ricardo pagseguro, oque devo fazer e como fazer para atualizar o sistema? 

Att

**Comment by r-martins** [comment]
Oi @mauretex,
Para ter o modulo pro, é necessario ter o modulo base instalado.
Baixe e instale o modulo base [aqui no github](https://github.com/r-martins/PagSeguro-Magento-Transparente/archive/master.zip) mesmo.

**Comment by mauretex** [comment]
Quando faço a atualização ele continua dando esse erro.

Module "RicardoMartins_PagSeguroPro" requires module 
"RicardoMartins_PagSeguro".

Attt

Em 23/02/2016 22:01, Ricardo Martins escreveu:
>
> Oi @mauretex <https://github.com/mauretex>,
> Para ter o modulo pro, é necessario ter o modulo base instalado.
> Baixe e instale o modulo base aqui no github 
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/archive/master.zip> 
> mesmo.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/144#issuecomment-187994494>.
>

-- 

blank <http://www.focalouca.com.br> 	*Mauro s.*
Pós-venda

E-mail: mauro@focalouca.com.br
Site: http://www.focalouca.com.br


Esta mensagem e quaisquer anexos são confidenciais aos destinatarios. 
Qualquer uso não autorizado é proibido

**Comment by mauretex** [comment]
Ola Ricardo já subi esse modulo tentei fazer o upgrade do sistema e 
continua aparecendo o mesmo erro.

Module "RicardoMartins_PagSeguroPro" requires module 
"RicardoMartins_PagSeguro".

Att




Em 23/02/2016 22:01, Ricardo Martins escreveu:
>
> Oi @mauretex <https://github.com/mauretex>,
> Para ter o modulo pro, é necessario ter o modulo base instalado.
> Baixe e instale o modulo base aqui no github 
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/archive/master.zip> 
> mesmo.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/144#issuecomment-187994494>.
>

-- 

blank <http://www.focalouca.com.br> 	*Mauro s.*
Pós-venda

E-mail: mauro@focalouca.com.br
Site: http://www.focalouca.com.br


Esta mensagem e quaisquer anexos são confidenciais aos destinatarios. 
Qualquer uso não autorizado é proibido
