### ISSUE TITLE
Erro ao salvar formas de pagamento

### ISSUE THREAD

**Issue by aquere** [r-martins/PagSeguro-Magento-Transparente#145]
Após instalar o magento, a primeira coisa que fiz foi instalar o módulo do PagSeguro Transparente, porém na hora de salvar as formas de pagamento o mesmo apresenta este erro:

Ocorreu um erro ao salvar esta configuração: Maximum key size must be smaller 56

Tentei na versão 1.9.1 e na 1.9.2.4

Estou usando um servidor compartilhado apenas para testes

**Comment by r-martins** [comment]
Acho que já tratamos do seu caso via chamado.
Esse não é um erro do módulo, mas sim do Magento. 
Veja se o tamanho da chave <key> no app/etc/local.xml é maior que 56 caracteres e diminua.
