### ISSUE TITLE
Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#146]
Olá,

Possuo o serviço do pagseguro transparente pro(cartão, boleto e TEF), porém ao finalizar o pedido no cartão ele da a mensagem "Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.", o site já foi configurado e estava certo e funcionando, porém esta acontecendo isso agora.

OBS: site em funcionamento desde 17/02/16 porém só agora foi aparecer esse problema.

**Comment by r-martins** [comment]
@richard-nexxus peço que abra um chamado relatando isso e informando o url da loja com a dificuldade.
Vamos manter esse espaço para bugs do módulo mesmo, ok?

Obrigado pela colaboração.
