### ISSUE TITLE
Cliente Pessoa Jurídica

### ISSUE THREAD

**Issue by apzeiro** [r-martins/PagSeguro-Magento-Transparente#147]
Gostaria de saber se dá algum problema caso o cliente seja Pessoa Jurídica.
Nesse tipo de cadastro o campo Data de Nascimento não é exibido.

**Comment by r-martins** [comment]
Olá @apzeiro 
O módulo suporta cpf/cnpj no campo de cpf.
No entanto, o cartão de crédito **sempre** terá um cpf, que corresponde ao portador do cartão, e deve ser informado. (Regras do PagSeguro)
Acredito que o mesmo vale para data de nascimento.

No caso de dúvidas peço que use o canal de suporte para um atendimento mais rápido.
Mais informações: https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/205033015-Gostaria-de-vender-pra-Pessoa-Juridica-mas-pede-CPF
