### ISSUE TITLE
Problema ao finalizar pedido

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#148]
Olá, estava com um problema com o modulo pro (cartão boleto e TEF), estava dando a mensagem de erro Sender_Hash e "Erro ao finalizar o pedido..." inverti as ordens de pagamento no checkout e deu certo, coloquei boleto em segundo e cartão em primeiro como padrão de forma de pagamento. =D

**Comment by r-martins** [comment]
@richard-nexxus 
Analisei a questão e fiz um teste (video abaixo)
![Video do teste](http://g.recordit.co/BLkyRx8y8n.gif)
Veja que parece estar ok.

Tem algo mais que possa me falar para tentar reproduzir?
Existe uma correção pra isso numa versão bem antiga. Qual versão está usando dos módulos?

**Comment by richard-nexxus** [comment]
Estou utilizando a versão mais nova do modulo.
Creio que o problema então deve estar relacionado ao meu checkout personalizado da MageStore(onestepcheckout)
