### ISSUE TITLE
Problemas de finalização de compras como visitante

### ISSUE THREAD

**Issue by Lytron1** [r-martins/PagSeguro-Magento-Transparente#149]
Olá Ricardo,

Temos um cliente em comum que usa sua extensão para o pagseguro Pro e estamos tendo alguns problemas.

O boleto só é gerado quando a pessoa é cadastrada, quando faz a compra como visitante não gera o boleto.

Você poderia nos dizer o que é ou dar uma olhada no porque isso ta acontecendo.

Obrigado,

Romulo

**Comment by r-martins** [comment]
@Lytron1 
Realmente era um bug do módulo e será corrigido na versão que estou lançando em alguns minutos (2.5.1) no github. Não é preciso atualizar o Pro.
Se você usa o taxvat como cpf, bastará mapear o atributo como **Customer: CPF/CNPJ (taxvat)** no painel magento.
