### ISSUE TITLE
Problema com CPF e Sugestão

### ISSUE THREAD

**Issue by diego-goulart** [r-martins/PagSeguro-Magento-Transparente#150]
Olá Ricardo, primeiramente parabéns pelo módulo e pelo serviço.

Estou usando o módulo PRO juntamente com o OSC 6 Pro e tentei mapear o campo de CPF para o customer:taxvat (embora no formulário do OSC esteja billing:traxvat.

Até ai tudo bem, o problema é que na hora de enviar os dados para o pagseguro o mesmo retorna uma mensagem de erro informando que faltou o envio do "sender_cpf ou cnpj".

O problema acima não acontece se eu configurar o seu módulo para solicitar o cpf jundo aos dados do cartão.

Então eu tenho uma sugestão a fazer: 
Seria possível ao invés de apenas solicitar o cpf junto aos dados do cartão colocar um radio butom com a label "Usar cpf do cadastro" ?

Meu argumento para isso seria que o lojista daria as 2 opções ao cliente:
Cadastrar um CPF na conta e usar um cartão de terceiro (com outro CPF) no campo de CPF do proprietário do cartão.

Ou cadastrar um cpf na conta e selecionar o radio buttom para setar o mesmo cpf para o cartão de crédito.

**Comment by r-martins** [comment]
@diego-goulart 
A sugestão é boa. Só receio que o pessoal ia ficar mais confuso ainda na hora de configurar o módulo.
Quer fazer um pull request dessa melhoria?
Contribuições são sempre bem-vindas.

Obrigado pelo feedback. Vou colocar no roadmap pra ver o esforço. ;)
