### ISSUE TITLE
Token do Cartão em branco

### ISSUE THREAD

**Issue by diego-goulart** [r-martins/PagSeguro-Magento-Transparente#151]
@r-martins  eis o meu problema, você consegue me ajudar?

Quando digito qualquer cartão de crédido no modo de PRODUÇÃO  aparece **cartão de crédito inválido**

**Verificando os logs do console no chrome aparece:**
`Falha ao obter o token do cartao.
pagseguro.js:93 Object {10000: "invalid creditcard brand"}
pagseguro.js:92 Falha ao obter o token do cartao.
pagseguro.js:93 Object {10000: "invalid creditcard brand"}`

**Verificando os logs do módulo:**

```
2016-04-10T05:33:47+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash.
                    Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário.
                    Um problema de JavaScript pode ter ocorrido.
                    Se esta for apenas uma atualização de blocos via ajax nao se preocupe.
```

**Verifiquei os dados que estão indo no post e realmente o campo credit_card_token está vazio:**

`payment[sender_hash]:727238022c966a3888574510d8d0dd6b3a2f935c1b5530dad0ca2870a67726a3
payment[ps_card_type]:
payment[credit_card_token]:

### Outras informações:

**Token testado?** Sim, no site do módulo.

**URL:** http://www.cheiroecor.com.br
**Tipo do módulo:** Pro
**Tipo de licença:** aplicação
**Magento versão.** 1.9.2.4

**Comment by r-martins** [comment]
@diego-goulart 
Pelo que pude ver em http://www.cheiroecor.com.br/pseguro/test/getConfig, tem algo errado com a configuração da sua loja.
Geralmente nesses casos, que não consegue pegar o sessionId, e usa modelo de aplicação, o problema é o token.
Tente redigitar o token da loja e salvar as informações no painel do magento.

Grande abraço e boas vendas.

**Comment by diego-goulart** [comment]
@r-martins 
Bom dia, infelizmente não deu certo. Tentei tudo que sabia, até reinstalei tudo novamente.
o Método getConfig está retornando false na sessionId:
{"RicardoMartins_PagSeguro":{"version":"2.5.0","debug":true,"sandbox":false},"RicardoMartins_PagSeguroPro":{"version":"2.3.2","key_type":"app"},"session_id":false,"pagseguro_modules":["RicardoMartins_PagSeguro","RicardoMartins_PagSeguroPro"]}
