### ISSUE TITLE
Versão do php

### ISSUE THREAD

**Issue by coringafiles** [r-martins/PagSeguro-Magento-Transparente#152]
Boa tarde, ao tentar instalar através do magento connect recebo a seguinte mensagem:

"requires PHP version >= 5.2.1 and <= 5.6.16 current is: 5.6.19-0+deb8u1"

Alguma previsão de suporte a essa versão do php ou alguma modificação que eu possa fazer pra utilizar na versão 5.6.19.0?

**Comment by diego-goulart** [comment]
@coringafiles 
Tive um problema semelhante quando usava HHVM, daí fiz a instalação manual e deu certo.

**Comment by r-martins** [comment]
@coringafiles 
Pode tentar novamente por favor?

Obrigado.
