### ISSUE TITLE
Problemas ao processar pagamento

### ISSUE THREAD

**Issue by Lemondr2** [r-martins/PagSeguro-Magento-Transparente#153]
Estou recebendo o erro 53086.

Anexo screenshot.
![report](https://cloud.githubusercontent.com/assets/10519663/14615713/6494098e-057d-11e6-9534-f4741d9fbc9f.png)

**Comment by r-martins** [comment]
Oi @Lemondr2,
O valor mínimo aceito pelo PagSeguro é R$1,00.
