### ISSUE TITLE
Problema no retorno

### ISSUE THREAD

**Issue by rodrigoflyer** [r-martins/PagSeguro-Magento-Transparente#155]
Boa Noite,

Estou com um problema.

Efetuo a compra pelo pagseguro transparente no crédito, a conta é validada, mas no frontend não sai do loading.

Verifico no uol e o pagamento é realizado.

Já no boleto e no tef o loading fica o tempo todo, não permitindo realizar a transação.

**Comment by r-martins** [comment]
Olá Rodrigo,
É muito provável que tenha ocorrido algum erro no ajax de retorno, porém o pedido foi processado.
Experimente avaliar o retorno desse ajax de finalizacao de compra com o firebug ou similar.
