### ISSUE TITLE
Resposta de uma requisição instável

### ISSUE THREAD

**Issue by wellescastro** [r-martins/PagSeguro-Magento-Transparente#156]
Estava realizando testes de compras em uma loja que utiliza esse plugin, no entanto, em alguns momentos não pude prosseguir o processo de checkout devido a uma requisição: 
POST https://www.nomedaloja.com.br/pseguro/ajax/getSessionId que demorou mais de 2 minutos para responder.

**Comment by r-martins** [comment]
Olá @wellescastro 
Pode compartilhar o url da loja pra analisar?
Em alguns casos o proprio PagSeguro pode estar fora do ar, mas não acredito ser o caso, pois esse controller tem um timeout de 45 segundos na chamada externa. Talvez seja um problema da propria loja.

**Comment by r-martins** [comment]
@wellescastro 
Quando responder, por favor reabra a issue. Se preferir, abre um chamado, que costumo olhar com muito mais frequente.
