### ISSUE TITLE
Falha em processar pagamento em casos específicos 

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#157]
Olá @r-martins e outros membros que utilizam o modulo.

Estou notando em minha loja que está aumentando o numero de vezes em que o pagamento falha e retorna está mensagem  "Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe."

Não é registrado nada no log e é disparado o e-mail de falha de pagamento do magento, utilizo a versão pro junto com OSC 6.

O que reparei é que a falha é sempre ao tentar pagar com cartão a vista ou parcelado e que sempre são nos mesmos dispositivos, navegadores etc. no caso aqui sempre acontece com IOS com Safari, Windows 10 com Edge.

Outro detalhe que reparei é que na minha loja ao preencher os campos de endereço no checkout e da o erro tem hora que é salvo o endereço do cliente e outras vezes não, em certas vezes o cliente chama no chat e peço para ele atualizar a página (F5) e as vezes vai e outras mesmo assim não e continua o erro.

Alguém está tento este tipo de problema? Gostaria de alguma opinião pois em media a cada 10 vendas de 2 a 3 estão sendo perdidas por conta disto.

Obrigado.

**Comment by r-martins** [comment]
@fchiqueto obrigado pelo contato.
Enquanto não tivermos certeza que se trata de um bug ainda não corrigido, poderia abrir um chamado pra eu ver o seu caso de perto?

Obrigado.

**Comment by fchiqueto** [comment]
Obrigado pelo retorno @r-martins vou fazer alguns testes antes durante fim de semana em um horário de menos movimento na loja e lhe dou um retorno.

**Comment by fchiqueto** [comment]
@r-martins pode fechar esse issue pois simulei e não encontrei erro e como ninguém que usa o modulo não relatou nada parecido acredito que o problema é aqui mesmo.
