### ISSUE TITLE
Desconto no boleto 

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#160]
Bom dia,

Criei uma regra para desconto no boleto porem ao selecionar a forma de pagamento do Pagseguro e depois selecionar o boleto, o desconto desaparece e não volta mais.
Isso está relacionado com algo no modulo do pagseguro?
Meu checkout é o da MageStore(onestepcheckout)

Agradeço desde já

**Comment by budswarez** [comment]
O mesmo ocorre comigo.

**Comment by r-martins** [comment]
Conseguem simular o problema em uma das lojas de teste?
http://pagseguro-exemplo.ricardomartins.net.br/
ou
http://pagseguro-exemplo-osc.ricardomartins.net.br/

**Comment by r-martins** [comment]
Senhores, consegui simular o problema e, embora não seja um problema do módulo - vocês teriam o mesmo problema se usasse o CC Salvo (nativo) - eu publique uma possível solução nesse link: https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/213956906

Grande abraço.
