### ISSUE TITLE
Falha ao processar pagamento junto ao PagSeguro.

### ISSUE THREAD

**Issue by perrera** [r-martins/PagSeguro-Magento-Transparente#161]
Eu estava utilizando o modulo,e parecia funcionar perfeitamente. Porem nos ultimos dois dias ele parou de funcionar. 
Ao selecionar pagamento com cartao de crédito , inserir os dados do cartão, e clicar em finalizar compra ocorre o seguinte erro:
"Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe",
Eu verifiquei e o arquivo pagseguro.log tem o seguinte erro:
"2016-05-25T00:34:45+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash.
                    Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário.
                    Um problema de JavaScript pode ter ocorrido.
                    Se esta for apenas uma atualização de blocos via ajax nao se preocupe."

No exception.log ocorre a seguinte mensagem:

2016-05-25T00:34:45+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.' in /chroot/home/combinad/combinado.com.br/html/app/Mage.php:595
Stack trace:
#0 /chroot/home/combinad/combinado.com.br/html/app/code/community/RicardoMartins/PagSeguro/Model/Payment/Cc.php(129): Mage::throwException('Falha ao proces...')
#1 /chroot/home/combinad/combinado.com.br/html/app/code/core/Mage/Sales/Model/Quote/Payment.php(160): RicardoMartins_PagSeguro_Model_Payment_Cc->validate()
#2 /chroot/home/combinad/combinado.com.br/html/app/code/community/Inovarti/Onestepcheckout/controllers/AjaxController.php(392): Mage_Sales_Model_Quote_Payment->importData(Array)
#3 /chroot/home/combinad/combinado.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_AjaxController->placeOrderAction()
#4 /chroot/home/combinad/combinado.com.br/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('placeOrder')
#5 /chroot/home/combinad/combinado.com.br/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /chroot/home/combinad/combinado.com.br/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /chroot/home/combinad/combinado.com.br/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 /chroot/home/combinad/combinado.com.br/html/index.php(83): Mage::run('', 'store')
#9 {main}

Se puder verificar e me dar um retorno. Obrigado.

**Comment by richard-nexxus** [comment]
você tem o certificado ssl no site? se não, precisá dele, ou então inverta as ordens dos pagamentos no checkout, colocando cartão em primeira opção

**Comment by perrera** [comment]
Tenho sim amigo, certificado SSL instalado. Hoje  recebi novamente esse erro, parece intermitente. Voce falou para inverter a ordem da formad e pagamento?

**Comment by perrera** [comment]
Eu voltei a ter erros, pensei que fossem intermitentes mas hoje estao ocorrendo novamente.
Eu consultei a logo e encontrei o seguinte erro>

2016-05-31T14:35:22+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53041</code><message>installment value invalid value: 60.82</message></error></errors>'
2016-05-31T14:36:49+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): 

Me parece que tem esse erro relatado em outra issue. Vou ter que tirar o modulo agora pois estou ha muitos dias com esse problema que comecou de repente.

**Comment by richard-nexxus** [comment]
Qual o site da loja?

**Comment by perrera** [comment]
combinado.com.br
Agora eu tive um cliente que ficou a manha inteira tentando pagar e
encontrava esse erro no "installmentValue".
Agora ele acabou de fazer o pagamento que foi aceito.

Eu fiquei verificando a log, realmente o valor está errado. Mas não
consegui encontrar o motivo disso.
Vc sabe como ele monta esse valor?

2016-05-31 12:13 GMT-03:00 richard-nexxus <notifications@github.com>:

**Comment by richard-nexxus** [comment]
Observando a loja pelo console do inspecionar elemento, ele apresenta um erro relacionado ao token, já tentou verificar se ele está digitado corretamente ou gerar um novo?

![cap](https://cloud.githubusercontent.com/assets/17569565/15687142/8f24c790-2749-11e6-8275-31f15df921cc.PNG)

**Comment by lucassdoliveira** [comment]
Eu tive esse problema, solucionei retirando um refresh que fazíamos via js no modulo onestepcheckout6, esse refrash fazia com que essas informações armazenadas via hidden se perdesse.

**Comment by agenciawebfuel** [comment]
@lucassdoliveira você poderia informar como fez isso?

**Comment by r-martins** [comment]
Alguém poderia tentar me explicar como eu conseguiria replicar o erro em http://pagseguro-exemplo-osc.ricardomartins.net.br ?
Esta é uma loja crua com o OSC do Deivison

**Comment by perrera** [comment]
O Ricardo, bom dia.
Eu nao sei exatamente como replicar. O que eu fiz foi acessar o checkout e escolhi a forma de pagamento e frete. Apos isso eu mudei  a forma de envio algumas vezes, o que faz com que a pagina atualize os totais a cada modificacao. Apos isso cliquei em finalizar a compra.
O erro aconteceu na sua loja tambem. Forma de pagamento cartao de credito.
Eu fiz agora pelo menos umas 5 vezes e o erro aconteceu.
Veja o erro>
http://enaweb.com.br/erros/rmartins_erro.jpg

**Comment by perrera** [comment]
Eu agora ate consegui gerar dois pedidos, 400000005 e 400000006. Porem o erro ocorreu por alguma  vezes antes de conseguir gerar esses pedidos.

**Comment by agenciawebfuel** [comment]
Parece bem aleatório @r-martins, você conseguiu ver o que poderia ser? conseguiu replicar?

**Comment by apzeiro** [comment]
Estou com o mesmo problema. Estava funcionando perfeitamente há meses e essa semana deu pau. 
No pagseguro.log aparece o seguinte erro:

```
2016-07-08T19:44:32+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash.
                    Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário.
                    Um problema de JavaScript pode ter ocorrido.
                    Se esta for apenas uma atualização de blocos via ajax nao se preocupe.

```

**Comment by r-martins** [comment]
Receio ter relação com #172 que foi corrigido há pouco na versão 2.5.5.
Conseguem testar e me dar um feedback?

Obrigado.

**Comment by apzeiro** [comment]
Oi Ricardo, infelizmente meu cliente pediu pra remover o módulo.
Eu tenho um backup de como estava antes de remover. Vou ver se consigo
rodar local e te falo.

Abraço.
Marcos

2016-08-30 23:09 GMT-03:00 Ricardo Martins <notifications@github.com>:
