### ISSUE TITLE
Não está gerando o boleto

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#163]
Olá, acontece algo parecido com alguém aqui? Em 3 vendas e não foi gerado o boleto para o cliente, o pedido aparece no pagseguro e o boleto não aparece no admin ao clicar abre uma nova aba com o pedido, no e-mail de pedido ou na conta do cliente não aparece o link para pagar o boleto. Até ai ok poderia ser um problema mais... são casos espaçados e já realizamos vendas por boleto e apareceu normal entre uma falha e outra... o que poderia ser? no log nada consta :(

**Comment by r-martins** [comment]
@fchiqueto 
De uma olhada no https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/208251746-Tela-em-branco-ao-tentar-imprimir-boleto-ou-pagar-TEF
