### ISSUE TITLE
Erro ao tentar salvar o token pagseguro

### ISSUE THREAD

**Issue by gustavoluna** [r-martins/PagSeguro-Magento-Transparente#164]
Bom dia!

Estou tentando configurar o modulo pagseguro transparente, porém ao tentar salvar o token o mesmo está apresentando uma mensagem de erro
"Ocorreu um erro ao salvar esta configuração: Maximum key size must be smaller 56" Existem alguma configuração para alterar isso.

**Comment by r-martins** [comment]
@gustavoluna 
Dê uma olhada em https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/211273983
