### ISSUE TITLE
DNA UOL 404 (Not Found)

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#166]
Estava conferindo pelo console minha pagina de pagamento e apareceu isto no log:

`dna.min.js:45 GET https://dna.uol.com.br/service/cookie?_=1466647217691 404 (Not Found)
dna.min.js:45 GET https://dna.uol.com.br/service/etag?_=1466647217692 412 (Precondition Failed)`

![ss](https://cloud.githubusercontent.com/assets/17584080/16289843/facb4ff0-38ce-11e6-8120-31116d6b0f1f.jpg)

**Comment by r-martins** [comment]
Acabei de enviar sua questão para o PagSeguro. Já vi isso acontecer, mas não afetou o checkout/compra.
Vamos ver o que eles dizem, ok?

Abs

**Comment by fchiqueto** [comment]
@r-martins gostaria de incrementar mais isto que começou aparecer hoje:
![ss](https://cloud.githubusercontent.com/assets/17584080/16427965/36f22b22-3d46-11e6-81d0-bc796408ac01.jpg)

Interfere no momento da compra?

**Comment by r-martins** [comment]
Sim, no checkout, onde os js sao inseridos.

**Comment by r-martins** [comment]
Tem o link da issue no github se quiser interagir direto com o lojista.

**Comment by fchiqueto** [comment]
Obrigado, vou procurar a issue

**Comment by r-martins** [comment]
Sobre o test de token válido, tem alguma sugestão?

**Comment by fchiqueto** [comment]
Não encontrei a issue... Nosso token é válido, descobri que esse ultimo ocorre em abas privadas dos navegadores, cliente quer comprar no serviço e da erro... Acredito que seja isso... 
O primeiro é bem aleatório já cheguei a ver ele novamente depois sumiu...

**Comment by r-martins** [comment]
Do token eu queria saber se tem algum jeito de testar se um token é válido.

Sent from my Android.
Em 28 de jun de 2016 5:02 PM, "fchiqueto" <notifications@github.com>
escreveu:

**Comment by fchiqueto** [comment]
Aparece no log se for inválido, aconteceu conosco venceu o cartão cadastrado no Pagseguro e não débitou a assinatura e não vimos...

**Comment by r-martins** [comment]
@fchiqueto ignore meus ultimos comentários.
Eu respondi pelo celular e achei que estava respondendo pro pessoal do PagSeguro, rs.
Eles já estão vendo a questão do DNA 404.

**Comment by r-martins** [comment]
@fchiqueto me ligaram hoje.
Qual url da sua loja?

**Comment by fchiqueto** [comment]
@r-martins o endereço é http://pepot.com.br/

**Comment by fchiqueto** [comment]
@r-martins fui conferir o log o PagSeguro e gerou um monte de códigos, poderia me dizer se encontraram algo?

**Comment by r-martins** [comment]
cobrei eles novamente hoje

**Comment by r-martins** [comment]
Sem resposta do PagSeguro pra esse caso. O último e-mail que tenho é que foi encaminhado pra equipe de desenvolvedores.

Se o problema continua, sugiro entrar em contato através do Fórum de desenvolvedores, disponível no link http://forum.pagseguro.uol.com.br/ ou através da Central de Atendimento PagSeguro:

Capitais e regiões metropolitanas: 4003-1775

Demais localidades, exceto celular: 0800-728-2174

**Comment by fchiqueto** [comment]
@r-martins investiguei esse erro e descobri depois de vários testes que o motivo disso é navegar em aba privada, acredito que tem cliente que navega em privado no serviço e compra ai aparece esses erros, se você puder encaminha essa informação para eles pode ser que ajude.
