### ISSUE TITLE
CRIT (2): Not valid template

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#167]
Hoje apareceu este erro no log:

2016-06-27T13:16:39+00:00 CRIT (2): Not valid template file:adminhtml/base/default/template/ricardomartins_pagseguro/form/info/cc.phtml

Verifiquei os arquivos e em meu servidor não se encontra os mesmo porem já foi realizado pedido por cartão normalmente e também já ocorreu falhas.

Nunca ouve esta pasta em meu servidor e ele nunca registrou isso no log utilizo a versão pro então neste caminho:
adminhtml/base/default/template/ricardomartins_pagseguropro/form/info
só tem esses arquivos:
boleto.phtml
tef.phtml

Minha dúvida é crio esta pasta com os arquivos? Tem algo errado? Instalei pelo magento connect e depois segui os passos para instalar a versão pro. Estou contando com a sorte com vendas no cartão... hora funciona outra hora da erro e não tem como fazer funcionar.

Outro detalhe é que pagamento por TEF no console diz que:
Banco do Brasil encontra-se indisponível e foi removido.
Porem o mesmo se encontra ainda como opção de pagamento

**Comment by r-martins** [comment]
Havia um erro no pacote do magento connect. Foi corrigido a cerca de uma semana.
Obrigado por reportar.
