### ISSUE TITLE
Erro Estado de entrega com valor inválido: RIO DEJANEIRO (53034)

### ISSUE THREAD

**Issue by edicarlosmv** [r-martins/PagSeguro-Magento-Transparente#168]
**Logs**
==> pagseguro.log <==
2016-06-28T00:49:06+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => 'suporte@elshadaidistribuidora.com.br',
  'token' => '+++++++++',
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => 'suporte@elshadaidistribuidora.com.br',
  'currency' => 'BRL',
  'creditCardToken' => '71cd4cc3c89743a69ce4f47cfe6efed6',
  'reference' => '100000100',
  'extraAmount' => '0.00',
  'notificationURL' => 'http://www3.elshadaidistribuidora.com.br/shop/index.php/pseguro/notification/',
  'itemId1' => '115',
  'itemDescription1' => 'CD ELAINE DE JESUS SOMOS A IGREJA',
  'itemAmount1' => '19.90',
  'itemQuantity1' => '1',
  'senderName' => 'Edicarlos Mangabeira Vieira',
  'senderEmail' => 'emvinfor@gmail.com',
  'senderHash' => '152bf01ba53c3cc3f165a3c221c8a314d5dd870a5112f1d9db1823f4bd19d086',
  'senderCPF' => '01086698665',
  'senderAreaCode' => '31',
  'senderPhone' => '32739583',
  'shippingAddressStreet' => 'Rua Iriquitia',
  'shippingAddressNumber' => '120',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => 'Taquara',
  'shippingAddressPostalCode' => '22730150',
  **'shippingAddressCity' => 'Rio de Janeiro',
  'shippingAddressState' => 'RIO DEJANEIRO',
  'shippingAddressCountry' => 'BRA',**
  'shippingType' => '3',
  'shippingCost' => '18.30',
  'billingAddressStreet' => 'Rua Iriquitia',
  'billingAddressNumber' => '120',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => 'Taquara',
  'billingAddressPostalCode' => '22730150',
  **'billingAddressCity' => 'Rio de Janeiro',
  'billingAddressState' => 'RIO DEJANEIRO',
  'billingAddressCountry' => 'BRA',**
  'creditCardHolderName' => 'Edicarlos mangabeira',
  'creditCardHolderBirthDate' => '23/12/1977',
  'creditCardHolderCPF' => '05888888555',
  'creditCardHolderAreaCode' => '31',
  'creditCardHolderPhone' => '32739773',
  'installmentQuantity' => '5',
  'installmentValue' => '8.34',
  'public_key' => 'PUB28ED0BE177594FD58F13EC4F7BCA21AF',
)
2016-06-28T00:49:08+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53034</code><message>shipping address state invalid value: RIO DEJANEIRO</message></error><error><code>53065</code><message>billing address state invalid value: RIO DEJANEIRO</message></error></errors>'

**Cabeçalho de envio do navegador**

Request URL:http://www3.elshadaidistribuidora.com.br/shop/index.php/onestepcheckout/ajax/placeOrder/
Request Method:POST
Status Code:200 OK
Remote Address:189.59.158.0:80
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:144
Content-Type:text/html; charset=UTF-8
Date:Tue, 28 Jun 2016 00:49:04 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=98
Pragma:no-cache
Server:Apache/2.4.12 (Ubuntu)
Set-Cookie:frontend=rgjigojl7pe34vlr81g35tljm5; expires=Wed, 29-Jun-2016 00:49:05 GMT; Max-Age=86400; path=/shop; domain=www3.elshadaidistribuidora.com.br; httponly
Vary:Accept-Encoding
X-Frame-Options:SAMEORIGIN
Request Headers
view source
Accept:text/javascript, text/html, application/xml, text/xml, */*
Accept-Encoding:gzip, deflate
Accept-Language:pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:1788
Content-type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:persistent_shopping_cart=M5B6nIfpU2CDL2V7v6A5TDOoEO2XXrtS8kFTcjJSP3132KtRY9; adminhtml=4870k8s79b1ftib72cor41cji1; frontend=rgjigojl7pe34vlr81g35tljm5; external_no_cache=1; _ga=GA1.3.1575857746.1467065272; __utma=42910499.1575857746.1467065272.1467065272.1467068912.2; __utmb=42910499.29.10.1467068912; __utmc=42910499; __utmz=42910499.1467065272.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); wooTracker=nE7g1u0KjKfy; __zlcmid=bLfeqk3gRMEqLJ
Host:www3.elshadaidistribuidora.com.br
Origin:http://www3.elshadaidistribuidora.com.br
Referer:http://www3.elshadaidistribuidora.com.br/shop/index.php/onestepcheckout/index/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
X-Prototype-Version:1.7
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
billing[radio_tipopessoa]:Física
billing[tipopessoa]:17
billing[email]:emvinfor@gmail.com
billing[customer_password]:123456
billing[confirm_password]:123456
billing[create_account]:1
billing[taxvat]:010.866.986-65
billing[ie]:
billing[firstname]:Edicarlos
billing[lastname]:Mangabeira Vieira
billing[telephone]:(31) 3273-9583
billing[fax]:
billing[postcode]:22730150
billing[street][]: Rua Iriquitia
billing[street][2]:120
billing[street][3]:
billing[street][4]:Taquara
**billing[city]:Rio de Janeiro
billing[region_id]:19**
billing[region]:
billing[country_id]:BR

Está batendo certinho com a lista de estado do banco de dados. Somente para esse CEP ocorre isso.

**Comment by r-martins** [comment]
O modulo até tenta tratar casos onde o checkout está mal configurado e envia o nome dos estados como RIO DE JANEIRO, incluindo acentuação, e camel case. Mas não trata casos como o seu, onde o usuário digitou tudo junto, como DEJANEIRO.
Pra resolver de uma vez, é só rodar o SQL do Mario Sam, que tá no pacote de tradução dele. Dessa forma, o usuário vai selecionar o estado no dropdown, ao invés de correr o risco de digitar na mão.

**Comment by edicarlosmv** [comment]
Mas puxa automático através do CEP. Não consegui achar onde é setado isso
no sistema. Pois no frontend a grafia está correta. E já rodei sql dele.
Em 28/06/2016 20:23, "Ricardo Martins" <notifications@github.com> escreveu:

**Comment by edicarlosmv** [comment]
Bom dia!

 

      Eu verifiquei que ao colocar o CEP, ele busca as informações conforme está na imagem em anexo. Eu suspeito que problema está no envio da URL para o pagseguro que está inserindo a informação errada. Eu não sei onde no sistema que é responsável por enviar as informações para o pagseguro e de onde ele busca. Pq o formulário envia as informações certar. Deve ter outra tabela de estado no magento.

 

Vc tem alguma ideia se há outra tabela além das que eu vi na query do  Mario Sam?

 

Atenciosamente,

 



 

De: Ricardo Martins [mailto:notifications@github.com] 
Enviada em: terça-feira, 28 de junho de 2016 20:23
Para: r-martins/PagSeguro-Magento-Transparente <PagSeguro-Magento-Transparente@noreply.github.com>
Cc: Edicarlos Mangabeira <edicarlos.mangabeira@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [r-martins/PagSeguro-Magento-Transparente] Erro Estado de entrega com valor inválido: RIO DEJANEIRO (53034) (#168)

 

O modulo até tenta tratar casos onde o checkout está mal configurado e envia o nome dos estados como RIO DE JANEIRO, incluindo acentuação, e camel case. Mas não trata casos como o seu, onde o usuário digitou tudo junto, como DEJANEIRO.
Pra resolver de uma vez, é só rodar o SQL do Mario Sam, que tá no pacote de tradução dele. Dessa forma, o usuário vai selecionar o estado no dropdown, ao invés de correr o risco de digitar na mão.
