### ISSUE TITLE
Faturas Duplicadas

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#169]
Ricardo, bom dia 
Tudo bem ? 
Parabens pelo seu módulo , realmente funciona muito bem. Mas estou tendo problemas com faturas duplicadas em pagamentos com cartão de credito e boleto. A primeira ele gera uma fatura com os dados corretos , e dps ele gera uma fatura para o mesmo pedido só que sem informação nenhuma e com valor 0,00 . Tem como você me ajudar com isso ?
Abs
Rafael

**Comment by r-martins** [comment]
@rafatriolo 
Tente apenas remover a url de retorno de dados no seu painel pagseguro. Reabra se não resolver, com os prints de exemplos por gentileza.

**Comment by rafatriolo** [comment]
@r-martins  , não resolveu. segue os prints: 
![problema1](https://cloud.githubusercontent.com/assets/13166395/17182920/ca7d1746-53fb-11e6-851f-c074fb2d05e9.JPG)

![problema2](https://cloud.githubusercontent.com/assets/13166395/17182924/d0bdf4b8-53fb-11e6-966b-a83da6fdee7b.JPG)

No primeiro print , eu fui em ver todas as faturas . Ai cliquei para exibir uma fatura duplicada (print 2) , o estranho é que o numero da transação do pagseguro é a mesmo da transação que gerou valor.

**Comment by r-martins** [comment]
Tente remover a URL de retorno nas configurações do PagSeguro.

Abs

Sent from my Android.

Em 27 de jul de 2016 13:15, "rafatriolo" <notifications@github.com>
escreveu:

**Comment by rafatriolo** [comment]
Fala @r-martins  ja removi todas as urls de retorno do pagseguro , mas ainda sim continuam chegando. Uma pergunta , no seu modulo as faturas são geradas automaticamente? Estou perguntando pq tlvz o modulo esteja gerando as faturas e o cliente esta gerando tbm as faturas manualmente. 

Abs

**Comment by r-martins** [comment]
@rafatriolo o modulo não gera a fatura sozinho na hora do pedido, a menos que o pagseguro envie a notificacao dizendo que foi pago (o que pode acontecer logo em seguida).
Receio que se receber varias notificacoes de pago, sejam geradas varias faturas.

**Comment by rafatriolo** [comment]
@r-martins  bom dia , tudo bem ?

Ainda estou tendo problemas com essas faturas , ele está gerando faturas duplicadas dps de pago. E o estranho é que são em alguns pedidos só. E no log aparecem as 2 faturas geradas , uma com o valor e a outra zerada, com o mesmo numero de transação.

**Comment by ratocuiara** [comment]
Veja a solução no link abaixo:
https://github.com/r-martins/PagSeguro-Magento-Transparente/commit/39e139bdecd28ff65ca4444272cad6dbd9a764b6

**Comment by rafatriolo** [comment]
@ratocuiara obrigado por ter me mostrado a solução. Eu fiz uns testes e parece que esta tudo ok agora, vou esperar um feedback do cliente. 

Abs,

**Comment by r-martins** [comment]
Estranho, pois esta solução foi aceita há algum tempo. Você não deveria ter o problema.

**Comment by rafatriolo** [comment]
Então @r-martins na verdade eu não tinha visto pelo github que vc já tinha atualizado o módulo.
