### ISSUE TITLE
Desconto Boleto Aplicando PagSeguro Transparente

### ISSUE THREAD

**Issue by budswarez** [r-martins/PagSeguro-Magento-Transparente#170]
Criei um regra para boleto com 10% porem ele esta aplicando no pagseguro transparente caso eu selecione boleto e depois selecione o pagseguro, até tentei forçar a regra mas não funciona.
Tentei até mesmo a seguinte:
Se TODAS condições forem VERDADEIRA :
Forma de Pagamento é Boleto

Forma de Pagamento não é Cartão de Crédito - via PagSeguro

Forma de Pagamento não é Cartão de Débito

Forma de Pagamento não é Cartão de Crédito

Normalmente teria apenas uma regra 
Se TODAS condições forem VERDADEIRA :
Forma de Pagamento é Boleto

Porem não  Funciona, ele continua com o valor da regra de desconto do boleto no pagseguro transparente.

**Comment by r-martins** [comment]
Voce diz, que ele está aplicando a regra do boleto quando seleciona cartao? É isso?

**Comment by budswarez** [comment]
Se eu adicionar o produto ir ao checkout e selecionar diretamente o pagseguro ( cartão ) o valor fica normal exemplo R$ 1,00, após se eu selecionar boleto que dá o desconto de 10% o valor do boleto fica R$ 0,80 até ai esta correto, porem se eu retornar a selecionar o pagseguro o valor fica 0,80 não retorna o valor R$ 1,00
O mesmo ocorre se eu chegar ao checkout selecionar boleto depois paypal ( normalmente deixo o boleto como padrão )

**Comment by r-martins** [comment]
Parece ser um problema do checkout, que não está atualizando os totais quando muda a forma de pagamento.
Qual checkout está usando?

**Comment by budswarez** [comment]
r-martins, já testei em 3 tipos de checkout, estou com o módulo do proprio paypal ( esse não tem transparente ) + 2 módulos da cielo para crédito e débito, o único que não atualiza o valor corretamente é o pagseguro transparente.
http://www.hoyo.com.br/ dá uma conferida ai adiciona produto até a ultima etapa e seleciona os modos de pagamento, verá que valor de todos atualizam normalmente menos o pagseguro transparente,
Fiz a instalação novamente do módulo pois havia removido, continua não atualizando o valor, fui fazer o teste com 2 cartões ele apresenta a msg "Verifique os dados do cartão digitado."

**Comment by magnored** [comment]
vc abriu o mesmo topico no git do OSC:
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/251

da uma olhada nesse commit que pessoal fez la, ele força a atualização dos descontos:
https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/c9d81a3d6588a61ff82b33314a08d781b4dbc349

**Comment by budswarez** [comment]
Sim em todos outros métodos de pagamento ele força porem no pagseguro
transparente mesmo o 1.5.3 baixado hoje não esta forçando.
Não atualiza o campo
[image: Imagem inline 1]
Se eu for diretamente pela forma de pagamento do pagseguro o campo fica 1
real, porem se for boleto depois retornar ao pagseguro esse campo fica com
o valor do boleto
Digitando meus dados verdadeiros do cartão obtive o seguinte retorno


[image: Imagem inline 2]

Veja que o alerta fala sobre o valor 0.90 mesmo no "Valor total" estar
1,00, pela lógica ele esta pegando o valor de 1 parcela que é do boleto.

Removi o produto,
Adicionei novamente
Fui direto na forma pag seguro transparente
Adicionei meus dados corretos e do meu cartão

[image: Imagem inline 3]

Mandei finalizar a compra

[image: Imagem inline 4]
Segue dados de dentro do magento do pedido

[image: Imagem inline 5]

Em 1 de julho de 2016 14:13, magnored <notifications@github.com> escreveu:

> vc abriu o mesmo topico no git do OSC:
> deivisonarthur/OSC-Magento-Brasil-6-Pro#251
> <https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/251>
>
> da uma olhada nesse commit que pessoal fez la, ele força a atualização dos
> descontos:
> eneiasramos/OSC-Magento-Brasil-6-Pro@c9d81a3
> <https://github.com/eneiasramos/OSC-Magento-Brasil-6-Pro/commit/c9d81a3d6588a61ff82b33314a08d781b4dbc349>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/170#issuecomment-230000446>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGwOGHVxW32tHjPq6j67QkBD9D7BjHLiks5qRUrKgaJpZM4JDTBi>
> .
>



-- 
_________________________________

Atenciosamente.
Hudson Henrique Schmidt
Marketing
47 9640-6375
*SKYPE:* budswarez

Pichau Informática
www.pichau.com.br

**Comment by budswarez** [comment]
![image](https://cloud.githubusercontent.com/assets/7081496/16529485/93c48dc2-3f99-11e6-85e1-d7d55460f138.png)

**Comment by budswarez** [comment]
https://github.com/magnored
Só ocorre o problema com o módulo dele o módulo da cielo funciona normalmente,
Selecionou boleto = aplicou 10% desconto no valor
Selecionou pagseguro transparente = deveria carregar o preço normal, porem carrega o preço com a regra de promoção aplicada, caso que não ocorre nos demais métodos.
Testei o onepage do próprio thema Porto, o OneStepCheckout, IWD checkout e firecheckout

**Comment by r-martins** [comment]
@budswarez 
Você consegue simular o problema em um dos dois ambientes puros abaixo?

- Checkout nativo magento: http://pagseguro-exemplo.ricardomartins.net.br/
- Checkout OSC Deivison: http://pagseguro-exemplo-osc.ricardomartins.net.br/

**Comment by magnored** [comment]
Eu uso o tema da porto tbm com o OSC, mas nao utilizo mais o pagseguro por causa das tarifas.
Contudo, quando eu utilizava o Pagseguro do ricardo eu só consegui fazer funcionar após usar o fix do eneas

**Comment by r-martins** [comment]
@magnored 
Só por curiosidade.. Vc está pagando menos de 3,69% com antifraude?

**Comment by magnored** [comment]
@r-martins to usando MercadoPago a 8,39% com 6x sem juros para o cliente.
Em 6x sem juros não há nenhum outro intermediador melhor que esse preço, contudo esse preço tbm estava valendo para boletos, então acabei instalando o modulo MOIP somente para boletos e TEF 3,49% + R$0,69 por transação concluida

**Comment by budswarez** [comment]
@r-martins  fiz o teste no ricardomartins.net o mesmo problema ocorreu criei a regra de 10% no boleto
ao selecionar boleto ele aplica o desconto de 10%
após seleciono cartão adiciono os dados do cartão o valor da parcela fica com o desconto aplicado

![image](https://cloud.githubusercontent.com/assets/7081496/16530262/a183eb2a-3f9d-11e6-9011-3088b2551218.png)

**Comment by r-martins** [comment]
@magnored interessante mesmo. Se todos seus clientes parcelam em muitas vezes, 8,39% pode ser vantajoso. Já estou vendo com o PagSeguro o que consigo fazer com as minhas taxas.

@budswarez Realmente é um problema do checkout. Fix o teste na [loja com checkout puro](http://pagseguro-exemplo.ricardomartins.net.br) do magento e o problema não ocorre como mostro abaixo. De qualquer forma, vou tentar ver se existe algo 'genérico' que eu possa fazer do meu lado.
![1cfe9vkikf](https://cloud.githubusercontent.com/assets/191149/16531050/2b73f458-3fa1-11e6-91b4-881c30519bd2.gif)

**Comment by budswarez** [comment]
Com TEF (Débito) Não ocorre, aparentemente é algo relacionado ao campo de parcelamento do cartão de crédito.

**Comment by magnored** [comment]
Detalhe:
No TEF só não ocorre quando ja te um banco selecionado, se ficar na opção SELECIONE O BANCO ele ainda continua aplicando o desconto.
Posso estar errado, mas quando eu estava usando o modulo eu observei isso

**Comment by r-martins** [comment]
Na vdd o modulo do deivison só atualiza os totais uma vez. Veja no firebug

**Comment by budswarez** [comment]
Estranho funcionar no módulo de pagamento transparente da Cielo.

**Comment by r-martins** [comment]
@budswarez sinto ter que discordar rs. Ele só atualiza o total qdo clica no boleto, igual o meu modulo, rs. Insisto que o problema é no checkout. ;(
![cmab6ldu0u](https://cloud.githubusercontent.com/assets/191149/16532287/705fb5ec-3fa7-11e6-93fa-d5cedc8b2ca7.gif)

**Comment by budswarez** [comment]
@r-martins  Veja que o campo de parcela "á vista 1,00" que no caso seria 1 x 1,00 não foi modificado como acontece no meu exemplo usando utilizo seu módulo.

**Comment by r-martins** [comment]
Veja q o total do pedido com cartão ficou errado do mesmo jeito.
A diferença é que o meu atualiza as parcelas com os juros q vc configurou
no PagSeguro, diferente do que está usando.

Sent from my Android.
Em 1 de jul de 2016 16:29, "budswarez" <notifications@github.com> escreveu:

**Comment by budswarez** [comment]
No meu caso não tem juros, o total ali ele atualiza quando for clicar em finalizar, mas acredito que vou ter que retornar ao modulo anterior do pagseguro para evitar esse tipo de problema, deixar apenas cielo transparente.

**Comment by r-martins** [comment]
Você pode chamar o evento de atualizar meios de pagamento do deivison no checkbox dos outros pagamentos. Assim resolve seja com pagseguro ou cielo.

**Comment by budswarez** [comment]
Instalei o pag seguro 2,7 sem ser transparente funciona só não está na
cielo estava vendo é um js que não carrega quando seleciona cielo
Em 01/07/2016 7:51 PM, "Ricardo Martins" <notifications@github.com>
escreveu:

**Comment by budswarez** [comment]
O problema não é no módulo do boleto, pois o módulo que utilizo para cc CIELO da "oitoo" recarrega perfeitamente o valor removendo a regra.
Já o mesmo erro que ocorre com o pagseguro transparente ocorre com a extension de CC e Débito da CIELO da Query "http://querycommerce.com/modulos-magento/modulo-de-integracao-magento-cielo.html" 
Possivelmente alguma chamada depreciada.

**Comment by r-martins** [comment]
Você pode chamar o evento de atualizar meios de pagamento do deivison no checkbox dos outros pagamentos. Assim resolve seja com pagseguro ou cielo.

**Comment by budswarez** [comment]
Dai já esta fora do meu nivel de conhecimento, mas vlw mesmo, o correto seria mesmo atualizar o valor quando seleciona o meio de pagamento.
Obrigado desde já.

**Comment by r-martins** [comment]
@budswarez 
Eu acho que peguei um problema parecido esses dias.. Depois de uma cacetada de debug, eu cheguei no que parecia ser a solução mais simples pra matar na fonte o problema do checkout do Deivison...
O checkout dele remove uma validação de cartao de credito, usada em meu módulo, que desencadeia uma série de comportamentos bizarros sem exceptions.

**Pra resolver**
1. Procure o arquivo onestepcheckout.xml do deivison, e copie-o pro seu tema (pra evitar sobrescrever).
2. Localize o nó <onestepcheckout_index_index>...<reference name="head"> ... e acrescente o trecho abaixo dentro desse nó...

`<action method="addJs"><script>lib/ccard.js</script></action>`

Limpe os caches e tente denovo.. ;)

**Comment by r-martins** [comment]
Esta issue está sendo re-aberta a fim de re-avaliar as soluções possíveis de acordo com relatos recentes.

**Comment by leuterio** [comment]
Depois de um tempo lendo este tópico e com o auxílio do meu supervisor conseguimos resolver este problema que também estávamos enfrentando.

No arquivo `Cc.php` localizado em `app\code\community\RicardoMartins\PagSeguro\Model\Payment` fizemos uma condição na validação pelo backend. 

`if ( (!$creditCardToken || !$senderHash) && !in_array($pathRequest, $configPaths)) {`

Ou seja, além de verificar se o `token` e o `hash` eram inválidos, também verificamos o path da requisição de validação. Se viesse pelo ` savePaymentMethod` não valida, apenas valida após o `placeOrder`, que é de fato o momento que o usuário finaliza a compra e aí é validado o cartão de crédito.
Adicionamos um textArea no admin para caso haja necessidade de adicionar outra path url nessa exceção é necessário apenas inserir o path lá separando por ponto e vírgula (;).

Segue o link da minha [contribuição](https://github.com/leuterio/PagSeguro-Magento-Transparente/tree/fix_discount_error);

O resultado ficou o seguinte:
![Error fixed](https://thumbs.gfycat.com/BlackKeenAvians-size_restricted.gif)

**Comment by apzeiro** [comment]
Parece que a melhor solução até o momento.
Vou testar!

**Comment by r-martins** [comment]
@leuterio Obrigado pela contribuição e pontualidade na resolução do problema.
Sua solução foi aplicada (com algumas modificações) na versão 3.5.0.
