### ISSUE TITLE
Log no exception > Falha ao processar pagamento

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#171]
Olá, alguém já recebeu esse erro no log exception?

`2016-07-07T18:39:47+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.' in /home/....../public_html/app/Mage.php:595
Stack trace:
#0 /home/....../public_html/app/code/community/RicardoMartins/PagSeguro/Model/Payment/Cc.php(129): Mage::throwException('Falha ao proces...')
#1 /home/....../public_html/app/code/core/Mage/Sales/Model/Quote/Payment.php(160): RicardoMartins_PagSeguro_Model_Payment_Cc->validate()
#2 /home/....../public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(659): Mage_Sales_Model_Quote_Payment->importData(Array)
#3 /home/....../public_html/app/code/community/Inovarti/Onestepcheckout/controllers/AjaxController.php(240): Mage_Checkout_Model_Type_Onepage->savePayment(Array)
#4 /home/....../public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_AjaxController->savePaymentMethodAction()
#5 /home/....../public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('savePaymentMeth...')
#6 /home/....../public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /home/....../public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/....../public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /home/....../public_html/index.php(83): Mage::run('', 'store')
#10 {main}`

Foi a primeira vez que apareceu alguém assim... @r-martins poderia dar uma olhada?

Obrigado

**Comment by r-martins** [comment]
@fchiqueto me ajuda a simular o problema?

**Comment by fchiqueto** [comment]
@r-martins acredito que está falha seja por causa da issue #172
