### ISSUE TITLE
Falha ao finalizar compra via admin

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#173]
Problema havia sido resolvido na v. 2.4.1 mas parece estar de volta.
Após tentar realizar compra no admin com Boleto por exemplo...

> Um erro ocorreu em seu pagamento. sender hash is required. (53150)

Testado na loja exemplo.

**Comment by r-martins** [comment]
Funcionando.

**Comment by robsonschneider** [comment]
Ricardo... estou com este problema. Alguma dica para resolver? O que fiz agora a pouco foi atualizar a versão PRO, pois optei por receber em 2 dias os pagamentos. Atualizei com os arquivos recebido por email em um .ZIP (pagseguro-pro.zip). Descompactando este arquivo .ZIP, a data da pasta é de 19/04/2016 às 19:07.

**Comment by r-martins** [comment]
@robsonschneider manda a solicitação via chamado com o url e email da conta, por gentileza.
A menos que tenha detectado algum bug claro, usamos o github. Combinado?
Grande abraço.

**Comment by robsonschneider** [comment]
Combinado. Desculpa a confusão.
