### ISSUE TITLE
Valor do brinde 0.00

### ISSUE THREAD

**Issue by fernandoybus** [r-martins/PagSeguro-Magento-Transparente#174]
Ola Ricardo,
Criamos uma regra pra brinde. Na compra de um produto, o cliente ganha um segundo produto de graca. E o sistema esta voltando esse erro.
Problemas ao processar seu pagamento. Valor do item fora do permitido: 0.00(53079)

Pode me ajudar?

**Comment by r-martins** [comment]
Bacana @fernandoybus.
Pode anexar um print da promoção só pra facilitar?
Obrigado.

**Comment by r-martins** [comment]
Não consegui simular o problema. Quando puder, reabra o chamado com o print da promoção pra poder simular.
Obrigado.

**Comment by mvsucupira** [comment]
@r-martins isto está acontecendo comigo também.
Estou usando usando a extensão https://github.com/witrin/magento-gifts para incluir os produtos de brinde, e ao realizar pagamento, está dando o erro 53079.

Seguem as telas do checkout e do log do pagseguro.log

![captura de tela 2017-03-09 as 13 10 50](https://cloud.githubusercontent.com/assets/18449669/23758962/18b5ef9e-04ca-11e7-9547-8ed7915ecb48.png)
![captura de tela 2017-03-09 as 13 10 31](https://cloud.githubusercontent.com/assets/18449669/23758963/18b9946e-04ca-11e7-8369-58096c20dfaf.png)
![captura de tela 2017-03-09 as 13 09 44](https://cloud.githubusercontent.com/assets/18449669/23758964/18bda914-04ca-11e7-890a-2ed770f4b1bf.png)

**Comment by fchiqueto** [comment]
Testado e aprovado @r-martins +1:

**Comment by r-martins** [comment]
Show. Valeu pelo feedback.
