### ISSUE TITLE
Maximum key size must be smaller 56

### ISSUE THREAD

**Issue by alexandrelrv99** [r-martins/PagSeguro-Magento-Transparente#175]
Olá, estou com o erro ao tentar salvar as configurações.

Ocorreu um erro ao salvar esta configuração: Maximum key size must be smaller 56
Sim, já li o tópico https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/211273983-Erro-Maximum-key-size-must-be-smaller-56 porém não entendi o qual é a resolução do problema...
Deixei com menos de 56 caracteres, exclui todos os caracteres da linha e nada aconteceu e voltei o bkp do arquivo.
**Qual é a real resolução do problema?**

**Comment by r-martins** [comment]
Olá @alexandrelrv99 
Esse erro é exatamente sobre o tamanho da chave no seu arquivo de config.
Lembre-se de limpar todos os caches depois de alterar o valor da chave.
No caso de duvidas (e nao bugs) peço que abra um chamado e vemos individualmente.
Grande abraço.
