### ISSUE TITLE
Remover Data de Nascimento e CPF?

### ISSUE THREAD

**Issue by panuci** [r-martins/PagSeguro-Magento-Transparente#177]
Posso remover os campos de data de nascimento e CPF no pagamento com cartão de crédito? Se sim qual é a melhor maneira de fazer isto.

**Comment by magnored** [comment]
é obrigatorio pelo pagseguro ... nao é possivel remove-los.
O maximo que vc pode fazer é incluir um checkup informando se o dados do comprador são os mesmos do titular do cartao e fazer que ele copie os dados ja preenchidos pelo cliente

**Comment by r-martins** [comment]
Obrigado por responder, @magnored
