### ISSUE TITLE
Parcela é enviada sem juros

### ISSUE THREAD

**Issue by mlimasolucoes** [r-martins/PagSeguro-Magento-Transparente#181]
Relatei numa issue fechada porém abrindo uma nova por via das dúvidas.
Resumo do print em anexo:
Produto custa: R$4.364,00
Com um cupom de 20% de desconto ele fica custando: R$3.491,20
Nosso dropdown de parcelas informa corretamente o valor com juros, porem como no print mostra, a mensagem de erro informa o valor da parcela sem juros.

![img-20161010-wa0005](https://cloud.githubusercontent.com/assets/8741804/19247940/a9ad6398-8f03-11e6-922a-ef06ce55444a.jpg)

**Comment by r-martins** [comment]
Olá, @mlimasolucoes.
Fiz uma simulação com os mesmos valores e não consegui simular.
Peço que tente simular em uma das lojas de teste, que contém a versão mais recente do módulo sem outros módulos pra influenciar.

![screen shot 2016-10-10 at 10 38 24 pm](https://cloud.githubusercontent.com/assets/191149/19256155/a9e346a2-8f3a-11e6-91d0-d26d5dafafd6.png)

O screencast do teste está disponível em http://recordit.co/1C4cYRBTrr
