### ISSUE TITLE
Erro - Boleto pago não retornou para Loja

### ISSUE THREAD

**Issue by rfbastos** [r-martins/PagSeguro-Magento-Transparente#182]
E ai Ricardo Beleza?

Minha cliente está com seu modulo instalado na versão PRO, autorizado e etc.

Cartão funcionou normalmente até agora. Mas hoje houve um boleto pago (apareceu aprovado no pagseguro) e no site está como "Pagamento Pendente"

Ao analisar o report encontrei isso

a:5:{i:0;s:90**:"Problemas ao processar seu pagamento. invalid transactionCode value:  notifications(13003)"**;i:1;s:1116:"#0 /home/lojadasr/public_html/app/code/community/RicardoMartins/PagSeguro/Model/Abstract.php(29): Mage::throwException('Problemas ao pr...')

Sabe me dizer o que é preciso fazer para solucionar este problema?

**Comment by r-martins** [comment]
Olá @rfbastos,
Dê uma olhada [nesse link](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/209089326-Configurei-o-retorno-autom%C3%A1tico-mas-parece-n%C3%A3o-funcionar-).
Se necessário abre um chamado por lá.
Provavelmente não é um bug e sim erro de configuração. Vamos manter somente os bugs aqui no github, ok?

Valeu! Abraços!
