### ISSUE TITLE
Um erro ocorreu em seu pagamento. sender hash is required. (53150)

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#184]
Olá, estou tendo esse problema com o módulo pro do PagSeguro, acontece da seguinte forma:

Se coloco boleto primeiro ele funciona mas o cartão não (aparece a mensagem "Um erro ocorreu em seu pagamento. sender hash is required. (53150)";
Se coloco cartão primeiro ele funciona mas o boleto não (aparece a mensagem "Um erro ocorreu em seu pagamento. sender hash is required. (53150)";

Poderiam me ajudar por favor.

Certificado SSL já instalado na loja

**Comment by r-martins** [comment]
@richard-nexxus 
Por não se tratar de um bug, peço que abra um chamado na [central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br).
