### ISSUE TITLE
Configurar integração Pagseguro

### ISSUE THREAD

**Issue by rabraga** [r-martins/PagSeguro-Magento-Transparente#185]
Ricardo,

Boa tarde, tudo bem? Primeiro queria parabeniza-lo pelo trabalho realizado!! 

Instalei o modulo FREE e gostei muito. Estou usando a versão 1.9.2.4 do Magento. Tive que customizar os templates incluíndo nas quatro linhas de endereço os campos numero, complemento e bairro. Após isto ao finalizar um pedido os dados passaram para minha conta do pagseguro. Mas como foi teste digitei o codigo de segurança errado. Minha operadora negou o pagamento e recebi um email do pagseguro com esse cancelamento. Porém o status do pedido continuou Pendente na minha loja.

Já fiz integração com o pagseguro e me recordo de configurar os retornos de notificação na minha conta do Pagseguro para receber. No seu modulo também tem isto? Como ficam as configurações de integração na conta do Pagseguro?

Gostaria muito de assinar o pacote PRO para liberar o boleto e TEF. Mas antes queria deixar a integração funcionando sem erros.

Obrigado.
Ramon Loureiro

**Comment by rabraga** [comment]
Ok. faltou configurar https://www.lojaloft.com.br/index.php/pseguro/notification.

Tudo certo!

**Comment by r-martins** [comment]
@rabraga 
Show. Quando tiver dúvidas veja a [central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br) e se precisar abre um chamado por lá.
Por aqui é pra reportar bugs, e demoro mais pra conseguir dar retorno.

Abs
