### ISSUE TITLE
Outros aplicativos na mesma conta

### ISSUE THREAD

**Issue by mlimasolucoes** [r-martins/PagSeguro-Magento-Transparente#186]
Fala meu brother, tudo bem?

Utilizamos seu módulo aqui na Empresa em um Magento, funciona perfeitamente, porém estamos com uma dúvida: Temos um outro produto em Dot Net em que iremos integrar o checkout transparente.

1 - Como seria a questão do token, da url de notificação e demais dados?
2 - Teria como dar uma tag por transação pra sabermos no extrato daonde estará vindo?

Obrigado pelo ótimo módulo, grande abs

**Comment by r-martins** [comment]
Olá @mlimasolucoes,
Peço que entre em contato via chamado para novas questões.
Por aqui é apenas para reportar erros, e demoro mais pra responder.

Grande abraço e obrigado pelo contato. ;)
