### ISSUE TITLE
Erro na Finalização de Compra - "Banco HSBC encontra-se indisponível e foi removido."

### ISSUE THREAD

**Issue by paulo-medparc** [r-martins/PagSeguro-Magento-Transparente#187]
Boa tarde Ricardo!

Estamos utilizando a versão PRO de seu módulo em nosso site de e-commerce. Até alguns dias atrás ele estava funcionando perfeitamente, processava os pedidos em todas as formas de pagamento.

Mas desde ontem não estamos conseguindo concluir as compras no site. Simplesmente o botão para finalizar a compra não funciona mais. Utilizamos o debugger do Chrome e verificamos que o módulo está retornando uma mensagem de erro: "**Banco HSBC encontra-se indisponível e foi removido.**"

Tentamos de várias formas corrigir este problema, removendo a opção do HSBC do controller, verificando incompatibilidade com outros módulos, restaurando versões anteriores de backup de nossa loja, etc. Mas o erro persiste. Abaixo está um _print_ mostrando o erro.

Poderia nos ajudar?
Muito obrigado.

**Paulo de Andrade
_Atendimento TI MedParc_**

![error_magento](https://cloud.githubusercontent.com/assets/20602487/19736985/660760aa-9b90-11e6-9e3b-730c99e5bf7c.png)

**Comment by r-martins** [comment]
Olá @paulo-medparc 
Não se trata de um erro e sim de um recurso do módulo, que consulta junto à API do pagseguro sobre bancos que estão fora do ar neste momento, pra evitar que o cliente fique tentando finalizar compra sem sucesso com um banco que está fora do ar.
Quem diz se o banco está fora ou não é o próprio PagSeguro.

Espero ter ajudado.
Grande abraço.
