### ISSUE TITLE
Cartão inválido no ambiente de produção

### ISSUE THREAD

**Issue by gustavu92** [r-martins/PagSeguro-Magento-Transparente#19]
Primeiramente parabéns pelo módulo!
Estou com um problema estranho, quando estou no ambiente de testes o módulo funciona normalmente, entretanto, quando mudo para o ambiente de produção, ele dá inválido em qualquer cartão que coloco no campo.

**Comment by BernardinoGomes** [comment]
Amigos,Boa noite.
Estou com um problema similar ao relatado por vocês.
Teu Token está habilidado para usar no checkout transparente,porém no ambiente de produção aparece a mensagem de cartão inválido.Isso ocorre com qualquer cartão que eu coloque.

Alguém poderia me dar uma solução  ?
Já re-coloquei o token,limpei a cache,porém sem sucesso

log.
2015-04-29T22:58:53+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulÃ¡rio. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualizaÃ§Ã£o de blocos via ajax nao se preocupe.

**Comment by marcoshuss** [comment]
Olá pessoal, por acaso a URL base da loja de vc´s foi alterada? A instalação do magento foi em um domínio temporário e depois editaram a URL base? Comigo aconteceu isso e dava erro de Cross-Origin no Ajax. Verifiquei no meu banco onde ainda havia registro da minha url antiga e achei na tabela core_confg_data na coluna path a linha web/secure/base_url tinha como valor minha URL antiga. Depois de corrigir isso, funcionou normalmente o módulo.

**Comment by cassolatto** [comment]
estou com o mesmo problema e desesperado
![image](https://cloud.githubusercontent.com/assets/17692639/15276824/4132bf88-1ac9-11e6-95cf-380ca60d6b80.png)

**Comment by gustavu92** [comment]
No meu caso por algum motivo o módulo não estava salvando o token no arquivo. Tente editar o arquivo diretamente:

PAGSEGURO:
app/code/community/RicardoMartins/PagSeguro/Helper/Data.php
Linha 27

PAGSEGURO PRO:
app/code/community/RicardoMartins/PagSeguroPro/Helper/Internal.php
Linha 81

**Comment by cassolatto** [comment]
Olá, muito obrigado !

Só uma dúvida,  o que eu tenho de editar lá ? Eu sou total novo nisso !

Obrigado


*RICARDO CASSOLATTO*

Business Consultant
sintetik@gmail.com / 21 98196-0504

*FastMobile*
http://fastmobile.info
Rua Farani, 23 - apto. 403 - Botafogo - CEP 22231-020 - RJ - BRASIL

<http://www.facebook.com/ricardo.cassolatto>
<https://br.linkedin.com/in/ricardo-cassolato-9ba225>

2016-05-15 19:23 GMT-03:00 Gustavo J. Q. Vasconcelos <
notifications@github.com>:

**Comment by lanapf** [comment]
Fiz a instalação do módulo e o testei, estava funcionando perfeitamente fiz uma compra com o cartão para teste tudo OK!

Após a alteração de meu dominio a opção de cartão de crédito simplesmente não funciona mais, Boleto, TEF tudo OK apenas o cartão quando colocado os dados do cartão de crédito ele não funciona, vc não consegue avançar na compra para finalizar como se algo tivesse faltando porém ele não aparece nenhuma mensagem de erro.

Como posso solucionar isso. Preciso com urgência que meu site volte a funcionar.
