### ISSUE TITLE
Sender Hash is required

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#191]
Boa tarde,

Já abri uma vez esse tópico aqui e já abri um ticket, porém ainda não encontrei a solução.

Utilizo pagseguro pro no site cartão e boleto porém quando deixo boleto como segundo opção no checkout, o sender hash desaparece, o mesmo acontece se deixo cartão como segunda opção.

Gostaria de saber se alguém pode me ajudar com isso.

Agradeço desde já

**Comment by renatoaleksander** [comment]
https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203887479-Problemas-ao-processar-seu-pagamento-sender-hash-is-required-53150-

**Comment by richard-nexxus** [comment]
Obrigado @renatoaleksander, mas já tentei esse procedimento também e não tive sucesso.

**Comment by richard-nexxus** [comment]
Para melhor entendimento, fiz esses prints

![boleto1](https://cloud.githubusercontent.com/assets/17569565/20107060/534eebda-a5be-11e6-9fbe-e17af30e80dd.PNG)
![cartoa1](https://cloud.githubusercontent.com/assets/17569565/20107061/534f9ce2-a5be-11e6-850d-e40c612d35c7.PNG)

Os prints acima estão na ordem de Boleto em primeiro e Cartão em segundo, repare no codigo que o input Sender Hash aparece somente pro boleto e no cartão desaparece

Já nesses prints abaixo é o contrário, Cartão em primeiro e Boleto em segundo, input sender hash apenas no cartão, sumindo do boleto

![boleto2](https://cloud.githubusercontent.com/assets/17569565/20107123/868f3676-a5be-11e6-8290-01a8779676e8.PNG)
![cartao2](https://cloud.githubusercontent.com/assets/17569565/20107124/86955920-a5be-11e6-8c10-8dd0fc7743ed.PNG)

**Comment by richard-nexxus** [comment]
Problema resolvido, removi o <input type="hidden" name="payment[sender_hash]"/> do arquivo directpayment.phtml em app/design/frontend/base/default/template/ricardomartins_pagseguro/form e coloquei para ser carregado antes dos pagamentos.
No meu arquivo de configuração do método de pagamento ficou da seguinte forma:

<dl class="sp-methods" id="checkout-payment-method-load">
	<?php $i=0;?>
	<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
	<?php $i++;?>
	<?php if($i != count($this->getMethods())):?>
		<style type="text/css">
			#advice-validate-one-required-by-name-p_method_<?php echo $_code ?>{
				display: none !important;
			}
		</style>
		<input type="hidden" name="payment[sender_hash]"/>
	<?php endif;?>
		<dt>
		<?php if( sizeof($this->getMethods()) > 1 ): ?>	
				<input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="save_shipping_method(shipping_method_url,0,update_payment_review);" <?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio validate-one-required-by-name" />
		<?php else: ?>
				<span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio validate-one-required-by-name " onclick="save_shipping_method(shipping_method_url,0,update_payment_review);" /></span>
		<?php endif; ?>
				<label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
		</dt>
		
		<?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
		<dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
				<?php echo $html; ?>
		</dd>
		<?php endif; ?>
	<?php endforeach; ?>
	</dl>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
	<div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
	<div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
$$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {
    var element = e.element();
    var name = 'payment_form_' + element.value;
    
    /* Hide all other forms */
    $$('dd.payment-method').invoke('hide');
    
    if(element.checked) {
        var form = $(name);
        var container = $('container_payment_method_' + element.value);

        if(element !== null && container !== null)    {
            container.show();
            $(name).show();
        }
    }    
});
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
	function toggleToolTip(event){
		if($('payment-tool-tip')){
			$('payment-tool-tip').setStyle({
				top: (Event.pointerY(event)-560)+'px'//,
				//left: (Event.pointerX(event)+100)+'px'
			})
			$('payment-tool-tip').toggle();
		}
		Event.stop(event);
	}
	if($('payment-tool-tip-close')){
		Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
	}
	
	initWhatIsCvvListeners();	
//]]>
</script>

**Comment by mvsucupira** [comment]
@richard-nexxus , boa tarde.
Poderia explicar melhor como fez isto? Não sou expert em códigos. Como colocou para ser carregado antes dos pagamentos e para que serve este arquivo (directpayment.phtml) ?

**Comment by richard-nexxus** [comment]
@mvsucupira botarde,

dentro do arquivo directpayment.html tem um campo de input, eu removi ele de lá e coloquei no meu arquivo de checkout responsável por carregar as formas de pagamento, porém coloquei logo abaixo da primeira tag <dl> em meu checkout

**Comment by mvsucupira** [comment]
Você uso o OSC 6 do deividson? Estou procurando também o código do botao de
finalizar o pedido para pode incluir a instrução de rodar a função de
preenchimento do Sender hash, mas parece que é criado dinamicamente e não
consigo alterar.

Não sou um escovador de bits, por isso queria uma instrução simples e
direta.

Obrigado.

Em 18 de nov de 2016 12:29 PM, "richard-nexxus" <notifications@github.com>
escreveu:

**Comment by richard-nexxus** [comment]
@mvsucupira No meu caso eu não utilizo o OSC 6 e sim o onestepcheckout da MageStore, mas eu estava dando uma olhada nos arquivo do seu checkout e no caminho app/design/frontend/base/default/template/onestepcheckout/onestep/form/payment_method.phtml
o arquivo payment_method.phtml é bem parecido com o meu e entre a linha 19 e 20, coloquei o <input type="hidden" name="payment[sender_hash]"/> que estava dentro do arquivo directpayment no caminho
app/design/frontend/base/default/template/ricardomartins_pagseguro/form/directpayment.phtml

**Comment by mvsucupira** [comment]
Valeu, vou verificar.

Abs.

Marcus Vinícius T. Sucupira

2016-11-18 15:06 GMT-02:00 richard-nexxus <notifications@github.com>:

**Comment by cledsonsilva** [comment]
Olá Richard-Nexxus, 

Finalmente consegui resolver esse problema que me fez perder muitas vendas, graças às suas informações. Você tem razão. Fui em app/design/frontend/base/default/template/ricardomartins_pagseguro/form/directpayment.phtml e apaguei a linha <input type="hidden" name="payment[sender_hash]"/>. Depois inseri o código <input type="hidden" name="payment[sender_hash]"/> no arquivo app/design/frontend/base/default/template/ideasa/idecheckoutvm/onepage/review.phtml. Lembrando que eu uso o Checkout Venda Mais do Ipagare. 

É como disse Ricardo Martins, nesses tipos de checkouts que usam ajax às vezes ocorre a perda do hidden sender hash, daí a mensagem de erro. Às vezes o cliente atualizando a página dava certo, às vezes nem a pau.

Antes de inserir o código no arquivo do Checkout Venda Mais, mas depois de ter excluído o código do arquivo directpayment.phtml, fiz uma compra teste e... Sender Hash is Required. Aí depois que inseri o código no review.phtml tudo funcionou perfeitamente.

**Comment by Marusso** [comment]
Olá @cledsonsilva ,

Fico feliz que essa solução tenha te ajudado também.

Obrigado.

**Comment by r-martins** [comment]
@Marusso , @cledsonsilva 
Tem a versão 3.0-beta na área de branches. Se puderem atualizar e me dar um feedback eu agradeço.
PS: usem no ambiente de testes por enqto. 

Abs

**Comment by mvsucupira** [comment]
Pessoal, também fiz os procedimentos e os meus problemas tinham acabado, mas hoje tornou a acontecer, com um pedido pago por boleto, a cliente tentou três vezes e desistiu. 
Ainda não testei a nova versão Beta do Ricardo, mas este erro está me tirando o sono. Alguém mais teve o problema depois dos ajustes? Alguma dica para tentar acompanhar e rastrear as situações que isso acontece?

**Comment by richard-nexxus** [comment]
olá @mvsucupira, a versão 3.0 resolveu meus problemas em relação a isso

**Comment by mvsucupira** [comment]
Vocês já estão usando esta versão em producao?

Em 24 de jan de 2017 8:18 AM, "richard-nexxus" <notifications@github.com>
escreveu:

**Comment by richard-nexxus** [comment]
Corrigindo, o problema de sender_hash voltou a acontecer, tive que voltar a fazer como era antes.
Sim @mvsucupira, já estou usando em produção, pois os testes que eu fiz, passaram

**Comment by r-martins** [comment]
A versão 3.0.1 já está em produção. Por enquanto só no github, pois o
Magento Connect está demorando pra aprovar.



2017-01-24 9:27 GMT-02:00 richard-nexxus <notifications@github.com>:

**Comment by r-martins** [comment]
Corrigido na v. 3.0.1 já em produção no Connect e no github.

**Comment by apzeiro** [comment]
Estou com esse problema na versão 3.0.4 . O que fazer?
