### ISSUE TITLE
Bandeira Visa obrigatório incluir no checkout o país em que a transação é realizada.

### ISSUE THREAD

**Issue by marcuspitu** [r-martins/PagSeguro-Magento-Transparente#195]
Olá, recentemente recebi um email do pagseguro informando que a partir do dia 31/01/17 será obrigatório incluir no checkout o país em que a transação é realizada. Já tenho o módulo instalado e funcionando a um bom tempo e agora pergunto, este módulo já contem esta informação ou é necessário incluir, onde? O módulo que tenho instalado é o 2.1.1 Obrigado.

**Comment by r-martins** [comment]
Olá @marcuspitu 
Já foi incluído na versão 3.0 que ainda está em beta.
Devo lançar em breve, ou postarei uma solução paliativa na central de ajuda.
