### ISSUE TITLE
Sandbox no modelo de aplicação

### ISSUE THREAD

**Issue by mvsucupira** [r-martins/PagSeguro-Magento-Transparente#196]
@r-martins , boa noite.
Estou testando a versão 3.0 para colocar na versão de produção, no entanto ainda não há suporte para sandbox neste modelo.
Como posso testar sem ser com pagamento reais no cartão de crédito e débito?
Há alguma previsão para disponibilizar a sanbox? Abs.

**Comment by r-martins** [comment]
Olá, @mvsucupira 
Pode fazer uma compra de valor baixo (R$1,00) e depois fazer o estorno.
Vamos manter esse canal para bugs apenas. Quando for sobre duvidas, utilize o canal de suporte por gentileza.
