### ISSUE TITLE
Solicitar data de nascimento junto com os dados do cartão

### ISSUE THREAD

**Issue by nestormagento** [r-martins/PagSeguro-Magento-Transparente#197]
Realizei a instalação em 2 lojas diferentes, em ambos realizando a atualização do módulo 2.5.6 para a 3.0.1  (Magento 1.9.3.1) e a opção de solicitar data de nascimento junto com os dados do cartão, não funcionou e o campo não é exibido no checkout OSC6.

**Comment by r-martins** [comment]
Consegue simular na [loja demo osc](http://pagseguro-exemplo-osc.ricardomartins.net.br/)?
Peço que envie via ticket até termos certeza que é um bug, ok?

Obrigado pela atenção.

**Comment by nestormagento** [comment]
Olá Ricardo,
Referente a enviar por ticket: Ok entendido.

Referente a simular:
Posso testar sim, quando puder poderia atualizar a versão da loja demo?

Acredito não ser a mais recente pois não possui a opção de exibir a mensagem de transação realizada no Brasil, certo?

**Comment by r-martins** [comment]
Olá @nestormagento.
Você tem razão. A loja demo está desatualizada. Acabei de realizar a atualização no repositório. Ela deve subir as novas versões nas próximas 6 horas.

Grande abraço.
