### ISSUE TITLE
Problemas com atualização para a versão 3

### ISSUE THREAD

**Issue by mvsucupira** [r-martins/PagSeguro-Magento-Transparente#198]
Pessoal, boa noite.
Possuo a versão PRO no modelo de aplicação + OSC6 e utilizei o modman update para atualizar a extensão do @r-martins , no entanto me deparei com os seguintes problemas:
1) No console do Chrome aparece o erro, quando estou no checkout: 
Uncaught ReferenceError: RMPagSeguro is not defined
    at preparePagSeguro ((index):1074)
    at (index):1078

2) As opções de cartão de crédito ficam duplicados
3) Não abrem as opções para inserir os dados do cartão

Fiquei o dia inteiro para tentar resolver, mas sem sucesso ainda.

Há algum procedimento especial para realizar esta atualização? é necessário excluir os arquivos antigos e/ou limpar a base de dados?

Aguardo uma luz, obrigado.

**Comment by r-martins** [comment]
@mvsucupira parece que você está usando o JS do modulo 2.x.
Na v 3.0 é RMPagSeguroObj o nome da classe.
