### ISSUE TITLE
Erro ao pegar o CPF/CNPJ

### ISSUE THREAD

**Issue by iam-alan-abreu** [r-martins/PagSeguro-Magento-Transparente#20]
Caro Ricardo,

esta ocorrendo um problema ao finalizar o pagamento, conforme segue abaixo.

Problemas ao processar seu pagamento. sender cpf or sender cnpj is required.(53118)

Estou usando a versao 1.8.1 do magento, juntamente com o modulo OSC Versão: PRO V4.0.2 do Deivison. Ja configurei os campos personalizados, ja desativei e ativei o TAX/VAT, mas o problema persiste. Já não sei mais o que tenho que fazer.

O campo CPF/CNPJ está como obrigatório e esta salvando no banco de dados.

**Comment by MayaOliver2** [comment]
O Bairro está dando erro de envio de pagamento, como arrumo isso?

**Comment by MayaOliver2** [comment]
Eu acredito que encontrei a solução ( não sei se é a correta, nem se vai funcionar pra todos) no meu funcionou:
No admin em Sistema > Configuração > Clientes > Configurações > (aba) Opções de nome e endereço.
Coloquei em "Número de Linhas p/ Endereço" 2
 Em base/default/template/persistent/checkout/onepage arquivo  billing.phtml por volta da linha :67
logo abaixo o trecho:

terá esse código:

_<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">_
inseri: 
**<label ><?php echo $this->__('Bairro') ?></label>**

Aqui deu certo, porém como disse não sei se está correto!

**Comment by thiagovilela11** [comment]
53118 - CPF/CNPJ do comprador é obrigatório.
53029 - Campo "bairro" do endereço de entrega é obrigatório.

Poderiam me ajudar

**Comment by apzeiro** [comment]
Surgiu esse erro hoje aqui. Alguém sabe a solução?

**Comment by r-martins** [comment]
Vejam https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/208727606-Como-configuro-os-campos-de-endere%C3%A7o-corretamente-

Caso tenham dúvidas e não encontrem na [central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br/), [abram um chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new). Não tenho como acompanhar todas as threads fechadas aqui no github. ;)
