### ISSUE TITLE
Problemas com mapeamento da data de nascimento

### ISSUE THREAD

**Issue by fredbrunken** [r-martins/PagSeguro-Magento-Transparente#200]
De acordo com a descrição da versão 3.0.4 do módulo pagseguro transparente diz que foi feito uma correção do mapeamento da data de nascimento que não funcionava, eu continuo tendo o problema com o mapeamento errado.

Eu estou usando magento 1.9.3.0 e firecheckout 3.10 na loja e o mapeamento não está funcionando.

Obrigado

**Comment by pratesbh** [comment]
Também observo o mesmo problema:
'creditCardHolderBirthDate' => '01/01/1970',
uso a versão 1.9.3, checkout padrão.
