### ISSUE TITLE
Após Digitar CPF e clicar no botão finalizar pagamento não gera boleto

### ISSUE THREAD

**Issue by celsoaramos** [r-martins/PagSeguro-Magento-Transparente#201]
Pessoal, boa tarde.

Depois que escolho a opção boleto, digito o CPF e clico em Finalizar o boleto não é gerado.. o botão não faz ação nenhuma... somente se clicar de novo.
Ou
se eu digitar o CPF, clicar fora do campo e depois sim clicar no botão Finalizar pagamento.

é como se o CPF necessitasse perder o foco para poder clicar no botao finalizar pagamento

**Comment by r-martins** [comment]
@celsoaramos 
Receio que este seja um problema no seu checkout apenas.
Pode verificar se o problema ocorre nas [lojas de demonstração](http://pagseguro-exemplo.ricardomartins.net.br/) do módulo ou na loja limpa?
Obrigado.
