### ISSUE TITLE
Falha ao processar seu pagamento

### ISSUE THREAD

**Issue by AgenciaDom** [r-martins/PagSeguro-Magento-Transparente#202]
Olá, instalei esse módulo na minha loja no magento. Quando eu clico pra finalizar a compra aparece essa mensagem "Falha ao processar seu pagamento". Por favor me ajudem, não sei como resolver.
Segue o link da loja: http://newnewam.com/loja/
Versão magento. 1.9.3.0
Tema : KARTPARADIGM

**Comment by r-martins** [comment]
Olá, @AgenciaDom.
Verifique os arquivos de log da sua loja e do módulo.
Vamos interagir pelo pagseguro-transparente@ricardomartins.net.br para avançar com essa dúvida, ok?
Deixamos esta área apenas para reportar bugs mesmo.
