### ISSUE TITLE
Versão 3 já pode ser utilizada?

### ISSUE THREAD

**Issue by rmansini** [r-martins/PagSeguro-Magento-Transparente#203]
Olá, gostaria de saber se já pode utilizar em ambiente de produção a versão 3.0 do modulo, pois ainda tem uns arquivos em beta.

obrigado

**Comment by r-martins** [comment]
Já pode sim.
PS: use este espaço para reporte de bugs apenas. Para dúvidas, use a [central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br).
