### ISSUE TITLE
Autorização de aplicação não funciona

### ISSUE THREAD

**Issue by roneclay** [r-martins/PagSeguro-Magento-Transparente#204]
Tentamos por diversas vezes autorizar a aplicação, mas ao clicar em avançar a próxima tela não faz login automático no PagSeguro e se estiver logado ele desloga.

E mesmo forçando o login na tela de autorização, recebemos o erro:

Requisição de autorização inválida, por favor tente uma nova requisição de autorização.

**Comment by r-martins** [comment]
Olá, Roneclay.
Obrigado por reportar. Pode me enviar detalhes do que colocou no form do site para pagseguro-transparente@ricardomartins.net.br ?
Fiz alterações recentes no serviço, e nos meus testes por enquanto estava ok. Talvez você tenha feito algo diferente. Pode me auxiliar a reproduzir o problema?

**Comment by roneclay** [comment]
[image: Imagem inline 2][image: Imagem inline 1]

*Ronne Clay Santos *
Criando sites, lojas, blogs e sistemas inteligentes.
+55 (41) 3732-2868 / Skype: *roneclay*
http://ronneclaysantos.eti.br

Em 10 de março de 2017 18:23, Ricardo Martins <notifications@github.com>
escreveu:
