### ISSUE TITLE
Pulando numeração dos pedidos

### ISSUE THREAD

**Issue by richard-nexxus** [r-martins/PagSeguro-Magento-Transparente#205]
Olá,

Reparei que alguns pedidos em minha lojas estão pulando a numeração e alguns desses pedidos não aparecem no painel de pedidos, por exemplo, a ultima numeração é 100000724, o próximo pedido cai com a numeração de 100000729 em vez de ser 100000725, isso aconteceu depois que fiz a atualização 3.0 referente as especificações dos cartões Visa.

Olhando o log do pagseguro, pude notar que os pedidos do 100000725 até 100000728, existem, porem somente no log, esses pedidos foram tentativas de compra do mesmo cliente com os mesmos itens que provavelmente falharam.

Alguém poderia me dar alguma solução ou resposta do por que isso estar acontecendo após a atualização??

Segue o print para melhor entendimento
![1](https://cloud.githubusercontent.com/assets/17569565/24008869/c9ae3982-0a51-11e7-9f86-2a311e88ebfe.PNG)

Agradeço desde já

**Comment by r-martins** [comment]
Olá @richard-nexxus.
Este comportamento geralmente está ligado à falhas no banco no momento da gravação do pedido.
Habilite os logs do sistema (do Magento) e olhe seu arquivo exception.log em busca de "INSERT", "lock" e "write", que são termos comuns para exceptions na escrita dos pedidos.

Grande abraço e sucesso na resolução.
