### ISSUE TITLE
Falha ao obter o token do cartão

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#207]
Ricardo , boa noite 

Tudo bem ?

Seguinte , eu uso o onestepcheckout do deivison e o seu modulo transparente atualizado para essa última versão. Estou tendo o seguinte problema: 

Quando eu me logo antes de fazer qualquer compra, e dps vou para o checkout escolho cartao de credito, digito qualquer numero de cartao valido, ele apresenta o seguinte erro : falha ao obter token do cartão. 

Mas quando eu não estou logado, faço uma compra e me logo pelo checkout e preencho os dados do cartão dá tudo certo. 

Veja se vc consegue me ajudar nisso?

Obrigado 

Rafael

**Comment by rafatriolo** [comment]
Descobri outra coisa, é que não tem a ver com estar logado ou não, mas se eu estou logado e mudo de endereço 2 vezes, ele pego o token do cartao!

**Comment by joelmartins** [comment]
Estou com o mesmo problema aqui

**Comment by r-martins** [comment]
Olá pessoal,
Tentei simular o problema na [loja demo](http://pagseguro-exemplo-osc.local.com.br), mas não consegui.
Podem simular por lá se quiserem com o login ricardo@taloko.net e senha 123qwe.
O que aconteceu pra mim foi que ele resetou o form do cartão que eu estava preenchendo pq algum outro ajax terminou de carregar, mas estou num 3G sentado na praça.. então não ajuda muito rs.

Se puderem, compartilhem o url da loja ou do ambiente que estão tentando testar.

Abraços!

**Comment by r-martins** [comment]
Como não tivemos mais retorno, estou encerrando a issue.

**Comment by malkahakuk** [comment]
o que é esse erro?

Fatal error: Call to a member function getCcToken() on array in /home/economin/public_html/app/code/local/Gerencianet/Transparent/Model/Card.php on line 46

**Comment by r-martins** [comment]
Olá, @malkahakuk. Não faço ideia. Aparentemente este caminho nem é o meu módulo.

**Comment by malkahakuk** [comment]
Boa tarde
Qual é o motivo que o cartão não esta funcionando?




Em qua, 17 de jul de 2019 às 20:16, Ricardo Martins <
notifications@github.com> escreveu:

**Comment by r-martins** [comment]
@malkahakuk instale o [meu módulo](http://r-martins.github.io/PagSeguro-Magento-Transparente/download.html) que funciona. :)
