### ISSUE TITLE
Teste local do módulo com sandbox

### ISSUE THREAD

**Issue by philliprj** [r-martins/PagSeguro-Magento-Transparente#208]
Não consigo testar localmente. Não recebo o retorno de pago da sandbox.

Vi que devo inserir PHP: header("access-control-allow-origin: https://sandbox.pagseguro.uol.com.br");

Aonde exatemente ? Poderia me ajudar?

Abraço.

**Comment by r-martins** [comment]
Oi @philliprj.
Na verdade você não consegue testar o retorno localmente pois o PagSeguro não conseguirá acessar sua máquina, dentro da rede da sua casa, a menos que você mapeie um url, e configure seu roteador fazendo o mapeamento interno, etc etc.
Minha sugestão aqui é você simular este retorno com cURL ou Postman de forma manual, conforme mostrado [neste link](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/209089326-Configurei-o-retorno-autom%C3%A1tico-mas-parece-n%C3%A3o-funcionar-).

Para ter retorno sobre dúvidas de forma mais rápida, mande para pagseguro-transparente@ricardomartins.net.br.

Este espaço é destinado apenas para reportar bugs preferencialmente.


Grande abraço e sucesso.
