### ISSUE TITLE
Cartões com a bandeira Mais!

### ISSUE THREAD

**Issue by marcosViniciusLisboa** [r-martins/PagSeguro-Magento-Transparente#209]
Boa tarde, 
Estou usando o módulo em um projeto, e esta dando  um erro quando o cliente digita o número de um cartão da bandeira Mais! , o mesmo relata  que o número do cartão está inválido, porém já entrei em contato com o cliente e o número do mesmo está correto. 
Eu verifiquei que dentro do arquivo card.js, não existe alguma definição em relação ao cartão Mais! , porém não obtive sucesso em consertar. E verifiquei com o PagSeguro e realmente o próprio aceita a bandeira. 
Alguma solução?

**Comment by r-martins** [comment]
Oi Marcos, tudo bom?
O que você pode fazer neste caso é remover a validação da bandeira via JS no phtml do cartão.
Desta forma, o usuário só vai saber que digitou cartão inválido depois que der enviar o pedido.
Se o Pagseguro ou você descobrir qual a expressão regular para validar este tipo de cartão, e tiver alguns de teste, posso ver como adiciona-los ao módulo.
Enquanto isso, vou mandando um e-mail para o PagSeguro pra ver se me ajudam a testar isso com você.

Abs

**Comment by r-martins** [comment]
O PagSeguro não me forneceu cartões de teste para solução do problema.
Você teria algum (só o número, sem cvv nem data) ?
A única coisa que eles validam do lado deles é se começa com 628028.

**Comment by marcosViniciusLisboa** [comment]
Boa noite,
Infelizmente não tenho um cartão para te passar, minha solução foi tirando a validação via JS e deixar para o PagSeguro analisar. Obrigado pela atenção!
