### ISSUE TITLE
Falha ao obter o token do cartao ou sender_hash

### ISSUE THREAD

**Issue by giuliannosa** [r-martins/PagSeguro-Magento-Transparente#210]
Olá Ricardo,

Desde as versões anteriores tento utilizar o módulo, sem sucesso, e como recebi um email informando que ele foi reescrito do zero, pensei que este problema do sender_hash havia sido resolvido, mas não no meu caso, estou utilizando o Magento CE 1.7.0.2 com o módulo PRO e acontece em qualquer página de finalização.

Token do cartão: false/ Sender_hash: '26df17487afa6f1db5bad0d43a3c497168c0dbbcc9b2f18f523ed1a5a057d53f'
2017-06-02T15:44:27+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash.
                    Ative o modo debug e observe o console de erros do seu navegador.
                    Se esta for uma atualização via Ajax, ignore esta mensagem até a finalização do pedido.

**Comment by r-martins** [comment]
Olá, @giuliannosa.
Qual URL da loja onde os módulos estão instalados?
Se possível, me envie para pagseguro-transparente@ricardomartins.net.br.

Abs

**Comment by giuliannosa** [comment]
Olá Ricardo,

Agradeço a resposta, a URL é lojasaline.com

Abraços,

Juliano Sá

2017-06-02 20:59 GMT-03:00 Ricardo Martins <notifications@github.com>:

**Comment by r-martins** [comment]
Olá, Juliano.
Receio que não tenha mais o módulo instalado.
Se tiver outro url, não deixe de entrar em contato no pagseguro-transparente@ricardomartins.net.br
