### ISSUE TITLE
Retorno do Pagseguro Pedido não encontrado 

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#211]
@r-martins  bom dia , tudo bem ?

Atualizei o modulo para última versão aqui do github. Porém tive um problema, ao processar um pagamento com cartão de crédito, na hora de retornar para atualizar o status de pagamento na loja, vi no log a seguinte mensagem: Pedido xxxxx não encontrado no sistema. Impossível processar retorno. Só que o número do pedido está lá. 

Pode me ajudar com isso?

Obrigado

**Comment by r-martins** [comment]
Oi @rafatriolo.
O tratamento do retorno do Pagseguro começa em \RicardoMartins_PagSeguro_NotificationController e depois é processado no \RicardoMartins_PagSeguro_Model_Abstract::proccessNotificatonResult.

Basicamente funciona assim:

1. O Pagseguro envia um notificationCode pra pseguro/notification
2. O modulo busca um XML com mais informações sobre essa notificação.
3. No segundo método acima, o módulo carrega o pedido que consta nesse XML.
4. Se não for possível carregar o pedido (ou seja, se $order->getId() for false, ele gera esta exception que comentou por volta da linha 46 do app/code/community/RicardoMartins/PagSeguro/Model/Abstract.php, que é onde está o segundo método que comentei.

Eu no seu lugar tentaria ver qual foi o notificationCode e qual o número do pedido que está nesse XML. Por fim, tentaria fazer um load desse pedido manualmente, pra ver se tem alguma outra coisa no seu sistema fazendo esse load retornar false.

Espero ter ajudado um pouco. ;)
