### ISSUE TITLE
Um erro ocorreu em seu pagamento. Hash de comprador inválido. (53091)

### ISSUE THREAD

**Issue by brunaashby** [r-martins/PagSeguro-Magento-Transparente#212]
Olá, testei a opção cartão de crédito em ambiente de testes e deu tudo certo, então habilitei a versão pro e ativei o boleto, mas quando tento finalizar o pedido aparece o erro "Um erro ocorreu em seu pagamento. Hash de comprador inválido. (53091)" coloquei na ordem Cartão de Crédito 1 e Boleto 2; minha versão do magento é a 1.9.3.3;

Notei também que no ambiente de testes o "processamento" do pedido demora bastante, é normal?

**Comment by r-martins** [comment]
Oi @brunaashby 
Pode encaminhar essa issue com o url da sua loja para o e-mail de suporte? 
pagseguro-transparente@ricardomartins.net.br

Obrigado.
