### ISSUE TITLE
Customizar Botão de Imprimir Boleto e Realizar Pagamento (TEF)

### ISSUE THREAD

**Issue by aquere** [r-martins/PagSeguro-Magento-Transparente#213]
Olá,

em qual arquivo eu posso customizar os botões de **Imprimir Boleto** e **Realizar Pagamento** no final da compra?

Li algo parecido no #124 porém não encontro o destino que o @r-martins indicou

> Basta copiar o arquivo app/design/frontend/base/default/template/ricardomartins_pagseguropro/payment/info.phtml para app/design/frontend/seuPackage/seuTema/template/ricardomartins_pagseguropro/payment/info.phtml e alterar a gosto

**Comment by r-martins** [comment]
Olá, @aquere.
De fato o botão de pagamento de boleto e tef está localizado em app/design/frontend/base/default/template/ricardomartins_pagseguropro/payment/info.phtml.
Mais detalhes em https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/115003228183.

PS: Se tiver dúvidas pode usar o e-mail de suporte pagseguro-transparente@ricardomartins.net.br.

Este espaço é mais destinado à resolução de bugs.
