### ISSUE TITLE
Forma de pagamento em Criar pedido no admin não aparece.

### ISSUE THREAD

**Issue by williannagano** [r-martins/PagSeguro-Magento-Transparente#214]
Em VENDAS> PEDIDOS> CRIAR PEDIDOS, ao selecionar o cliente e inserir os produtos do pedido, quando vou em FORMAS DE PAGAMENTO, a opção CARTÃO DE CRÉDITO VIA PAGSEGURO não aparece. Em um antiga instalação existia esta opção que ao escolher "cartão de credito via pagseguro" ele gerava um email pro cliente que continha um link (pagar). Está opção não existe mais neste módulo?

**Comment by r-martins** [comment]
Oi Willian.
Por questões de segurança, pedidos via cartão são bloqueados via admin mesmo.
Se desejar, use o [LoginAsCustomer](https://github.com/ajzele/Inchoo_LoginAsCustomer) para fazer pedidos em nome de um cliente.

Espero ter ajudado.
Grande abraço e sucesso nas vendas.
