### ISSUE TITLE
Fatura duplicada - confirmada

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#215]
Reportado por Wagner.. (suporte 1740)

Magento gera fatura duplicada quando o PagSeguro envia notificação duplicada com `<status>3</status>`.

Config:
```
{
    "RicardoMartins_PagSeguro": {
        "version": "3.2.0",
        "debug": true,
        "sandbox": false
    },
    "configJs": {
        "active_methods": {
            "cc": 0,
            "boleto": 1,
            "tef": 0
        },
        "flag": "42x20",
        "debug": true,
        "PagSeguroSessionId": "5feb1b0d4d41441caedebecbc7efc28e",
        "is_admin": false,
        "show_total": false,
        "force_installments_selection": false
    },
    "RicardoMartins_PagSeguroPro": {
        "version": "3.0.0",
        "key_type": "app",
        "key_validation": "a:2:{s:4:\"auth\";b:1;s:10:\"xmlRetorno\";s:0:\"\";}"
    },
    "compilation": {
        "status": "Disabled",
        "state": "Not Compiled",
        "files_count": 0,
        "scopes_count": 0
    },
    "token_consistency": "Good",
    "session_id": "5b233817cf8340cab9240e5666787265",
    "pagseguro_modules": [
        "RicardoMartins_PagSeguro",
        "RicardoMartins_PagSeguroPro"
    ]
}
```

**Comment by r-martins** [comment]
Ainda não foi possível reproduzir o problema nos testes realizados em sandbox.
Novos testes serão feitos em outro ambiente.

**Comment by rafatriolo** [comment]
@r-martins tudo bem ? Estou tendo o mesmo problema.

**Comment by rafatriolo** [comment]
Normalmente esse problema ocorre qdo o pagamento é feito via cartão de credito.

**Comment by r-martins** [comment]
Detectei o problema hoje em uma transação do Magenteiro.
O PagSeguro enviou a mesma notificação 5x, sendo 3x em menos de 15 segundos. No entanto no painel diz que só fez 2 tentativas.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/191149/31306732-5826fbfc-ab99-11e7-8a7c-fae8f5536208.png">

Isso gerou 5 faturas.
Tentarei arrumar um jeito de melhorar isso e tratar no módulo.
Pelo menos agora é possível replicar.

**Comment by rafatriolo** [comment]
Então eu reparei que esse problema acontece com o pagamento via boleto tbm.

**Comment by r-martins** [comment]
Sim. Aconteceu com boleto e cartão pra mim tbm.
Vou cuidar disso.

**Comment by r-martins** [comment]
Agora se o PagSeguro enviar 2 notificações (notificationCode) iguais em menos de 60 segundos, será barrado no controller. 
O que ocorria é que o Pagseguro enviava 2 ou mais requisições no mesmo segundo, e a transação anterior ainda nem tinha sido salva no banco quando a segunda invoice começava a ser processada.
