### ISSUE TITLE
Exibir parcelamento na página de produto

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#216]
Exibir opções de parcelamento na página de produto de acordo com os juros e promoções configurados no painel do PagSeguro.

**Comment by laerciossa** [comment]
Olá Ricardo,
Já está disponível?

**Comment by r-martins** [comment]
@laerciossa ainda não

**Comment by deniscsz** [comment]
@r-martins Essa funcionalidade está sendo levada adiante?
Caso negativo, me disponho a implementá-la.

**Comment by r-martins** [comment]
@deniscsz oi Denis. Ainda estou apanhando da agenda Magenteiro + PagSeguro + Cursos M2..
Ficarei feliz se puder ajudar.
Imagino que isso possa ser um helper + block, de forma a permitir que o usuário insira onde quiser.
Mas se puder ajudar, fique à vontade para fazer um Pull Request.
Até ficarei feliz em retribuir a contribuição... ;)

**Comment by deniscsz** [comment]
@r-martins Tranquilo, vou me organizar aqui e implementar durante o mês de março.

**Comment by feeh27** [comment]
@deniscsz Você implementou essa funcionalidade?

**Comment by ggcampos** [comment]
Olá pessoal, alguma novidade sobre essa funcionalidade?

**Comment by r-martins** [comment]
Disponível a partir da versão 3.7.6.
Saiba mais em http://bit.ly/2IYaGxY.
