### ISSUE TITLE
PagSeguro com problemas

### ISSUE THREAD

**Issue by phdiegues** [r-martins/PagSeguro-Magento-Transparente#217]
Boa tarde Pessoal. 
Minhas duas lojas estão com problemas no pagamento via pagseguro, por acaso é uma instabilidade no sistema deles?

Ambas apresentam a mesma mensagem de erro:
Não foi possível obter o SessionId do PagSeguro. Verifique seu token, chave e configurações.

Obrigado a todos!

**Comment by r-martins** [comment]
Olá @phdiegues 
Não. Desta vez foi uma manutenção emergencial de hardware nos meus servidores mesmo.
A instabilidade durou cerca de 1h e meia. Mantenho o acompanhamento dos servidores minuto a minuto com o Monitis, e não é algo normal de acontecer.
Já solicitei a mudança do serviço para outro servidor, a fim de ter mais estabilidade. O que deve ocorrer nas próximas horas.

Lamento o transtorno, mas estou em cima com isso.
Também estou estudando formas de hospedar o serviço no Brasil, mas das 2 empresas que testei até o momento (Host1Plus e Uol Cloud (por ser da mesma empresa)), não superaram o SLA do provedor atual.

Lamento o transtorno, mas estou em cima desse assunto.

**Comment by phdiegues** [comment]
Oi Ricardo, obrigado pelo retorno. Tudo bem, só perguntei mesmo pra saber se o problema era aqui comigo só pois foi logo apos eu fazer uma atualização, coincidentemente. Obrigado pelos esclarecimentos!
Abração.

**Comment by jemarall** [comment]
Ricardo,
Acredito que seja o mesmo assunto. 
Desde sexta estamos tendo problemas com o módulo PRO.

Na console do navegador aparece: 
Não foi possível obter o SessionId do PagSeguro. Verifique seu token, chave e configurações.

No pagseguro.log:
Falha de comunicação com API do PagSeguro: Could not resolve host: ws.ricardomartins.net.br

**Comment by r-martins** [comment]
Olá, senhores.
Mera (ruim) coincidência, mas os 4 servidores de DNS que uso na kinghost há 7 anos estão enfrentando dificuldades conforme mencionei no #219 .

Estou neste momento configurando um 5º servidor de DNS na AWS (Route 53) para contornar o problema de forma mais rápida.
A equipe da kinghost já está ciente e trabalhando no problema também, conforme podem verificar em http://status.kinghost.net.br.

Lamento pelo ocorrido, e espero normalizar o quanto antes ainda nesta madrugada.

**Comment by r-martins** [comment]
Update: dns primário alterado e apontando para DNS da amazon.
Deve replicar nas próximas horas, e sigo fazendo testes em ferramentas de DNS.
