### ISSUE TITLE
Desconto para pagamento no boleto

### ISSUE THREAD

**Issue by paolinelli** [r-martins/PagSeguro-Magento-Transparente#218]
Seu modulo de boleto não permite dar um desconto nesta forma de pagamento. Isso é muito prejudicial.

**Comment by paolinelli** [comment]
Paguei a versão mensal, não tem essa função lá, no modulo light box do pagseguro tem essa função, voce poderia atualizar o seu dando uma olhada no deles.

**Comment by r-martins** [comment]
Olá @paolinelli, tudo bom?
Desconto por forma de pagamento não é algo que depende do módulo de pagamento em si.
Isso é um recurso do próprio Magento. Você pode criar uma promoção de carrinho para Boleto, por exemplo, e ainda especificar valor mínimo, categoria de produtos, entre milhares de outras coisas.

Grande abraço e sucesso nas vendas.
