### ISSUE TITLE
Erro ao enviar parâmetros PagSeguro

### ISSUE THREAD

**Issue by marcosViniciusLisboa** [r-martins/PagSeguro-Magento-Transparente#219]
Os clientes não estão conseguindo finalizar uma compra no meu projeto, antes funcionava corretamente, e nos últimos dias começou a dar a seguinte mensagem "Falha ao tentar enviar parametros ao PagSeguro: Couldn't resolve host 'ws.ricardomartins.net.br' " ao clicar no botão "Finalizar Pedido", e o projeto não teve nenhuma alteração que possa ter causado o problema
![capturar](https://user-images.githubusercontent.com/25207214/28540687-9d3243c0-708c-11e7-8e35-6c3ff8dbd52e.JPG)
. Eu mesmo fiz um teste usando as duas formas de pagamento,boleto e cartão, e ambos os meios voltaram o mesmo erro. Segue em anexo o print da mensagem. Espero um retorno, obrigado.

**Comment by r-martins** [comment]
Olá @marcosViniciusLisboa.
Verifiquei com a equipe de infra responsável pelo DNS e parece haver um problema que já foi identificado e está sendo tratado.
Há quase 3 anos rodo os serviços nos mesmo provedores sem nenhum problema (e monitoro eles a cada minuto usando o monitis), mas parece que nos últimos 3 dias eles combinaram...
![screen shot 2017-07-25 at 09 47 04](https://user-images.githubusercontent.com/191149/28549610-8c70498c-711e-11e7-8c7d-b976a590bc10.png)

Já estou realizando testes na Amazon para trazer todos os serviços pra lá, inclusive de DNS.

Se preferir, altere **temporariamente** o arquivo app/code/community/RicardoMartins/PagSeguro/etc/config.xml e mude o 
`<ws_url_app>https://ws.ricardomartins.net.br/pspro/v6/wspagseguro/v2/</ws_url_app>`
para
 `<ws_url_app>https://69.160.57.2/pspro/v6/wspagseguro/v2/</ws_url_app>`


Lamento o transtorno.

**Comment by r-martins** [comment]
Update: problema contornado com a migração parcial dos DNS para AWS.
Obrigado pela compreensão de todos.

**Comment by fchiqueto** [comment]
Como fica o config.xml agora? eu fiz a alteração para <ws_url_app>https://69.160.57.2/pspro/v6/wspagseguro/v2/</ws_url_app>

Volto ao que estava antes?

**Comment by r-martins** [comment]
@fchiqueto a alteração era só uma medida temporária. Pode voltar como era antes...
`<ws_url_app>https://ws.ricardomartins.net.br/pspro/v6/wspagseguro/v2/</ws_url_app>`

**Comment by tiagoexe** [comment]
olá Ricardo, esse esse mesmo problema ontem e hoje!
a solução acima ainda é valida?

**Comment by r-martins** [comment]
Oi @tiagoexe.
Não é não. O que acontece?
Me mande seu problema [aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
