### ISSUE TITLE
Error 53079 -Brinde

### ISSUE THREAD

**Issue by edixavier** [r-martins/PagSeguro-Magento-Transparente#220]
Ola Ricardo @r-martins.

Por gentileza, Criamos uma regra pra brinde. Na compra de um produto, o cliente ganha um produto de graca. E o sistema esta voltando esse erro.
Problemas ao processar seu pagamento. Valor do item fora do permitido: 0.00(53079)

Pode me ajudar?
![error pag](https://user-images.githubusercontent.com/30468449/28622665-b2a4a314-71eb-11e7-9c8a-caec42dd5529.jpg)

**Comment by r-martins** [comment]
É duplicado do #174.
Foi tratado no release [3.2.1](https://github.com/r-martins/PagSeguro-Magento-Transparente/releases/tag/3.2.1).
