### ISSUE TITLE
Adequação Bacen

### ISSUE THREAD

**Issue by fchiqueto** [r-martins/PagSeguro-Magento-Transparente#223]
Olá recebi um e-mail do PagSeguro hoje, segue abaixo:

Em razão das regras do Bacen, no que se refere a centralização junto a CIP (Câmara Interbancária de Pagamentos) dos registros, compensação e liquidação do fluxo financeiro entre os participantes do Sistema de Pagamentos, o PagSeguro está realizando os ajustes necessários para ficar em conformidade com as novas exigências.

Sendo assim, informarmos que caso queira continuar oferecendo os meios de pagamento Débito Online e Boleto bancário, será necessário realizar um ajuste na sua integração, passando a enviar dois campos adicionais na integração que possui conosco:

Nome completo do comprador ou razão social da empresa;
CPF ou CNPJ;

Lembre-se, esse ajuste é opcional e só deverá ser realizado caso queira seguir oferecendo os meios de pagamento em sua loja virtual.

O módulo já está em conformidade?

Obrigado!

**Comment by r-martins** [comment]
Olá, @fchiqueto.
Sim, o módulo já está em conformidade. Nada precisará ser feito.
Obrigado por perguntar.
