### ISSUE TITLE
Informe os dados do cartão para calcular

### ISSUE THREAD

**Issue by Mamaousa** [r-martins/PagSeguro-Magento-Transparente#224]
Instalei os novas versões dos módulos, mas na hora do checkout, mesmo preenchendo todos os dados do cartão, fica escrito na campo parcelas a seguinte mensagem: Informe os dados do cartão para calcular. A compra não prossegue a partir disso. o que fazer? Será algo a ver com o meu one step checkout?

**Comment by Mamaousa** [comment]
Desabilitei o meu one step checkout e mesmo assim deu o mesmo erro.

**Comment by r-martins** [comment]
Olá, @Mamaousa.
Acredito que seu caso seja mais uma dúvida do que um bug.
Poderia encaminhar sua solicitação para pagseguro-transparente@ricardomartins.net.br informando o URL da loja?

Seguirei com você por lá.
Grande abraço.
