### ISSUE TITLE
CEP - auto preenchimento de dados de cobrança

### ISSUE THREAD

**Issue by laerciossa** [r-martins/PagSeguro-Magento-Transparente#225]
Pessoal,

Boa tarde. Instalei e configurei  este módulo em minha loja, mas percebi que ao informar o CEP durante o cadastro de clientes, a aplicação não consegue preencher os campos de endereço, bairro, etc. A aplicação fica indicando que estaria consultando o CEP, mas não termina. 
Alguém já passou por algo semelhante?
Eu estou usando essa extensão para integração com os correios:

https://www.magentocommerce.com/magento-connect/calculo-de-frete-dos-correios.html

Obrigado desde já pela ajuda

**Comment by r-martins** [comment]
Olá, @laerciossa.
Obrigado pelo contato e feedback.
Infelizmente o papel do módulo de Pagamento é cuidar do que diz respeito ao pagamento, sem se envolver em outras questões.
Veja outros módulos que possam fazer isso pra você. Provavelmente uma customização no tema em conjunto com algum módulo deva ser suficiente.
