### ISSUE TITLE
Erro 53080

### ISSUE THREAD

**Issue by rfbastos** [r-martins/PagSeguro-Magento-Transparente#227]
Um erro ocorreu em seu pagamento.
Receiver is blocked (53080)

Veja a imagem
https://ibb.co/bZusdw

**Comment by r-martins** [comment]
Oi @rfbastos 
Parece que a conta pagseguro configurada (receiver) está bloqueada.
Se quiser, me envie os detalhes da conta para pagseguro-transparente@ricardomartins.net.br e eu tentarei ver o que houve com o pessoal do PS.
