### ISSUE TITLE
Problema no módulo: Hash de comprador inválido. (53091)

### ISSUE THREAD

**Issue by luizosorio85** [r-martins/PagSeguro-Magento-Transparente#228]
Prezados, 

instalei o módulo de vocês, mas recebi um e-mail de um erro agora quando um comprador fez a compra, e não fiz nenhuma mudança no modulo e não houve nenhuma mudança no servidor. Muito estranho é que apavorado fiz uma compra teste simulando um novo cadastro e deu tudo certo, o que pode ter ocorrido, é algum erro do módulo? Estou desesperado pois estou perdendo vendas e com certeza esses clientes não voltarão mais.

Já fiz o teste pseguro/ajax/getSessionId e está retornando ID normalmente.

Aguardo seu retorno urgente.

Grato
Luiz Osorio

**Comment by luizosorio85** [comment]
E pra ajudar, outro erro também está ocorrendo: Sender hash is required (53150). Estou pensando em tirar esse módulo, vou acabar perdendo muitas vendas

**Comment by rfbastos** [comment]
Também comecei a receber o erro do sender hash (53150) depois de atualizar pra ultima versao.

**Comment by r-martins** [comment]
Apenas atualizando todos aqui, existe um bug já conhecido pela equipe do PagSeguro a este respeito.
A última informação que tenho é que o problema já foi corrigido e está em fase de testes com eles.
Hoje mandei um e-mail pedindo posicionamento.

De qualquer forma, no passado em alguns checkouts desenvolvidos fora do padrão do Magento, o módulo poderia ser responsável por parte do problema. Por isso é importante manter ambos os módulos (principal e PRO) atualizados.

**Comment by r-martins** [comment]
O erro 53150 (Sender hash is required) ainda está sendo tratado pela equipe do PagSeguro. Hoje tentei colocar mais pessoas de lá a par da situação a fim de obter algum retorno.
Para o outro erro (sender hash invalid emitido em alguns checkouts), há uma solução disponibilizada na versão 3.5 explicado [aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/115003006172-Workaround-para-requisi%C3%A7%C3%B5es-Ajax).

**Comment by r-martins** [comment]
Parece que o PagSeguro não vai resolver isso tão cedo...
Acabei por lançar mais um workaround para o problema na versão [3.5.2](https://github.com/r-martins/PagSeguro-Magento-Transparente/releases/tag/3.5.2).
