### ISSUE TITLE
Erro nas Notificações - 403

### ISSUE THREAD

**Issue by rfbastos** [r-martins/PagSeguro-Magento-Transparente#229]
Bom dia Ricardo,

Tenho um cliente que não tem recebido as notificações e com isso os status nao estão sendo alterados.

No pagseguro o codigo do status http é **403**

Assim como informado por você na issue #139 , fiz o que você sugeriu.

Acessei a URL de notificação que me gerou um erro no /var/reports

**a:5:{i:0;s:90:"Problemas ao processar seu pagamento. invalid transactionCode value:  notifications(13003)";i:1;s:1116:"#0** /home/xxxxxxx/public_html/app/code/community/RicardoMartins/PagSeguro/Model/Abstract.php(29): Mage::throwException('Problemas ao pr...')
#1 /home/xxxxxxx/public_html/app/code/community/RicardoMartins/PagSeguro/controllers/NotificationController.php(36): RicardoMartins_PagSeguro_Model_Abstract->proccessNotificatonResult(Object(SimpleXMLElement))
#2 /home/xxxxxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): RicardoMartins_PagSeguro_NotificationController->indexAction()
#3 /home/xxxxxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#4 /home/xxxxxxx/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/xxxxxxx/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/xxxxxxx/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/xxxxxxx/public_html/index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:22:"/pseguro/notification/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

Isso ocorre tanto com ou sem "index.php/" inserido na url

**Comment by r-martins** [comment]
Olá @rfbastos 
Esta URL sempre irá gerar erro se você não enviar o notificationCode pra ela via POST.
Veja [este artigo](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/209089326-Configurei-o-retorno-autom%C3%A1tico-mas-parece-n%C3%A3o-funcionar-) sobre como funcionam as notificações e como testar.

Se tiver dúvidas, entre em contato no pagseguro-transparente@ricardomartins.net.br.
Vamos tentar deixar o github apenas para erros mesmo, ok?

Abs.
