### ISSUE TITLE
Drop de parcelas exibe apenas 1 quando limitador está configurado

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#232]
Reportado por Mauro Filho (e já comentado por outros usuários)

> Por padrão veio "Usar as configurações definidas na conta PagSeguro". Ao alterar para 10X e simular uma compra, só é exibida a opção no checkout de 1X.

**Comment by DanielLCintra** [comment]
#234 Abri uma issue pra falar sobre isso.. Achei a solução

**Comment by r-martins** [comment]
Resolvido na versão 3.5.0 lançada hoje.
Obrigado Mauro e @DanielLCintra.

**Comment by mzfshark** [comment]
Muito obrigado Ricardo / Daniel.
