### ISSUE TITLE
Limitador de Parcelas Não está funcionando.

### ISSUE THREAD

**Issue by DanielLCintra** [r-martins/PagSeguro-Magento-Transparente#234]
Na linha 316 do arquivo RicardoMartins/Pagseguro/Helper/Data.php está assim:

'installment_limit' =>
            (int)Mage::**_getStoreConfigFlag_**(self::XML_PATH_PAYMENT_PAGSEGURO_CC_INSTALLMENT_LIMIT)

E o correto é assim

'installment_limit' =>
                (int)Mage::**_getStoreConfig_**(self::XML_PATH_PAYMENT_PAGSEGURO_CC_INSTALLMENT_LIMIT)

Como estava com getStoreConfigFlag ao invés de getStoreConfig, ele sempre retornava 1 fazendo com que a configuração de limite de parcelas não funcione. Com a alteração o valor da configuração passa a ser retornado e o limitador de parcelas passa a funcionar.

**Comment by r-martins** [comment]
@DanielLCintra Perfeito! Muito obrigado pela solução. Me poupou trabalho. 👍 
Resolvido na versão 3.5.0.
