### ISSUE TITLE
Pagamento recorrente

### ISSUE THREAD

**Issue by mlimasolucoes** [r-martins/PagSeguro-Magento-Transparente#235]
Olá Ricardo, existe alguma previsão ou customização pro modulo contemplar  pagamentos recorrentes?

**Comment by r-martins** [comment]
Olá @mlimasolucoes 
Infelizmente não. Este é um assunto complexo e extremamente difícil de ser testado.
Embora esteja na minha lista, não devo priorizá-lo enquanto eu ainda tiver um trabalho paralelo e não estiver 100% dedicado aos meus projetos. Hoje ainda trabalho 3 dias por semana para uma empresa, e os outros 2 dias fico com meus projetos pessoais (Magenteiro, Cursos, e PagSeguro).
Espero conseguir priorizar isso um dia, ou encontrar alguém que queira me ajudar neste desenvolvimento.
