### ISSUE TITLE
Alguns erros aparecendo no console.

### ISSUE THREAD

**Issue by diego-goulart** [r-martins/PagSeguro-Magento-Transparente#236]
Instalei os módulos e aparentemente estão funcionando. Mas está aparecendo alguns erros no console:

`VM5379:1 Uncaught SyntaxError: Unexpected token _ in JSON at position 0
    at JSON.parse (<anonymous>)
    at callbacks.(anonymous function) (https://stc.pagseguro.uol.com.br/pagseguro/j/pagescripts/checkout/direct-payment/pagseguro.mediator.directpayment.1512152761382.js:1:11315)`

Além disso, o layout das opções de pagamento ficou um pouco quebrado:
![image](https://user-images.githubusercontent.com/17575204/34016222-3e53f672-e108-11e7-8b90-b72d10a88c20.png)

**Comment by r-martins** [comment]
Oi @diego-goulart 
A resposta da própria equipe do PagSeguro é que estes erros não afetam o checkout ou a finalização de pedidos, portanto é 'ok'.
Infelizmente (ou felizmente) não está relacionado com o módulo e não há nada que eu possa fazer do meu lado.
