### ISSUE TITLE
O retorno da Forma de Pagamento não está disponível.

### ISSUE THREAD

**Issue by lemooca** [r-martins/PagSeguro-Magento-Transparente#237]
Ao tentar realizar o checkout na loja 1.8.2, não avança e retorna este erro em index.php/onestepcheckout/index/updateordermethod

Testei com o modo de pagamento boleto e o meio de recebimento boleto está habilitado no pagseguro, a url de retorno está devidamente configurada também, conforme instrução http://urldaloja.com/index.php/pseguro/notification

**Comment by r-martins** [comment]
Olá @lemooca.
Acho que esqueceu de mencionar qual erro está tendo.
Este canal é ideal para reportar bugs mesmo, se puder, envie os detalhes do problema e url [neste link](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
Obrigado
