### ISSUE TITLE
Problema ao aplicar cupom

### ISSUE THREAD

**Issue by FrancisGregori** [r-martins/PagSeguro-Magento-Transparente#238]
Quando um cupom é aplicado o valor fica positivo, mas ao tentar finalizar a compra é informado que o valor da compra é negativa.

Estou utilizando o modulo 3.5.3
Magento versão. 1.9.3.3
Modulo de checkout: OneStepCheckout

**Comment by r-martins** [comment]
Oi @FrancisGregori , tudo bom?
Estranho isso acontecer. Você consegue reproduzir o bug na [loja de teste com OneStepCheckout](http://pagseguro-exemplo-osc.ricardomartins.net.br/)?

**Comment by FrancisGregori** [comment]
Olá @r-martins, tudo certo sim, e por ai?

Consegui replicar o erro na loja teste.
Segue o passo a passo abaixo.

Criei um cupom 'teste-frete' que da um desconto no mesmo valor do frete, no caso aqui R$ 5,00.
Selecionei um produto de R$ 1,00, coloquei o frete de R$ 5,00, e apliquei o cupom de desconto, deixando o carrinho no valor de R$ 1,00, feito isso tentei finalizar usando a opção de boleto do pagseguro e recebi o erro de valor negativo.

Segue o print
![ricardo-martins](https://user-images.githubusercontent.com/3008656/35097972-96c291d2-fc39-11e7-9634-51f4abcbc58e.png)


Obrigado pela atenção!

**Comment by r-martins** [comment]
Oi @FrancisGregori. Obrigado pelo report e exemplos.
Consegui simular o "problema" aqui.
No entanto, se o objetivo é dar frete grátis através de cupom, basta selecionar a opção de frete grátis na criação da promoção.

Deu trabalho! Mais de 3 horas brincando nisso.
Mais demorado ainda é testar todos os cenários..
Bom, correção feita e publicada na v. 3.5.4. 🥇 

Obrigado por reportar.

**Comment by FrancisGregori** [comment]
@r-martins, muito obrigado pela atenção e também pelo módulo!
Abraço.
