### ISSUE TITLE
finalizando pedido depois de preencher cpf

### ISSUE THREAD

**Issue by Luiz-Bernardes** [r-martins/PagSeguro-Magento-Transparente#239]
Olá, poderia me dar uma ajuda?

estou usando o módulo do pagseguro, funciona perfeitamente o pagamento. só estou com um problema depois que a pessoa preenche o cpf ela clica direto em finalizar, sem clicar fora da caixa de texto do cpf,  ela acaba tendo que clicar 2 vezes em finalizar, uma pra carregar o cpf e a outra pra depois finalizar. alguma coisa pode ser feita, para contornar isso? Obrigado

**Comment by r-martins** [comment]
Olá @Luiz-Bernardes.
Isso parece ser um comportamento do seu módulo de checkout, e não do módulo de pagamento.
Se desejar, me enviar um e-mail como chamado ( pagseguro-transparente@ricardomartins.net.br ) e eu lhe indico alguém para lhe ajudar com o checkout.
Se este não for o caso, me envie um email mesmo assim com detalhes da loja que eu dou uma olhada.

Grande abraço.
