### ISSUE TITLE
Erro javascript durante o checkout

### ISSUE THREAD

**Issue by Josano** [r-martins/PagSeguro-Magento-Transparente#240]
Bom dia,

Habilitamos o metódo do pagseguro transparente para um cliente e no cartão de crédito estou recebendo o seguinte erro durante a finalização de pagamento dos cliente:

Uncaught SyntaxError: Unexpected token _ in JSON at position 0
    at JSON.parse (<anonymous>)
    at callbacks.(anonymous function) (https://stc.pagseguro.uol.com.br/pagseguro/j/pagescripts/checkout/direct-payment/pagseguro.mediator.directpayment.1518027343071.js:1:11315)

Esse erro ocorre mesmo se o cliente estiver logado.
Alguma dica de como solucionar?

**Comment by r-martins** [comment]
Olá, @Josano.
Os erros de JS com origem nos dominios do pagseguro não são do escopo do módulo corrigi-los.
A resposta oficial que tenho do PagSeguro é que estes erros **não** interferem no fechamento do pedido e podem ser ignorados (infelizmente).
Caso suspeite que algum deles esteja interferindo no correto funcionamento do módulo, fique à vontade para abrir um chamado pra mim na [Central de Ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br/).

Grande abraço e sucesso nas vendas.
