### ISSUE TITLE
Pagamento por TEF

### ISSUE THREAD

**Issue by renatoaleksander** [r-martins/PagSeguro-Magento-Transparente#241]
Ao habilitar pagamento por TEF a não finalização do pagamento acaba mesmo assim por decrementar a quantidade de produto no estoque. Alguma sugestão

**Comment by deniscsz** [comment]
Renato, acredito que você pode criar uma cron na qual cancela os pedido com
pagamento via tef em algumas horas após a criação do mesmo.
Dessa forma seu estoque não ficaria "preso".

**Comment by renatoaleksander** [comment]
Ok. Foi verificado isso e realmente após rodar o cron o pedido foi cancelado e retornado o produto ao estoque.

Pagamento TEF funciona normalmente.

Obrigado !!
