### ISSUE TITLE
Problemas com o PagSeguro?

### ISSUE THREAD

**Issue by phdiegues** [r-martins/PagSeguro-Magento-Transparente#242]
Bom dia gente. Há uns dias por alguns momentos tenho recebido o seguinte erro na minha página de checkout:

i-ck.html:83 GET https://df.uol.com.br/safe-checkout/js/datafortressConnSecure.v1.js net::ERR_CERT_AUTHORITY_INVALID
pagseguro.js:235 Falha ao obter bandeira do cartão.

o PagSeguro está realmente instável ou esse erro é isolado?

Muito obrigado

**Comment by williannagano** [comment]
Desde ontem que eu percebi isso. Hoje, desde manhã cedo ta assim. Da certificado invalido, aí depois vc tenta acessar de novo e ta funcionando, espera mais uns minutos e da certificado invalido de novo.

**Comment by r-martins** [comment]
A resposta oficial do PagSeguro é que estão cientes do problema e investigando..

> Olá Ricardo, tudo bem?
> 
> Me chamo Felipe e também faço parte da equipe de Suporte Dev do PagSeguro.
> 
> 
> Estamos recebendo mais casos como esse. Verificarei com a equipe responsável e assim que obtiver resposta, entrarei em contato através deste email com as informações obtidas. Peço que aguarde as informações e obrigado por nos relatar!
> 
> Atenciosamente,
> 
> Felipe Soares Olimpio | Suporte Dev


Assim que receber alguma resposta, atualizo esta issue.

**Comment by r-martins** [comment]
O update já estava aqui e eu não vi...

> Olá Ricardo, tudo bom?
> 
> Conforme informações da equipe responsável, ocorreu uma atualização do certificado no domínio df.uol.com.br que pode ter gerado instabilidade e possíveis problemas. Porém no dia 09/03 no período da noite foi feito o rollback dessa atualização. 
> 
> 
> Poderia verificar se o problema persiste hoje e nos avisar?

Alguém ainda enfrenta o problema?
@williannagano @phdiegues

**Comment by phdiegues** [comment]
Fala Willian e Ricardo, obrigado pelas manifestações. Aqui também aparentemente está normalizado também.
Obrigado mais uma vez.

**Comment by r-martins** [comment]
Obrigado pelo feedback pessoal.
Estou fechando essa issue.
