### ISSUE TITLE
Compatibilidade com Magento 2.2.3

### ISSUE THREAD

**Issue by kauansoft** [r-martins/PagSeguro-Magento-Transparente#243]
Olá, Ricardo, prazer em te ver por aqui também. Gostaria de saber quando será disponibilizado uma versão do pagseguro compatível com o Magento 2.2.3. Estou quase mudando de empresa, rs.

**Comment by kauansoft** [comment]
Repositório errado...

**Comment by r-martins** [comment]
Oi @kauansoft.
Já está em fase de desenvolvimento. Estou inclusive com mais gente desenvolvendo junto pra tentar acabar o quanto antes. ;)
