### ISSUE TITLE
Erro 53009 - notificationURL invalid value

### ISSUE THREAD

**Issue by RobsonBastos** [r-martins/PagSeguro-Magento-Transparente#244]
Estou tendo dificuldades com este módulo, instalei o magento do zero, cadastrei 1 produto e instalei o módulo do pagseguro, porém ao clicar em "Place Ordem", depois de cadastrar todas as informações para a compra, aparece a seguinte mensagem:

"Problemas ao processar seu pagamento. notificationURL invalid value: http://127.0.0.1/nomedaloja/pseguro/notification/(53009)" - Imagem em anexo:
![mensagem 53009 - navegador](https://user-images.githubusercontent.com/37664679/37789238-234f8b26-2de2-11e8-8d6b-f67fbeaf1ed9.png)

No site do pagseguro aparece com log 400 - Imagem em anexo:
![mensagem 400 - pagseguro](https://user-images.githubusercontent.com/37664679/37789237-23227a0a-2de2-11e8-8feb-47043d1c60fe.png)

No log do magento aparece Retorno do PagSeguro com o mesmo erro - imagem em anexo:
![mensagem retorno pagseguro - log do sistema](https://user-images.githubusercontent.com/37664679/37789239-23805a1c-2de2-11e8-997a-944d0710f722.png)

Estou em uma instalação local definições:
Magento: 1.9.3.7
PHP Version: 7.1.11
Apache:2.4.29 (Win32) OpenSSL/1.0.2l
MySql: mysqlnd 5.0.12-dev - 20150407

Alterações no PHP.INI:
memory_limit=2048M
max_execution_time=300
extension=php_soap.dll
extension=php_openssl.dll
extension=php_intl.dll
extension=php_xsl.dll
bcmath.scale=2

Estou usando o ambiente de testes(SandBox).
Preciso de ajuda com este problema.

**Comment by r-martins** [comment]
Olá @RobsonBastos 
Conforme conversamos, foi respondido por e-mail via chamado e também na [central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360002051851).

Grande abraço e sucesso nas vendas.
PS: para dúvidas, utilize apenas a [Central de ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br/).
