### ISSUE TITLE
Um erro ocorreu em seu pagamento. Invalid receiver: verify receiver's account status and if it is a sellers's accound. (53085)

### ISSUE THREAD

**Issue by denisgustavo1** [r-martins/PagSeguro-Magento-Transparente#245]
Olá, boa tarde!

Configurei o módulo em uma loja, porém ao realizar a compra via cartão ou boleto é exibido o seguinte erro:

"Um erro ocorreu em seu pagamento. Invalid receiver: verify receiver's account status and if it is a sellers's accound. (53085)"

Verifiquei na página do Pague Seguro pelo código do erro, onde informava que a conta precisa ser verificada e do tipo "Vendedor" ou "Empresarial". A conta que eu utilizei na configuração é verificada do tipo "Empresarial".

Print da mensagem de erro: https://uploaddeimagens.com.br/imagens/mensagem_de_erro-png

Print da conta Pague Seguro: https://uploaddeimagens.com.br/imagens/tipo_de_conta-png

Poderia me dizer como resolver?

**Comment by r-martins** [comment]
Olá, @denisgustavo1.
Muito provavelmente o e-mail da conta pagseguro usado nas configurações do modulo não é o mesmo da conta exibido no print.
Se o problema persistir, [abra um chamado pra mim](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

Vamos manter este canal para reportar bugs no modulo apenas.
Grande abraço.

**Comment by denisgustavo1** [comment]
Olá, boa tarde!

Consegui resolver. A cliente havia alterado os dados do cadastro sem me
comunicar, quando tirei os prints não reparei na alteração.

Obrigado!

Att,

Em 5 de abril de 2018 04:42, Ricardo Martins <notifications@github.com>
escreveu:
