### ISSUE TITLE
Sobre valor da parcela invalida, devido a aplicação de desconto em um método anteriormente 

### ISSUE THREAD

**Issue by hackin88** [r-martins/PagSeguro-Magento-Transparente#248]
Bom dia

-

Sobre valor da parcela invalida, devido a aplicação de desconto em um método anteriormente selecionado

-

Gostaria de compartilhar a seguinte ocorrencia 

A reprodução consiste no seguinte passo

-

1.

1.1

Criar uma promoção que aplica desconto a algum método de pagamento, pode ser no método "Cash On Delivery"

1.2

No checkout nativo, prosseguir e selecionar o método que tenha o desconto

Ao retornar selecione o método da PagSeguro

Veja que o valor da parcela está errada, sendo usado como base o valor com desconto relativo ao método anterior

1.3

Atualize a pagina

1.4

Em seguida selecione o método da PagSeguro

1.5

Veja que o valor da parcela está errada, sendo usado como base o valor com desconto relativo ao método anterior

-

**Comment by r-martins** [comment]
Olá @hackin88.
Obrigado por reportar. Acabo de verificar a existência do problema.
Para referência futura minha ou de quem for resolver, o [screencast do teste pode ser visto aqui](http://www.screencast.com/t/zlJ3KiuCH).

**Comment by r-martins** [comment]
Corrigido na versão 3.7.3
