### ISSUE TITLE
Reembolso total/parcial do pedido

### ISSUE THREAD

**Issue by renorram** [r-martins/PagSeguro-Magento-Transparente#250]
Tenho a seguinte situação, um cliente comprou por boleto 5 itens porém tem a intenção de devolver um dos itens e queria o estorno desse item. Porém percebi que no magento não posso estornar compras por boleto do pagseguro e também que compras por cartão de crédito só podem ser estornadas totalmente e não parcialmente.

Pelo que entendo do módulo e do magento a lógica seria apenas mudar as flags
`$_canRefund` e `$_canRefundInvoicePartial` para `true` dentro do Model dos meios de pagamento correspondentes, já que o método [`RicardoMartins_PagSeguro_Model_Abstract::refund`](https://github.com/r-martins/PagSeguro-Magento-Transparente/blob/42d37cc881a95560e4bf2f7cc259b96ecc743ddd/app/code/community/RicardoMartins/PagSeguro/Model/Abstract.php#L385) envia o valor que está sendo reembolsado.

Queria saber se é seguro alterar essas flags para utilizar o reembolso parcial/total ou se elas tem outra implicação dentro do módulo que pode acabar gerando comportamento indesejado?

**Comment by r-martins** [comment]
Oi @renorram 
Aparentemente o módulo já está preparado para lidar com reembolso parcial e realmente só faltaria alterar esta flag.
Farei alguns testes e atualizarei este ticket em breve.

Obrigado por reportar e lamento a demora.

**Comment by r-martins** [comment]
Oi @renorram 
Realmente, alterando o `$_canRefundInvoicePartial` é suficiente para habilitar o reembolso parcial.
Veja prints do teste que acabei de fazer com cartão de crédito:

![Novo_Reembolso_para__400000001___Reembolsos___Vendas___Administração_Magento](https://user-images.githubusercontent.com/191149/59728299-df367980-927c-11e9-87cb-75132bb9d7cc.png)

<img width="611" alt="pagseguro-exemplo___private_var_www_pagseguro-exemplo__-_pagseguro_exemplo_localhost__console_" src="https://user-images.githubusercontent.com/191149/59728352-08570a00-927d-11e9-8452-89228a186ba2.png">

![PagSeguro_UOL_-_Detalhes_da_transação](https://user-images.githubusercontent.com/191149/59728330-f83f2a80-927c-11e9-878c-f5ae7bc4d89e.png)

Vou liberar esse ajuste na próxima versão e fecho o ticket em seguida...
Obrigado pela contribuição.
