### ISSUE TITLE
Compatibilidade com IWD Checkout Suite [M1]

### ISSUE THREAD

**Issue by guztavoalves** [r-martins/PagSeguro-Magento-Transparente#251]
Olá,
recentemente instalei o Checkout Suite da IWD Agency (https://www.iwdagency.com/extensions/checkout-suite-m1.html) e de todos os módulos de pagamento e frete, o único que apresentou problemas foi este do PagSeguro.

**Recebo o seguinte na própria página de checkout**
URL: https://www.site.com.br/onepage/

Uncaught TypeError: Cannot read property 'active_methods' of undefined
at klass.removeUnavailableBanks (pagseguro.js:20)
at (index):13

(index):13 Uncaught TypeError: Cannot read property 'debug' of undefined
at (index):13

Estou usando Magento 1.9.3.4 e IWD Checkout Suite 6.0.10 (Free).

Alguém já teve esse mesmo problema ou sabe o que poderia ser?

Obrigado =)

**Comment by r-martins** [comment]
Olá, @guztavoalves.
Sei que o tópico é um "pouquinho" antigo, mas só hoje consegui parar pra instalar o IWD e analisar o problema.
O módulo de pagamento é compatível com os principais checkouts OSC do mercado, e temos até algumas demos do [OSC do Deivison](http://pagseguro-exemplo-osc.ricardomartins.net.br/) e do [Firecheckout](http://pagseguro-exemplo-firecheckout.ricardomartins.net.br/).

O que ocorre é que o IWD reescreve os blocos de pagamento removendo div's importantes para o correto funcionamento do módulo. Aparentemente eles implementaram um "universal_wrapper" para os principais meios de pagamento, mas não para o PagSeguro. Por isso funciona com check/money, paypal, braintree, mas não com pagseguro.

Ainda debugarei mais este caso, mas por enquanto tudo indica ser um problema do IWD mesmo e não do módulo PagSeguro.

Por favor me avise se você teve algum outro desfecho para esta issue.

**Comment by LuizSantos1** [comment]
> 

@guztavoalves 
Oi, tudo bem? Você ainda tem o Checkout Suite 1.1.2 da IWD? Eles desativaram e eu não salvei no meu e-mail

**Comment by r-martins** [comment]
Você encontra no github...
https://github.com/search?q=iwd+checkout ...
https://github.com/kirchbergerknorr/iwd_opc

**Comment by r-martins** [comment]
Seria legal se você colocasse no github de repente.. pergunta se eles deixariam.. pode ser útil pra outros.
Obrigado pelo update anyway.

**Comment by LuizSantos22** [comment]
@r-martins  
Sim, só que estou viajando no momento. 
Por praticidade, vou anexar aqui o arquivo tanto do IWD Checkout Suite 1.1.6 quando do Moip Checkout 2.0.3 

O Checkout Suite 1.1.6 já tem aqui no Github: 
https://github.com/italotech/iwd_m1_checkout_suite_free, 
Mas se por ventura não estiver com todos os  arquivos corretos, estou anexando abaixo.

O outro que anexarei, é o Moip Checkout 2.0.3 e explico o motivo
Ele permite que o cliente chegue a página de checkout sem necessidade de pré-cadastro, o que infelizmente não é possível na versão mais atual do módulo. Tive uma conta no Google Merchant suspensa devido a essa exisgência de pré-cadastro, eles disseram que não aceitam, mostrei vários grandes players que atuam da mesma forma, mas mantiveram a suspensão e ignoraram minhas argumentações (tipo, vc não é todo mundo rsrsrs...). 

PROBLEMAS 
Ambos não estão rodando "liso" 
O IWD Checkout Suite, tem um "wrapper" que só torna compatível os meios de pagamento parceiros deles, incluindo Paypal, Braintree, etc... Então um plugin de pagamento com form "transparent", teria que sofrer adaptações com esses "wrappers" pra funcionar. 

O Moip Checkout 2.0.3 em PHP5.6 funciona quase à perfeição, mas deu problema as "parcelas" com o módulo da Vindi/Yapay para cartão de crédito. No entanto, acho que isso tem mais a ver com o módulo de checkout. Pois ambos os módulos (Moip Checkout e Vindi/Yapay) não são compatíveis com PHP7.3 ou PHP7.4 (o que em teoria os torna incompatíveis com OpenMage), no entanto, o módulo da Vindi/Yapay, dá pra "tapear", instalando e depois fazendo um upgrande de Magento 1.9 para OpenMage 1.9 e atualizar para PHP7.4, ele segue funcionando. 
Já o módulo da Moip Checkout 2.0.3, para de funcionar a página de checkout no frontend. O bacend funciona normalmente. 
O que me leva a crer que seja um problema do módulo de checkout, é que a versão mais atual do Moip Checkout, funciona com o módulo de pagamento da Vindi/Yapay sem problema.

Segue em anexo
Arquivos IWD necessários: 
[checkout-suite-m1 (2).zip](https://github.com/r-martins/PagSeguro-Magento-Transparente/files/10223958/checkout-suite-m1.2.zip)
[iwd_all-master.zip](https://github.com/r-martins/PagSeguro-Magento-Transparente/files/10223959/iwd_all-master.zip)


Arquivo Moip Checkout 2.0.3 

[o2ti_moip-2.0.3-modelo-antigo.zip](https://github.com/r-martins/PagSeguro-Magento-Transparente/files/10223956/o2ti_moip-2.0.3-modelo-antigo.zip)

**Comment by r-martins** [comment]
Valeu @LuizSantos22 .
Acrescento que o wrapper que menciona foi tratado em nosso módulo PagSeguro há um tempão.
Embora eu não tenha dado continuidade à loja demo com iwd, lembro de ter preparado o módulo pra ser compatível com ele.

**Comment by r-martins** [comment]
Só pra reforçar...
Desde Abril/2020 que é compatível com IWD
https://github.com/r-martins/PagSeguro-Magento-Transparente/releases/tag/3.8.2

**Comment by LuizSantos22** [comment]
> Só pra reforçar... **Desde a [versão 3.8.2](https://github.com/r-martins/PagSeguro-Magento-Transparente/releases/tag/3.8.2) (Abr/2020), nosso módulo passou a ser compatível com IWD.**

@r-martins 
Com o IWD antigo, sim, ele é compatível. Só que estamos falando do IWD Checkout Suite 1.1.6, este novo checkout, que foi reestilizado, o CSS e layout foi todo mudado... Nenhum módulo não parceiro deles que usa o form "checkout transparent" é compatível. Você inclusive informou que eles usam "dois templates" ou "duas camadas" para tornar os métodos compatíveis com a extensão e não o inverso. Isso suponho que tenha sido feito de propósito para que só os parceiros deles funcionem com o módulo que é "gratis", mas na verdade, quem banca o custo de desenvolvimento seguramente são esses parceiros. 

Só pra esclarecer essa confusão, as versões IWD3.x - 4.x são compatíveis, as IWD Checkout Suite, à partir da 1.1.3 eles colocaram essas restrições. Segue o link da issue que abri à época, foi em 2021: 
https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/298 

Att
Luiz Santos
