### ISSUE TITLE
Página de sucesso e boleto

### ISSUE THREAD

**Issue by rodrigo286** [r-martins/PagSeguro-Magento-Transparente#252]
Olá amigos, instalei esse módulo depois do meu antigo módulo da ideasa não funcionar o retorno automático, esse funciona porem não achei a opção para gerar boletos, só pagamento por cartão de crédito e a página de sucesso não mostra mais o sucesso no pedido e o ID do pedido, tem alguma coisa extra que tenho que fazer para voltar a página de sucesso completa? 

Obrigado desde já.

**Comment by r-martins** [comment]
Oi @rodrigo286 . Tudo bom?
Dê uma olhada no [site do módulo](http://r-martins.github.io/PagSeguro-Magento-Transparente/) e baixe o módulo adicional para ter boleto e tef.
Sobre o ID do pedido na página de sucesso é algo padrão do Magento. Não tem a ver com o módulo de pagamento.

Se tiver alguma dúvida sobre o funcionamento do módulo, peço que [abra uma solicitação por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
O github é apenas para reportar bugs mesmo.

Grande abraço e sucesso nas vendsas.
