### ISSUE TITLE
Valor total do pedido não contempla o valor do Juros.

### ISSUE THREAD

**Issue by WidecommerceDev** [r-martins/PagSeguro-Magento-Transparente#253]
Olá,

Verificamos que o módulo não está calculando juros no valor total do pedido. Na página de checkout e nas informações do pedido no painel administrativo, as parcelas contemplam o valor de juros embutido. Porém no valor total ele não é exibido.

De acordo com algumas verificações em módulos de pagamento, constatamos que os mesmos utilizam os Extra fee para somar o valor adicional. O módulo do Pagseguro realiza essa soma de uma outra maneira ?

Os prints anexos mostram as parcelas e o valor total de um pedido exemplo.
![total](https://user-images.githubusercontent.com/43620573/47999302-4b4adf80-e0e9-11e8-822a-1f0d5a6e96ac.png)
![parcelas](https://user-images.githubusercontent.com/43620573/47999303-4b4adf80-e0e9-11e8-82a3-bd880e1ff14e.png)

**Comment by r-martins** [comment]
Oi @WidecommerceDev . 
Qual extra vc se refere?

**Comment by WidecommerceDev** [comment]
@r-martins na verdade o calculo de juros fica apenas no parcelamento. Ele não é somado ao valor total do pedido. 

Não sei se conseguimos te passar essa ideia.

**Comment by r-martins** [comment]
Acho q passaram sim.
Testo e respondo aqui assim q voltar das férias. ;)

**Comment by r-martins** [comment]
Oi, @WidecommerceDev 
Eu dei uma olhada no que disse, e realmente. O módulo não vai tratar o valor extra adicionado pelo PagSeguro referente aos juros.
Você disse ter visto em outros módulos usarem o Extra. Você tem algum exemplo de módulo que faça isso?

O que vi foi [esse artigo](https://magento.stackexchange.com/a/141213/555), mas envolveria a criação de um novo Totals, novas colunas em tabela de quote e outras coisas que achei muito intrusivas para um meio de pagemento. Também não encontrei nada parecido no módulo do Paypal nativo por exemplo nem no Mage_Payment_Model_Method_Abstract.

Pode dar uma luz?

**Comment by deniscsz** [comment]
@r-martins A abordagem do artigo funciona. Eu já usei o módulo da excellence blog para um projeto b2b, onde eu adicionava um novo Total chamado imposto. Você pode checar o módulo exemplo aqui: `https://github.com/manishiitg/excellence_magento_blog/tree/master/Fee%20Module/app`

**Comment by r-martins** [comment]
@deniscsz não é muito intrusivo para um meio de pagamento não?

**Comment by deniscsz** [comment]
@r-martins Acho sim, eu não curto a ideia também não. Mas eu entendo que isso pode gerar um problema de "fechamento de caixa" digamos assim (não sei usar o termo correto).

**Comment by r-martins** [comment]
Boa @deniscsz!
Acho mais razoável mesmo. Até porque se criar uma coluna nova não vai ajudar muito, exceto para fins de visualização.
Vou ver e conforme for adiciono nas informações do pedido no admin via additionalInformation.

**Comment by r-martins** [comment]
Oi @deniscsz .
Cara, desculpe a demora para lhe dar este retorno.
Hoje estava cuidando deste caso, e fazendo algumas melhorias nas informações exibidas no bloco de informações no admin.
Eu vi que as informações de parcelamento já são salvas no additional_information dentro da sales_flat_order_payment.
Sendo assim, se você fizer $order->getPayment() terá acesso ao additional_information com informações das parcelas e tudo mais.
Elas já são exibidas no admin desde a versão 1.algumaCoisa.
<img width="494" alt="_400000031___Pedidos___Vendas___Administração_Magento" src="https://user-images.githubusercontent.com/191149/69120168-f360fa00-0aec-11ea-8192-f10bff8b1761.png">

Com isso imagino que fique mais fácil.
Espero ter ajudado.
