### ISSUE TITLE
Pedidos Não Entraram no Magento

### ISSUE THREAD

**Issue by lucasfpiovesan12** [r-martins/PagSeguro-Magento-Transparente#255]
Olá, possuo um cliente onde já não é a primeira vez que o fato ocorre.

Acontece que o pedido é registrado no PagSeguro, porém no Magento o pedido não gravou. Não ficou nenhum resquício dele em nenhuma tabela do banco de dados. Não há exceptions, logs e nem nada.

Conseguiriam me ajudar, como por exemplo possuem algum log? Pois caso sim, e caso exista algum erro, poderiam nos auxiliar por favor?

Estou tentando reproduzir o problema, mas não consigo, meus pedidos todos entram e são processados corretamente. O torna difícil fazer um diagnostico.

Parece que há um time out entre as requisições, o que faz com que o Magento trave no checkout e não processe a compra.

Porém como disse, não consegui diagnosticar o problema.

**Comment by r-martins** [comment]
Olá, @lucasfpiovesan12 . Tudo bom?
Este tipo de situação ocorre quando algo dá errado em uma fase onde não é possível reverter a situação do pedido. 
**Geralmente** isso está relacionado a uma instabilidade no banco de dados, ou alguma exception não tratada em um dos módulos da loja.
Nestes casos, o pagamento é processado/enviado para o Pagseguro, mas o Magento não consegue gravar o pedido no banco e faz um rollback da transação.
Você pode habilitar os logs do Magento e também do php a fim de verificar onde está a inconsistência.
Veja também se a hospedagem que está usando é de qualidade e suporta lojas Magento.

Como não creio que este seja um bug do módulo, e não há informações suficientes, estou encerrando esta issue.

Se precisar de ajuda, peço que [abra uma solicitação](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
