### ISSUE TITLE
'Tamanho do cartão inválido.'

### ISSUE THREAD

**Issue by LBCorr** [r-martins/PagSeguro-Magento-Transparente#256]
Pessoal, fazendo os testes da última atualização, percebi que ao copiar e colar números de cartões de testes com quantidade de números diferentes (dinner, american, visa por exemplo), recebo a mensagem: 'Tamanho do cartão inválido.'. A bandeira é encontrada e ao alterar o cvv a mensagem some, ou seja, creio que está ok, apesar da mensagem.

Quando faço o mesmo teste substituindo um visa por um master, por exemplo (mesma quantidade de números) o problema não ocorre.

Além encontrou o mesmo problema?

os números utilizados foram:

MasterCard | 5555666677778884 | 123
Visa | 4012001037141112 | 123
Americacan Express | 376449047333005 | 1234
Dinners Club | 36490102462661 | 123

**Comment by LBCorr** [comment]
Aparentemente o problema está na alteração do 'keyup' para 'change' no js:

Element.observe(ccNumElm,'keyup',function(e){obj.updateCreditCardToken();});
para:
 Element.observe(ccNumElm,'change',function(e){obj.updateCreditCardToken();});

Retornei o keyup e o erro foi resolvido, teria alguma problema?

**Comment by LBCorr** [comment]
Pessoal, apenas atualizando, o erro persiste mesmo modificando o keyup, vou verificar mais profundamente e caso encontre alguma solução informo aqui.

Lembro que não utilizo o checkout padrão do magento então o erro pode não estar no código do módulo mas no do meu opc.

**Comment by r-martins** [comment]
Olá @LBCorr .
Você poderia [abrir um chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br) informando o url da loja para que possa realizar novos testes?
Obrigado.
