### ISSUE TITLE
Módulo V 3.7.7 (Falha ao processar seu pagamento)

### ISSUE THREAD

**Issue by mpgmateus** [r-martins/PagSeguro-Magento-Transparente#258]
Boa tarde, pessoal!

Então, fiz a instalação do módulo e na hora do checkout, preencho todos os dados do cartão. Tudo certinho. Assim que vou finalizar a compra aparece a seguinte mensagem de erro:

Falha ao processar seu pagamento. Por favor, entre em contato com nossa equipe.

O que pode ser isso?

Imagem do erro:
https://ibb.co/5hwgZF6

Se quiserem ver, o link da loja que estou criando:

https://www.ifitfitsonline.com

Valeu! Aguardo por vocês

**Comment by Moisa** [comment]
Olá boa noite! estou com o mesmo problema,  algueme pode ajudar?

Mage_Core_Exception: Falha ao processar seu pagamento. Por favor, entre em contato com nossa equipe. in /home/xdelta/public_html/app/Mage.php:595
Stack trace:
#0 /home/xdelta/public_html/app/code/community/RicardoMartins/PagSeguro/Model/Payment/Cc.php(162): Mage::throwException('Falha ao proces...')
#1 /home/xdelta/public_html/app/code/core/Mage/Sales/Model/Quote/Payment.php(160): RicardoMartins_PagSeguro_Model_Payment_Cc->validate()
#2 /home/xdelta/public_html/app/code/community/Inovarti/Onestepcheckout/controllers/AjaxController.php(392): Mage_Sales_Model_Quote_Payment->importData(Object(Varien_Object))
#3 /home/xdelta/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_AjaxController->placeOrderAction()
#4 /home/xdelta/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('placeOrder')
#5 /home/xdelta/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /home/xdelta/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /home/xdelta/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#8 /home/xdelta/public_html/index.php(111): Mage::run('', 'store')
#9 {main}

**Comment by r-martins** [comment]
@mpgmateus e @Moisa vocês chegaram a ver o arquivo var/log/pagseguro.log?
Por favor, enviem os logs numa solicitação [por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new) por favor.
