### ISSUE TITLE
pgseguro/notification

### ISSUE THREAD

**Issue by lucasferreiraestevam** [r-martins/PagSeguro-Magento-Transparente#261]
Notificação de status do Pagseguro retornando erro  ( Falha ao processar retorno XML do PagSeguro. )

2019-06-26T13:34:35+00:00 DEBUG (7): Retorno do Pagseguro para notificationCode 
2019-06-26T13:34:35+00:00 DEBUG (7): Retorno de notificacao XML PagSeguro em formato não esperado. Retorno: Unauthorized

Como Proceder ?

**Comment by r-martins** [comment]
Oi @lucasferreiraestevam 
Veja https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/211711386-Retorno-PagSeguro-transactions-Unauthorized-

**Comment by lucasferreiraestevam** [comment]
Obrigado Ricardo, vou verificar.

Att.




Em qua, 26 de jun de 2019 às 20:02, Ricardo Martins <
notifications@github.com> escreveu:
