### ISSUE TITLE
Compra de produto Virtual

### ISSUE THREAD

**Issue by GabrielSampaio** [r-martins/PagSeguro-Magento-Transparente#263]
Ao tentar fazer uma compra com um produto virtual da erro de não conseguir achar um endereço de entrega para finalizar a compra.

https://i.imgur.com/nFiz8x9.jpg

Uso o checkout onepage do magento

**Comment by r-martins** [comment]
Estranho.. Eu usava ele no Magenteiro pra vender produtos virtuais.
Vou investigar, @GabrielSampaio Gabriel

**Comment by r-martins** [comment]
Oi, @GabrielSampaio.
Fiz o teste e não consegui reproduzir o problema. 
Veja o vídeo abaixo e me diga se fiz algo diferente de você.
https://www.youtube.com/watch?v=_lQsLov11Wk

**Comment by GabrielSampaio** [comment]
@r-martins Desculpe a demora para responder, na verdade o erro foi por causa do template que alterou os campos de endereço.

Desculpe o transtorno
