### ISSUE TITLE
Alguns pedidos não finalizam

### ISSUE THREAD

**Issue by gabrielhaase** [r-martins/PagSeguro-Magento-Transparente#265]
Estamos enfrentando alguns problemas em apenas alguns pagamentos, tanto para cartões de crédito quanto para boletos e o que é mais estranho é que não são todos.

Seguem alguns erros que estamos recebendo:

Razão
Um erro ocorreu em seu pagamento. Valor da parcela inválido: 20.64 (53041)
TIpo de Checkout
onepage

Razão
Um erro ocorreu em seu pagamento. sender hash is required. (53150)
Tipo de Checkout
onepage

Razão
Falha ao processar seu pagamento. Por favor, entre em contato com nossa equipe.
Tipo de Checkout
onepage

**Comment by r-martins** [comment]
Oi @gabrielhaase . Tudo bom?
O problema do sender_hash pode ser resolvido/acompanhado conforme [estas instruções](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360029247212).

Já o das parcelas, receio que ele esteja relacionado a outro problema de instabilidade do PagSeguro, ainda sem solução. Veja se você consegue simular o problema, fazendo um pedido igual (mesmos produtos, frete, desconto e parcelamento exibido no var/log/pagseguro.log).

De qualquer forma, cobrei o PagSeguro por um update sobre a questão da instabilidade.

Por favor reabra a issue caso consiga reproduzir o problema como sugeri.

Obrigado por reportar.
