### ISSUE TITLE
Modelo de assinatura - Falhas

### ISSUE THREAD

**Issue by rafafl35** [r-martins/PagSeguro-Magento-Transparente#266]
Estamos enfrentando alguns problemas em apenas alguns pagamentos, tanto para cartões de crédito quanto para boletos. Uso o modelo de assinatura.

Seguem alguns erros que estamos recebendo:

Razão
Um erro ocorreu em seu pagamento. sender hash is required. (53150)
Tipo de Checkout: 
onepage

Razão
Falha ao processar seu pagamento. Por favor, entre em contato com nossa equipe.
Tipo de Checkout
onepage

Usamos o modelo de assinatura. Já tentei de tudo, isso nunca resolve.
Uso magento 1.9.3
Estamos perdendo muitas vendas a meses! Me ajudem.

**Comment by asalmeida** [comment]
Tenho o mesmo problema há meses, e sem solução. Também uso o modelo de assinatura, uma pena, mas tive que deixar o PagSeguro como 2a opção no site.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Moisa** [comment]
Ola, Estou com mesmo problema a meses, ja velho pensando em deixar de usar
o pagseguro. Nao entendo como isso não é resolvido, pois isso é muito
crítico:(

Att,

Moises

Em seg, 9 de set de 2019 às 14:45, asalmeida <notifications@github.com>
escreveu:

**Comment by asalmeida** [comment]
Não tenho certeza se o problema é no PagSeguro ou no módulo, pq só acontece no modelo de assinatura.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Moisa** [comment]
Eu também não consigo entender, por que não é resolvido, como vc disse
acontece somente no assinatura

Em seg, 9 de set de 2019 às 14:49, asalmeida <notifications@github.com>
escreveu:

**Comment by rafafl35** [comment]
Ricardo nos ajude com esse problema. Temos que ficar ligando pra cliente no dia a dia e gerar o pedido na mão quando esse tipo de problema ocorre. É pessimo isso.

**Comment by r-martins** [comment]
Oi pessoal. Tudo bom?
Este é um problema antigo mesmo e afeta **todas as lojas PagSeguro que usam o checkout transparente** (independente se ser modelo de assinatura, wordpress, ou **outras plataformas**).

No começo do ano quando estive no Brasil, me reuni com o pessoal do PagSeguro e discutimos o problema. Eles estão migrando uma série de códigos legados internos a fim de resolver o problema, mas não tem uma data para estabilizar o serviço.

**A solução**
No entanto, chegamos a um acordo onde as lojas que usam o [modelo de aplicação](http://r-martins.github.io/PagSeguro-Magento-Transparente/pro/app.html), não precisam enviar o sender_hash quando o serviço deles está fora do ar. E isso tem ajudado muito as lojas nesse modelo, inclusive aquelas que migraram do modelo de assinatura pra lá (em muitos casos a diferença não é tão grande e acaba compensando por conta do aumento na conversão com a marca do UOL.)

Infelizmente isso não se aplica para as lojas no modelo de assinatura, já que não passam por dentro da aplicação.

Sei que quem usa modelo de assinatura tem taxas diferenciadas e no momento estou também modificando o meu serviço a fim de suportar modelos de aplicação com taxas mais agressivas para grandes clientes como vocês. Se puder, [me mande um email](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new) informando o url da loja, volume e negociação atual a fim de me ajudar a moldar os novos modelos.

Vocês podem ver o quão antigo é este problema e como evoluimos ele ao longo do tempo nos links abaixo:
https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/360029247212
https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203887479-Problemas-ao-processar-seu-pagamento-sender-hash-is-required-53150-


**Outra alternativa**
A fim de recuperar pedidos nessa e em outras situações de instabilidade, também criei a [Retentativa](https://pagsegurotransparente.zendesk.com/hc/pt-br/sections/360000689312-Retentativa-e-Recupera%C3%A7%C3%A3o-de-Pedidos-beta-). Acho que vale a pena dar uma olhada.

**Comment by rafafl35** [comment]
Acompanho a tempos a tentativa de correção desse problema. Minha recomendação para quem está entrando, não usar o modelo assinatura, não funciona!

**Comment by r-martins** [comment]
Este é um problema intermitente @rafafl35. Acontecerá em **qualquer loja, de qualquer plataforma, usando checkout transparente do PagSeguro** quando o serviço deles estiver fora. 
A exceção à regra é o nosso [modelo de aplicação](http://r-martins.github.io/PagSeguro-Magento-Transparente/pro/app.html).
