### ISSUE TITLE
Status de pagamento não atualiza

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#268]
Mestre @r-martins, tudo bem? Resolvi abrir esse issue, mas não é bem um issue é mais uma dúvida. Recentemente mudei do cpanel pra um vps onde eu tenho mais controle(melhor coisa que eu fiz kkkkkk) e acontece o seguinte, eu uso o seu módulo e ele não atualiza o status de pagamento, como eu consigo debugar essa parte em específico?

Abs e obrigado

**Comment by r-martins** [comment]
Oi, @rafatriolo. Tudo bom?
O melhor lugar para tirar esse tipo de dúvida é na [Central de Ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br) ou [abrindo um chamado pra mim](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

No entanto, dê uma olhada [nesse artigo](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/209089326-Configurei-o-retorno-autom%C3%A1tico-mas-parece-n%C3%A3o-funcionar-). Ele mostra alguns problemas comuns e como debugar esta parte.
