### ISSUE TITLE
Pagseguro não é exibido na lista de métodos de pagamento

### ISSUE THREAD

**Issue by ghsantosalves** [r-martins/PagSeguro-Magento-Transparente#269]
Boa noite!
Estou tentando utilizar o modulo porem ele não aparece na lista de métodos de pagamento segue prints:
![Captura de tela de 2019-12-03 18-23-00](https://user-images.githubusercontent.com/40925712/70091116-3b5a4380-15fa-11ea-889c-e52e7276aa80.png)

![Captura de tela de 2019-12-03 18-25-33](https://user-images.githubusercontent.com/40925712/70091158-5036d700-15fa-11ea-874b-a1fd050d3a0a.png)

**Comment by r-martins** [comment]
@ghsantosalves para casos de dúvida, por favor [abre uma solicitação pra mim](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

**Comment by ghsantosalves** [comment]
Oh Desculpe!

**Comment by ghsantosalves** [comment]
ativei o log

Em ter., 3 de dez. de 2019 às 18:37, Ricardo Martins <
notifications@github.com> escreveu:
