### ISSUE TITLE
Problema com cross-origin

### ISSUE THREAD

**Issue by marcosguilhermef** [r-martins/PagSeguro-Magento-Transparente#271]
Estou tentando criar uma aplicação web onde todas as informações local ficaram salvas em outro servidor de domínio diferente do original. No entanto, estou tendo os seguintes problemas:
1) "Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://logger.dna.uol.com.br/v2/error?dnaReferer=http%3A%2F%2Flocalhost%2FPagamentoBestgame%2Findex-definitivo.html. (Motivo: o cabeçalho CORS 'Access-Control-Allow-Origin' não está presente)."
2) Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logger.dna.uol.com.br/v2/error?dnaReferer=http%3A%2F%2Flocalhost%2FPagamentoBestgame%2Findex-definitivo.html. (Reason: CORS request did not succeed).

3) Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://logger.dna.uol.com.br/v2/error?dnaReferer=http%3A%2F…oBestgame%2Findex-definitivo.html&scr=2.1.67&_=1582216096292. (Motivo: o cabeçalho CORS 'Access-Control-Allow-Origin' não está presente).

Qual a melhor forma de resolver esse problema? Já tentei aqui e não consegui.

**Comment by r-martins** [comment]
Oi, @marcosguilhermef 
Receio que este não seja um bug do módulo, mas sim uma dúvida relacionada às chamadas e configurações dos servidores do UOL.
Neste caso peço que entre em contato com o próprio PagSeguro.
