### ISSUE TITLE
Problema no Retorno do Pagamento para a Loja Virtual

### ISSUE THREAD

**Issue by czamorasoft** [r-martins/PagSeguro-Magento-Transparente#273]
Olá amigos, muito boa tarde!

Usamos o Módulo PRO na última versão (3.8.1) numa loja virtual Magento 1.7. A configuração está perfeita (é a mesma configuração que temos para outras lojas virtuais no mesmo servidor) e sempre funcionou muito bem.

No entanto de algumas semanas pra cá as transações deixaram de ser atualizadas na loja virtual quando o pagamento é feito por cartão de crédito. O pedido continua com o status "Aguardando Pagamento" e a fatura não é criada.

No PagSeguro o status da transação fica como OK (200), no entanto na loja virtual é gravado o seguinte erro no Log:

2020-02-27T11:33:10-03:00 DEBUG (7): Pedido 100010909 não encontrado no sistema. Impossível processar retorno.

Sendo que o pedido é o mesmo que originou o pagamento e está disponível na loja virtual.

Alguém já enfrentou algum problema semelhante?

--- 
Atualizando:

- Os IPs do PagSeguro estão liberados no firewall.

Status no PagSeguro:
26/03/2020 17:13 | A185E2-CFC4E4 | URL | 200 | 1 | 26/03/2020 17:13

**Comment by r-martins** [comment]
Olá, @czamorasoft .
Peço que abra uma solicitação pra mim no link abaixo. Obrigado pela compreensão.
https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new
