### ISSUE TITLE
no Magento2 a parte do cartão não esta funcionando direito

### ISSUE THREAD

**Issue by fabioxxt** [r-martins/PagSeguro-Magento-Transparente#277]
### Mesmo com os campos do "Nome do titular do cartão" e do "CPF" preenchidos, não recebo elesno backend e consequentemente obtenho esse erro do print

![Sem título](https://user-images.githubusercontent.com/37110607/84452969-aa5dc800-ac2d-11ea-8e4c-c9ea158694a4.jpg)
![84452817-4509d700-ac2d-11ea-869a-7efc5152810d](https://user-images.githubusercontent.com/37110607/84453343-0294ca00-ac2e-11ea-9468-6a514962032c.png)

**Comment by r-martins** [comment]
Oi @fabioxxt 
Como esta configurado o mapeamento de campos?
Que versao esta usando?
Tem url disponivel?

Pode responder estas peguntas aqui **[neste link](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new)**?

Vou encerrar a issue por aqui, até porque esse é o projeto do modulo para Magento 1, o de Magento 2 é outro repositorio.
