### ISSUE TITLE
Adicionar botão para baixar boleto (Magento 1)

### ISSUE THREAD

**Issue by maikjr** [r-martins/PagSeguro-Magento-Transparente#278]
Opa Ricardo, tranquilo ? 
tenho uma sugestão para o modulo **PRO**.
Eu tive um problema com um cliente que estava com alguns clientes reclamando do trabalho para baixar o boleto em dispositivos moveis. então eu modifiquei o arquivo no tema dele:

**/frontend/rwd/default/template/ricardomartins_pagseguropro/payment/info.phtml**

e adicionei um replace na url do boleto para trocar o **print.jhtml** por **download_pdf.jhtml** que faz o download automaticamente do boleto.

fica ai a sugestão para você!! 
você também poderia verificar se o usuário está em um dispositivo móvel e colocar o link do boleto mobile (m.pagseguro) que vem otimizado e com a opção de download.

**Comment by r-martins** [comment]
Oi, @maikjr 
Obrigado pelo feedback/sugestão. Também recebi sua sugestão pelo typeform.
Não sabia da opção de pdf do PagSeguro. Pode apostar que adicionarei nas próximas versões do módulo.
No momento estou trabalhando em uma grande atualização (suporte a recorrencia e sandbox), mas com certeza farei essa.

Só não notei a diferença na visualização do boleto mobile. 
Ex: 
https://pagseguro.uol.com.br/checkout/payment/booklet/print.jhtml?c=522e6e2de3439b7306b7fa0c5685b4a6c3eef7022ba3f8860f86ec4c84b380100631576a4c52ca79#rmcl

e

https://m.pagseguro.uol.com.br/checkout/payment/booklet/print.jhtml?c=522e6e2de3439b7306b7fa0c5685b4a6c3eef7022ba3f8860f86ec4c84b380100631576a4c52ca79#rmcl

Pra mim parece a mesma coisa.

**Comment by fredpiuma** [comment]
@r-martins 

Na verdade faltou dar o replace no seu link, esse é o correto:

https://m.pagseguro.uol.com.br/checkout/payment/booklet/download_pdf.jhtml?c=522e6e2de3439b7306b7fa0c5685b4a6c3eef7022ba3f8860f86ec4c84b380100631576a4c52ca79#rmcl

**Comment by r-martins** [comment]
Demorou mas saiu...
Na versão 3.5.4 do módulo PRO o botão de download do PDF é exibido.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/191149/125023009-4a03b900-e0c1-11eb-9f19-9680e5443d7d.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/191149/125023095-7a4b5780-e0c1-11eb-849f-e6a878e7dbf3.png">


E os botões também são exibidos no formato padrão do Magento.
