### ISSUE TITLE
Erro ao baixar parcelamento

### ISSUE THREAD

**Issue by fredpiuma** [r-martins/PagSeguro-Magento-Transparente#279]
Quando preenchemos o número do cartão e preenchemos a validade, ele faz um get para:
https://pagseguro.uol.com.br/checkout/v2/installments.json

Porém se o nosso navegador completar esses dados de forma automática, esse get não é feito, as parcelas nunca são baixadas e fica aparecendo apenas 1x como opção.

Parece que o onChange não é acionado quando o Chrome completa os dados.

Contornei o problema com o seguinte código:

   timerInstallments = setInterval(() => {
    if( document.querySelector('#card-brand') && document.querySelector('#card-brand').innerHTML.length > 0 ) {
      clearInterval(timerInstallments);
      RMPagSeguroObj.getInstallments();
    }
  },1000);

**Comment by r-martins** [comment]
Oi, @fredpiuma.
Esse problema do autocomplete do cartão já foi resolvido há alguns meses em outro release.
Até testei novamente na [loja demo](https://pagseguro-exemplo-osc.ricardomartins.net.br/) e funcinou sem problemas.
Será que o serviço de parcelas estava fora do ar na hora do seu teste?

https://youtu.be/ljYvjkm_d30 (meu teste)
