### ISSUE TITLE
Não possui a opção de boleto?

### ISSUE THREAD

**Issue by ricardopantani** [r-martins/PagSeguro-Magento-Transparente#281]
Olá.
Essa nova versão não possui a opção de boleto?
Apareceu somente as abas:
PagSeguro - Ricardo Martins
PagSeguro - Cartão de Crédito - Ricardo Martins
PagSeguro - Kiosk mode - Ricardo Martins (beta)
PagSeguro - Pagamento Recorrente (beta) - Ricardo Martins

**Comment by r-martins** [comment]
Oi, @ricardopantani. Tudo bom?
Conforme mostrado [neste passo a passo](https://pagseguro.ricardomartins.net.br/download.html), é preciso instalar um segundo módulo para que o boleto, tef e outros recursos apareçam.

Sempre que tiver dúvidas sobre o módulo, me mande um e-mail pela [Central de Ajuda](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

Grande abraço e sucesso nas vendas.
