### ISSUE TITLE
Pedido cancelado produto não volta pro estoque

### ISSUE THREAD

**Issue by rafatriolo** [r-martins/PagSeguro-Magento-Transparente#283]
Grande mestre Ricardo Martins, tudo bem?

Seguinte nessa ultima atualização do seu módulo notei que quando a transação via cartão de crédito é cancelada pelo pagseguro, o produto não está voltando pro estoque, pode me ajudar com isso? 

Abs e obrigado.

**Comment by r-martins** [comment]
Você diz nos casos onde o PagSeguro nega o pedido?
qual url da loja?

**Comment by rafatriolo** [comment]
Eu acho que acontece quando o pagseguro nega o pedido dps de finalizado. Url: brasilmoedas.com.br

**Comment by r-martins** [comment]
Oi, @rafatriolo 
Fiz um teste por aqui e funcionou normalmente pra mim. Veja o vídeo [aqui](https://youtu.be/J9-gkmsMGgQ).

Não consegui verificar sua configuração na URL que me informou. Está mesmo usando meus módulos?
Vi que a unica transacao que fez com meu módulo indica que está usando o módulo PRO com versão 2.x e módulo principal 3.x. Eles não são compatíveis. Você deve atualizar o módulo PRO. Confirme se este é o caso.

**Comment by rafatriolo** [comment]
Grande mestre @r-martins mto obrigado pela explicação em vídeo. Realmente vi aqui que eu estou usando versões incompatíveis e vou atualizar pra ver se resolve o problema. 

Grande abraço!
