### ISSUE TITLE
Erro em Informações de Pagamento

### ISSUE THREAD

**Issue by lGustavo206** [r-martins/PagSeguro-Magento-Transparente#294]
As informações de pagamento como Bandeira, Últimos 4 dígitos e Parcelas, sumiram após atualização.

![erro](https://user-images.githubusercontent.com/662643/115889110-08506400-a42a-11eb-8c28-7bfaaef4c84a.png)

Na impressão também esta com erro, esta aparecendo código HTML .

**Comment by r-martins** [comment]
Oi @lGustavo206. Tudo bom?
O problema acima foi corrigido na versão 3.12.4.
As informações foram salvas, só não estavam sendo exibidas. Com a atualização, mesmo pedidos antigos devem voltar a aparecer.
Lamento o transtorno.
