### ISSUE TITLE
Problemas ao processar seu pagamento (Parelamento)

### ISSUE THREAD

**Issue by MatNeves** [r-martins/PagSeguro-Magento-Transparente#30]
Não consigo finalizar algumas compras por conta do erro:
Problemas ao processar seu pagamento. installment value invalid value: 45.86(53041)

Não sei se é uma questão do módulo ou da API do PagSeguro, mas fica o registro para análise.
Achei um link comentando porém sem nenhum tipo de solução:
http://forum.pagseguro.uol.com.br/t/9351576/problemas-com-validacao-de-valor-parcelado

**Comment by r-martins** [comment]
Alguem?

**Comment by deniscsz** [comment]
Opa @r-martins, eu me prontifico a testar, mas só poderei fazer isso na semana que vem.

**Comment by MatNeves** [comment]
Confesso que não voltei a ter esse problema novamente. Ou nenhum cliente
meu relatou. Ao meu ver podemos fechar a issue e reabrir caso necessário.
Em 21/01/2015 18:59, "Ricardo Martins" <notifications@github.com> escreveu:

**Comment by deniscsz** [comment]
Não tive problema novamente desse tipo @r-martins, porém achei outros problemas (abri nova issue #78 ).

**Comment by r-martins** [comment]
Como a #78 foi fechada, finalizo esta. Qualquer coisa retomamos.

**Comment by absolutodigital** [comment]
@r-martins estou tendo o mesmo problema com parcelamento em 1x ocorre o erro tb ou 2,3,4 etc

**Comment by edmarholanda** [comment]
Estou com o mesmo problema. Erro ocorreu numa compra de 325, 27 parcelado em 4 vezes sem juros.

**Comment by edmarholanda** [comment]
Pelo menos com um cliente específico nada funciona. 

- Pedi para ele alterar a forma de frete para mudar o valor do pedido. 

- Limpei o cache. 

- Pedi para trocar de navegador. 

Em todas as transações retorna erro: Problemas ao processar seu pagamento. Valor da parcela inválido: 81.03(53041). 

Ontem o mesmo cliente teve um pagamento com o mesmo cartão, mas a transação não foi autorizada pelo banco. 

Nas últimas 80 transações com o PagSeguro este problema ocorreu duas vezes.

**Comment by brunofaria89** [comment]
Estou com o mesmo problema, como resolver?

Problemas ao processar seu pagamento. Valor da parcela inválido: 210.00(53041)

**Comment by r-martins** [comment]
Esse problema poderia acontecer se o valor total do pedido for alterado depois que o usuario clica em finalizar compra. É a única situação que consigo ver isso ocorrer.
Se alguém conseguir me ajudar a simular o problema, posso tentar resolver por aqui.

**Comment by marcuspitu** [comment]
Olá Ricardo estou com o mesmo problema como posso ajudar a resolver? Veja o log (editado para não conter informações pessoais.
A forma de pagamento foi em 3 vezes sem juros.
![erro ps](https://cloud.githubusercontent.com/assets/4326788/11045035/4f28e938-870c-11e5-8174-d682dd549b25.png)


2015-11-09T19:43:23+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => '?????',
  'token' => '??????',
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => '??????',
  'currency' => 'BRL',
  'creditCardToken' => '??????',
  'reference' => '100002646',
  'extraAmount' => '0.00',
  'notificationURL' => 'https://tecasistemas.com.br/pseguro/notification/',
  'itemId1' => '10968',
  'itemDescription1' => 'Kit Motor Deslizante DZ Nano Turbo - ROSSI',
  'itemAmount1' => '424.05',
  'itemQuantity1' => '2',
  'itemId2' => '10973',
  'itemDescription2' => 'Kit Motor Deslizante DZ Nano Turbo - ROSSI',
  'itemAmount2' => '412.60',
  'itemQuantity2' => '1',
  'itemId3' => '10979',
  'itemDescription3' => 'Controle Remoto Veicular - ROSSI (O Port䯠顁tivado pelo Farol do Carro)',
  'itemAmount3' => '36.90',
  'itemQuantity3' => '1',
  'senderName' => 'Marcus Winkler',
  'senderEmail' => '???????',
  'senderHash' => '???????',
  'senderCPF' => '??????',
  'senderAreaCode' => '12',
  'senderPhone' => '??????',
  'shippingAddressStreet' => 'gfhgfhf',
  'shippingAddressNumber' => 'gh',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => 'fghgf',
  'shippingAddressPostalCode' => '78540000',
  'shippingAddressCity' => 'Clⶤia',
  'shippingAddressState' => 'MT',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '160.52',
  'billingAddressStreet' => 'gfhgfhf',
  'billingAddressNumber' => 'gh',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => 'fghgf',
  'billingAddressPostalCode' => '78540000',
  'billingAddressCity' => 'Clⶤia',
  'billingAddressState' => 'MT',
  'billingAddressCountry' => 'BRA',
  'creditCardHolderName' => '??????',
  'creditCardHolderBirthDate' => '09/12/1978',
  'creditCardHolderCPF' => '???????',
  'creditCardHolderAreaCode' => '12',
  'creditCardHolderPhone' => '?????',
  'installmentQuantity' => '3',
  'installmentValue' => '486.03',
)
2015-11-09T19:43:25+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53041</code><message>installment value invalid value: 486.03</message></error></errors>'

**Comment by r-martins** [comment]
Oi @marcuspitu,
Parece que tem uma pequena diferença no valor do item 1...
'itemAmount1' => '424.05',
'itemQuantity1' => '2',

Daria 848,10 e nao 848,08 como mostra no carrinho.
Por isso que deve estar dando diferença no valor da parcela.. =/

Consegue ver no painel qual o valor do item corretamente?

Abs

**Comment by marcuspitu** [comment]
Olá Ricardo, realmente verifiquei e estou com problema de arredondamento no meu carrinho, vou resolver e posto se funcionou. Muito obrigado.

**Comment by mauriciodsssouza** [comment]
Olá, também esta acontecendo o mesmo comigo!!! Alguém já conseguiu solucionar??

**Comment by mateus007** [comment]
Mesmo problema por aqui. Alguém encontrou uma solução?

**Comment by marcuspitu** [comment]
Olá amigos. No meu caso o Ricardo descobriu que meu carrinho está calculado os valores com pequenas diferenças (erro) de arredondamento e com isso o valor acaba chegando errado no OSC e consequentemente o módulo do PagSeguro apresenta este erro que ná real não é erro do módulo. Estou resolvendo o problema que tenho de arredondamento e assim que terminar vou ver se resolve este problema. Posto os resultados aqui em mais ou menos 10 dias.

**Comment by brunoweig** [comment]
Bom dia senhores,
Imagino que o problema já tenha sido resolvido mas só pra ficar registrado...tive esse mesmo problema essa última sexta-feira quando estava testando o pagseguro com sandbox, e resolvi esse problema adicionando um campo a mais na requisição: **noInterestInstallmentQuantity**.

Todas as minhas compras fechavam normalmente em 1x, mas com qualquer outra parcela retornava esse mesmo erro 53041. Agora está fechando com qualquer parcela sem problema.

Abraço

**Comment by marcuspitu** [comment]
Olá brunoweig tem como passa mais detalhes de como resolveu o problema?

**Comment by marcuspitu** [comment]
Olá brunoweig <https://github.com/brunoweig> tem como passa mais detalhes
de como resolveu o problema?







Saudações, Marcus Ligabue Winkler.

Fixo: (12) 3835-3346 / (12) 3835-1083
        4004-0435 ramal 72010
Vivo: (12) 99769-7908 Nextel ID: 96*12327
E-mail: marcus@tecasistemas.com.br


Em 23 de maio de 2016 10:58, brunoweig <notifications@github.com> escreveu:

**Comment by perrera** [comment]
Ola amigos, eu encontrei esse problema também. Verifiquei no meu log que o campo "installmentValue" estava com valor errado. 
Eu estava com esse erro ocorrendo em todas as transações. 
Em uma das vezes que estava simulando tentando encontrar a causa do erro, após digitar o cartão eu já percebi que o total da parcela estava diferente do valor total correto, então eu mudei a forma de envio. O OSC atualiza os totais após modificar a forma de envio, quando mudou comecou a calcular certo.
Tentei simular o erro novamente e agora está correto.
Não sei se resolveu, mas aparentemente temos um problema nesse total, talvez algo no OSC.
Eu uso parcelamento com juros.

**Comment by perrera** [comment]
Bom pessoal, eu estou com o mesmo problema. Voltou a ocorrer.
Acho estranho pois comecou a ocorrer essa semana.
Ele estava funcionando normalmente.
Alguem tem alguma sugestao!?

**Comment by nelsontristao** [comment]
Todos clientes que tentaram parcelar não conseguiram. Segue abaixo um exemplo:
2016-09-11T03:55:35+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => '???,
  'token' => '????,
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => '???,
  'currency' => 'BRL',
  'creditCardToken' => '?????,
  'reference' => '???',
  'extraAmount' => '0.00',
  'notificationURL' => 'https://????.com.br/pseguro/notification/',
  'itemId1' => '143',
  'itemDescription1' => 'Camiseta Galileu - Masculina',
  'itemAmount1' => '49.90',
  'itemQuantity1' => '1',
  'itemId2' => '145',
  'itemDescription2' => 'Camiseta Galileu - Feminina',
  'itemAmount2' => '49.90',
  'itemQuantity2' => '1',
  'senderName' => '??',
  'senderEmail' => '??@gmail.com',
  'senderHash' => '???',
  'senderCPF' => '???',
  'senderAreaCode' => '21',
  'senderPhone' => '???',
  'shippingAddressStreet' => '???,
  'shippingAddressNumber' => '??',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => '???',
  'shippingAddressPostalCode' => '???',
  'shippingAddressCity' => '???',
  'shippingAddressState' => '??',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '20.15',
  'billingAddressStreet' => '??,
  'billingAddressNumber' => '??,
  'billingAddressComplement' => '',
  'billingAddressDistrict' => '???',
  'billingAddressPostalCode' => '???',
  'billingAddressCity' => '???',
  'billingAddressState' => 'RJ',
  'billingAddressCountry' => 'BRA',
  'creditCardHolderName' => '???',
  'creditCardHolderBirthDate' => '???',
  'creditCardHolderCPF' => '???',
  'creditCardHolderAreaCode' => '???',
  'creditCardHolderPhone' => '????',
  'installmentQuantity' => '2',
  'installmentValue' => '59.98',
  'public_key' => '??????????????',
)
2016-09-11T03:55:37+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53041</code><message>installment value invalid value: 59.98</message></error></errors>'

**Comment by mlimasolucoes** [comment]
Fala @r-martins beleza?
Voltei a ter esse mesmo erro em outro cliente. O produto tem o valor de R$4.364,00 e é utilizado na compra um cupom que dá 20% de desconto, ficando o valor de R$3.491,20. O cliente tentou parcelar em 6x com juros, no nosso dropdown de parcelas é informado o valor: 6x R$617,01 porém na mensagem de erro (em anexo) nos é informado o valor da parcela sem juros (581.87). 
Hipotese 1:
 A parcela apesar de mostra com juros corretamente no dropdown está sendo enviada sem juros?
Hipotese 2:
O valor não arredondou corretamente a divisão, a principio sem juros (3.491,20 / 6 = 581,8666666666667) apesar do nosso caso ter juros

![img-20161010-wa0005](https://cloud.githubusercontent.com/assets/8741804/19247525/02857bb0-8f02-11e6-8d01-0af3c8809319.jpg)

**Comment by pedrodakar** [comment]
Bom dia a todos.

Estou com o mesmo erro em duas lojas. Porém pude verificar um claro erro.

Nas duas, o valor da parcela é passado ao pagseguro sem juros.
No dropbox as parcelas são geradas de acordo, com descontos certos, porém não é informado o juros das parcelas.

Ao habilitar parcelamento sem juros no pagseguro tenho sucesso nas compras.

Ricardo Martins, tem algum parametro de configuração que não pude encontrar que informa os juros ?

**Comment by pedrodakar** [comment]
SubTotal	R$170,00
Embalagem e Entrega	R$24,50
Valor Total	R$194,50


Log:

)
2016-10-11T12:22:32+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53041</code><message>installment value invalid value: 48.63</message></error></errors>'
2016-10-11T12:24:15+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => 'xxxxxx',
  'token' => 'xxxxxxxxxx',
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => 'xxxxxx',
  'currency' => 'BRL',
  'creditCardToken' => 'xxxxxx',
  'reference' => '100000xxx',
  'extraAmount' => '0.00',
  'notificationURL' => xxxxxx/pseguro/notification/',
  'itemId1' => '417',
  'itemDescription1' => 'Guidão T6 Aluminio - Fly Racing ',
  'itemAmount1' => '170.00',
  'itemQuantity1' => '1',
  'senderName' => 'xxxx',
  'senderEmail' => 'xxxxxx',
  'senderHash' => 'acf7e181334d7ac51174d50de163b587041b8ff05922cb984576ad4ef80b982b',
  'senderCPF' => 'xxxxx',
  'senderAreaCode' => 'xxx',
  'senderPhone' => 'xxxxx',
  'shippingAddressStreet' => 'xxxx',
  'shippingAddressNumber' => 'xxx',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => 'xxxx',
  'shippingAddressPostalCode' => 'xxxx',
  'shippingAddressCity' => 'xxxx',
  'shippingAddressState' => 'xxxx',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '24.50',
  'billingAddressStreet' => 'xxxxx',
  'billingAddressNumber' => 'xxxx',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => 'xxxx',
  'billingAddressPostalCode' => 'xxx',
  'billingAddressCity' => 'xxxxx',
  'billingAddressState' => 'xxxxx',
  'billingAddressCountry' => 'BRA',
  'creditCardHolderName' => 'xxxx',
  'creditCardHolderBirthDate' => 'xxxx',
  'creditCardHolderCPF' => 'xxxx',
  'creditCardHolderAreaCode' => 'xxx',
  'creditCardHolderPhone' => 'xxx',
  'installmentQuantity' => '3',
  'installmentValue' => '64.83',
)

**Comment by mlimasolucoes** [comment]
Atualizei o módulo com a última versão no git e aparentemente foi solucionado! @pedrodakar confirma se aí após atualizar passa também. Abs

**Comment by pedrodakar** [comment]
@mlimasolucoes @ :+1:  Não tinha visto a atualização. Testei nas duas lojas e aparentemente tudo ok agora. Vou monitorar as compras, se tiver algum erro eu retorno. Obrigado.

**Comment by lorenatmc** [comment]
Ola, tive o mesmo problema. Estou utilizando a aplicação. 
Operação de pagamento não realizada.
Motivo
Problemas ao processar seu pagamento. Valor da parcela inválido: 36.62(53041)

**Comment by asalmeida** [comment]
Tive o mesmo problema, só que não consegui simular o problema e com isso achar a raiz do problema. Acontecia com meus clientes, mas comigo nao, mas nem sempre. :( Tive que destativar o módulo e voltar para o do Bruno, pois esse dava esse problema.

**Comment by davirs** [comment]
@r-martins 
Estou usando a última versão do módulo e o problema é exatamente o mesmo.:

erro 53041 installment value invalid value

Eu percebi que isso só ocorre quando tem alguma regra de desconto. Neste log tem um cupom com 20% de desconto:

'extraAmount' => '-87.12',
'itemAmount1' => '435.60',
'shippingCost' => '23.00'
'installmentQuantity' => '1',
'installmentValue' => '458.60',

Retorno PagSeguro (/transactions): <code>53041</code><message>installment value invalid value: 458.60</message>

O valor deveria ser 371,48
Alguém poderia informar se acharam uma solução para o problema?
Obrigado

**Comment by asalmeida** [comment]
Não fiz essa simulação, vou fazer no teste, faz sentido.


Enviado do Outlook<http://aka.ms/weboutlook>


________________________________
De: davirs <notifications@github.com>
Enviado: terça-feira, 22 de novembro de 2016 15:23
Para: r-martins/PagSeguro-Magento-Transparente
Cc: asalmeida; Comment
Assunto: Re: [r-martins/PagSeguro-Magento-Transparente] Problemas ao processar seu pagamento (Parcelamento) (#30)


@r-martins<https://github.com/r-martins>
Estou usando a última versão do módulo e o problema é exatamente o mesmo.:

erro 53041 installment value invalid value

Eu percebi que isso só ocorre quando tem alguma regra de desconto. Neste log tem um cupom com 20% de desconto:

'extraAmount' => '-87.12',
'itemAmount1' => '435.60',
'shippingCost' => '23.00'
'installmentQuantity' => '1',
'installmentValue' => '458.60',

Retorno PagSeguro (/transactions): 53041installment value invalid value: 458.60

O valor deveria ser 371,48
Alguém poderia informar se acharam uma solução para o problema?
Obrigado

-

**Comment by studiomantis** [comment]
Estou tendo o mesmo problema :/ ainda não conseguimos resolver aqui.

**Comment by JonathanCosta** [comment]
@r-martins 
Comigo esse erro aconteceu quando por exemplo o cliente tenta comprar um produto com o valor de R$559,30, e divide de 3 vezes, eu estou fazendo 4 vezes sem juros então a parcela retornada e de R$ 186,43.
O erro acontece quando valor de todas as parcelas somadas fica diferente do valor total. no meu caso 186,43*3 = 559,29.

Resumindo por R$0,01 de diferença o cliente não consegue finalizar.
Acredito que para resolver o PagSeguro tenha que começar a aceitar mais que duas casa decimais ou conseguir pensar em alguma validação aonde que verifica se existe alguma divergência entro os valores , para essa parte do codigo:

`$return = array();
        if ($payment->getAdditionalInformation('installment_quantity')
            && $payment->getAdditionalInformation('installment_value')) {
            $return = array(
                'installmentQuantity'   => $payment->getAdditionalInformation('installment_quantity'),
                'installmentValue'      => number_format($payment->getAdditionalInformation('installment_value'), 2, '.', ''
                ),
            );
        } else {
            $return = array(
                'installmentQuantity'   => '1',
                'installmentValue'      => number_format($order->getGrandTotal(), 2, '.', ''),
            );
        }
        return $return;`

**Comment by r-martins** [comment]
@JonathanCosta, você pode [abrir um chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new) pra mim informando os dados enviados ao pagseguro no arquivo pagseguro.log ? (voce pode ocultar os dados do cliente se quiser)

**Comment by alvarolordelo** [comment]
Pessoal, acho que descobri o problema, A API do pag Seguro espera que o valor total seja igual ao do selecionado
exemplo cigarro = 100 reais
installmentQuantity = parcelas = 2x
installmentValue = valor = 51.00
total calculado = 102.00
erro
agora se após enviar os itens o valor da soma deles bater com o total parcelado passa.
façam essa correção e me retornem se deu certo
eu corrigi o itemAmount1 pra dar o valor do calculo = parcela x valor

**Comment by pedroohsolucoes** [comment]
Olá, estou tendo esse erro também, alguém encontrou alguma solução?

**Comment by r-martins** [comment]
@pedroohsolucoes este problema geralmente ocorre quando outro módulo altera o valor do pedido depois do cliente selecionar as parcelas.
Caso esteja tendo problemas, abra um chamado pra mim com url da loja e valores enviados pra gente testar... ;)

**Comment by mlimasolucoes** [comment]
Não tenho ctza mas acho que rolava esse xabu de vez em quando, quando tinha
alguma regra de promoção criada pra aumentar o preço dos produtos

**Comment by r-martins** [comment]
Hoje peguei o caso de um cliente que tinha um cloudflare (ou outro cache) repetindo o valor das parcelas, dados de sessão e outras coisas entre diferentes clientes/sessões.
Tentem ver se o /pseguro/ajax/getSessionId e /pseguro/ajax/getGrandTotal estão sendo cacheando indevidamente.

**Comment by kenionatan** [comment]
Está acontecendo comigo em algumas compras, percebi que o pagseguro quando retorna o valor da parcela com a terceira casa decimal terminada em 5, ele arredonda a segunda casa decimal, meu exemplo:

**Item 1:** Quantidade = 1, Valor: R$ 4,00
**Item 2:** Quantidade = 1, Valor: R$ 6,60
**Total dos produtos** = R$ 10,60
**Desconto(5%)** = R$ 10,60 - R$ 0,53
**Total com desconto** = R$ 10,07

Na hora de fazer o calculo das parcelas através do **PagSeguroDirectPayment.getInstallments**
ele envia o valor de R$ 10,07, em duas vezes fica: 2 x de R$ 5,035
o pagseguro retorna o valor da parcela de 5,04
retornando assim, a mensagem ao fim da compra: **installment value invalid value: 5,04**

Alguém com alguma solução pra esse tipo de situação?

**Comment by r-martins** [comment]
@kenionatan por favor [abre um chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new) pra mim?
E certifique-se que está usando uma versão >= 3.8.4 do módulo principal.
