### ISSUE TITLE
Problema no checkout mobile Magento 1.9.3.0

### ISSUE THREAD

**Issue by AttilaBS** [r-martins/PagSeguro-Magento-Transparente#301]
Primeiramente, gostaria de parabenizar mais uma vez o Ricardo Martins pela qualidade do módulo. 

O problema que estou tendo ocorre há alguns meses em qualquer das versões mais atuais (testei várias) e continua com a versão 3.13.0 + 3.5.1 do Pro. 

Segue o problema: 
Eu estou tendo um problema com o OSC6 e o módulo (qualquer versão mais atual) onde o seguinte erro ocorre ao validar qualquer forma de pagamento:

payment.js:263 Uncaught TypeError: RMPagSeguro.getInstallments is not a function
    at klass.savePayment (payment.js:263)
    at HTMLInputElement.<anonymous> (payment.js:101)
    at HTMLInputElement.responder (prototype.js:5598)

Na web, apesar do erro, não há qualquer problema. Só que no mobile, aparentemente por causa da função validate() dentro de savePayment() , o checkout não passa para o bloco revisão de pagamento e não consigo fechar a compra. Só consegui um workaround mudando o momento de execução do savePayment(), o que gera alguns transtornos, como não validar se os dados de pagamento estão corretos. 

 PHP 5.6;
 RM Pagseguro 3.13.0;
 RM Pagseguro PRO 3.5.1;
 OSC6 Inovarti;

Se precisarem da mais informações só avisar. 

Grato

**Comment by r-martins** [comment]
Oi, @AttilaBS . Tudo bom?
Fiz um teste com o módulo atualizado na loja demo com Android e não tive problemas.
Fiz um vídeo: ﻿https://www.dropbox.com/s/bslu3t5t8tn18ok/pagseguro-osc-mobile.mp4?dl=0

No caso, a [loja demo](https://pagseguro-exemplo-osc.ricardomartins.net.br/) usa as últimas versões de cada módulo.
Me avise se não reproduzi corretamente ou se você conseguir reproduzir na mesma loja.

Abs
