### ISSUE TITLE
[NÃO É UMA ISSUE] Uma dúvida, o módulo atualmente suporte assinaturas (https://dev.pagseguro.uol.com.br/docs/pagamento-recorrente)?

### ISSUE THREAD

**Issue by vacosti** [r-martins/PagSeguro-Magento-Transparente#302]
[NÃO É UMA ISSUE] Uma dúvida, o módulo atualmente suporta assinaturas (https://dev.pagseguro.uol.com.br/docs/pagamento-recorrente)?

**Comment by r-martins** [comment]
Sim.
Veja [como usar a recorrência no Magento com PagSeguro](https://pagsegurotransparente.zendesk.com/hc/pt-br/sections/360009089331-Recorr%C3%AAncia).

Qualquer dúvida que tiver ou problema (que não seja claramente um bug), você pode [entrar em contato por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

Espero ter ajudado. ;)
