### ISSUE TITLE
Falha de comunicaÃ§Ã£o com API do PagSeguro: Could not resolve host: ws.pagseguro.uol.com.br

### ISSUE THREAD

**Issue by rafafl35** [r-martins/PagSeguro-Magento-Transparente#303]
Desde ontem com esse problema em minha loja.

2021-11-06T01:45:30+00:00 DEBUG (7): Falha de comunicaÃ§Ã£o com API do PagSeguro: Could not resolve host: ws.pagseguro.uol.com.br
2021-11-06T01:46:18+00:00 DEBUG (7): Falha de comunicaÃ§Ã£o com API do PagSeguro: Could not resolve host: ws.pagseguro.uol.com.br
2021-11-06T01:46:44+00:00 DEBUG (7): Falha de comunicaÃ§Ã£o com API do PagSeguro: Could not resolve host: ws.pagseguro.uol.com.br
2021-11-06T01:46:51+00:00 DEBUG (7): Falha de comunicaÃ§Ã£o com API do PagSeguro: Could not resolve host: ws.pagseguro.uol.com.br
2021-11-06T01:46:57+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (

**Comment by r-martins** [comment]
Problemas de resolução de DNS geralmente são contornados no [modelo de aplicação](https://pagseguro.ricardomartins.net.br/pro/app.html).
Receio que esteja usando modelo de assinatura ou nenhum dos dois. Neste caso, verifique as configurações e status do seu serviço de DNS.

**Comment by rafafl35** [comment]
Eu uso o modelo de assinatura.

Neste caso, verifique as configurações e status do seu serviço de DNS. 

Como assim meu serviço de DNS?
O que ele tem haver com o problema? Consegue me explicar? Obrigado.

**Comment by czamorasoft** [comment]
@rafafl35 @r-martins Mesma falha por aqui.

Só está ocorrendo a falha no modelo de assinatura.
Clientes que usam modelo de aplicação não está com o problema.

Dois datacenters diferentes. Há clientes que só usam o módulo free também (sem modelo de assinatura nem aplicação, pois só usam para cartão) e também com o mesmo problema.

Outros dois clientes noutro datacenter, não apresentam problemas.

**Comment by rafafl35** [comment]
Aqui já está funcionando. Mas está acontecendo diversas falhas! Está péssimo.

**Comment by czamorasoft** [comment]
Fiz um teste: 
Pedi ao meu irmão que tem uma loja no Magento e está hospedado no mesmo servidor habilitar o modelo de aplicação.
Assim que habilitou e ativou o modelo de aplicação, voltou a funcionar automaticamente.

Eu tiro o modelo de aplicação, volto ao modelo de assinatura, deixa de funcionar na hora.

@r-martins Quando usamos o modelo de aplicação, a transação segue algum caminho diferente (no sentido de DNS) do que do modelo de assinatura?

**Comment by rafafl35** [comment]
Creio que o modelo de assinatura não é rentável. 
Aumente a cobrança. Precisamos de algo que funcione. 
Nos ajude!

**Comment by czamorasoft** [comment]
@rafafl35 Ainda pode estar relacionado com o DNS mesmo, **SE** o modelo de aplicação faz um caminho diferente na comunicação com o PagSeguro, que não via ws.pagseguro.com.br ou se é validado noutro canto (e assume aquela sessão, ip, etc.) antes de ser enviado ao PagSeguro.

Não duvidaria (apesar de achar **muito difícil**) um bloqueio do PagSeguro ao AS do Datacenter que eu atuo, por isso já abri um ticket com a equipe de atendimento a desenvolvedores por lá. É mais provável um bloqueio do Datacenter para o PagSeguro (apesar de também ser difícil, menos do que a primeira hipótese). Só não veria motivos para isto.

Vou ver se consigo algum workaround. Se conseguir, posto aqui.

**Comment by czamorasoft** [comment]
Cheguei a uma outra questão:

**APESAR** de o modelo de aplicação permitir que a transação continue, o retorno automático do PagSeguro não atualiza o status do pagamento, seja ele cancelado ou com sucesso. 

Ou seja, o 'workaround' de usar o modelo de aplicação não resolve o problema. O pedido entra, mas não se atualiza.

**Comment by czamorasoft** [comment]
O erro do retorno (com ou sem modelo de aplicação), gravado no Log do Magento:

a:5:{i:0;s:137:"Unable to Connect to ssl://ws.pagseguro.uol.com.br:443. Error #0: php_network_getaddresses: getaddrinfo failed: Name or service not known"

**Comment by rafafl35** [comment]
2021-11-06T13:25:47+00:00 DEBUG (7): Retorno do Pagseguro para notificationCode A4BAE9-79F8A7F8A752-15543A5FAEAA-9801AA: 
2021-11-06T13:25:47+00:00 DEBUG (7): Retorno de notificacao XML PagSeguro em formato nÃ£o esperado.
2021-11-06T13:26:33+00:00 DEBUG (7): NotificaÃ§Ã£o recebida do pagseguro com os parÃ¢metros:array (
  'notificationCode' => 'xxxxx-xxxxx-xxxxx-xxxxx',
  'notificationType' => 'transaction',

**Comment by czamorasoft** [comment]
@rafafl35 tem algum de hoje?

**Comment by czamorasoft** [comment]
Creio que consegui resolver sem necessitar de nenhuma mudança no módulo @rafafl35 . Já compartilho a solução contigo.
Deixe-me fazer alguns testes.

**Comment by czamorasoft** [comment]
@rafafl35 Você tem acesso ao /etc/resolv.conf do servidor? No sentido de user um dedicado, cloud ou VPS? O que eu fiz: Modifiquei o DNS default do resolv.conf e utilizei o 8.8.8.8 do Google e 1.1.1.1 do Cloudflare. Isto pelo seguinte: Por algum motivo o PagSeguro aplicou um bloqueio no AS / Bloco / Datacenter, não sei... Mas já abri um ticket com eles para descobrir. E provavelmente afetou o seu datacenter também. Então é necessário, temporariamente, usar os DNSs públicos para que, então, você possa ver com o seu datacenter o motivo desta falha de comunicação, pois creio que via PagSeguro demorará mais. Se responderem no PagSeguro eu atualizo aqui posteriormente.

@r-martins Obrigado pela luz na resposta inicial do Rafael. O que me fez suspeitar de ser o DNS é porque ocorreu em 2 servidores diferentes, em datacenters diferentes, de empresas diferentes, AS's diferentes, etc.

Abraço!

**Comment by czamorasoft** [comment]
Aproveito para agradecer ao amigo Silas Tammerik da (https://www.dado.cloud/) pelo apoio. Tem que ficar aqui registrado, pois foi fundamental em auxiliar na correção sem depender do PagSeguro.

**Comment by rafafl35** [comment]
Consegue me auxiliar nessa alteração?
Tenho um VPS

**Comment by czamorasoft** [comment]
@rafafl35 Via shell, edite o arquivo /etc/resolv.conf

Mude, por exemplo, de:

nameserver X.X.X.X
nameserver Y.Y.Y.Y

Para:

nameserver 8.8.8.8
nameserver 1.1.1.1

Salve e reinicie o SSL.

Se você tiver um suporte da empresa que contrata o SSL, peça para eles te orientarem, pois pode fazer o seu VPS ficar incomunicável se não for feito corretamente. O 8.X é o DNS público do Google, o 1.X do Cloudflare. 

O ideal é que abra um ticket no teu datacenter para que eles averiguem o motivo de o DNS default deles não "encontrar" o nameserver do PagSeguro / UOL.

Abraço!

**Comment by czamorasoft** [comment]
Obs.: Se você usa o cPanel, pode fazer pelo WHM em: **Resolver Configuration**:

https://hosthowto.com/how-to-configure-google-public-dns-ip-resolver-on-cpanel/

**Comment by rafafl35** [comment]
Alterei pelo WHM, mas continuo com Falhas em minhas vendas.
Consegue me auxiliar?

2021-11-08T20:34:49+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53118</code><message>sender cpf or sender cnpj is required.</message></error><error><code>53045</code><message>credit card holder cpf is required.</message></error><error><code>53042</code><message>credit card holder name is required.</message></error></errors>'
2021-11-08T20:34:49+00:00 DEBUG (7): Could not determine the transaction ID of the WS returned XML: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<errors><error><code>53118</code><message>sender cpf or sender cnpj is required.</message></error><error><code>53045</code><message>credit card holder cpf is required.</message></error><error><code>53042</code><message>credit card holder name is required.</message></error></errors>

2021-11-08T20:36:01+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => 'Informação Retirada XXXXX',
  'token' => 'Informação Retirada XXXXX',
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => 'Informação Retirada XXXXX',
  'currency' => 'BRL',
  'creditCardToken' => 'Informação Retirada XXXXX',
  'reference' => '100026378',
  'extraAmount' => '0.00',
  'notificationURL' => 'Informação Retirada XXXXX',
  'itemId1' => '67345',
  'itemDescription1' => 'Dosador Unidade',
  'itemAmount1' => '0.50',
  'itemQuantity1' => '100',
  'senderName' => 'Informação Retirada XXXXX',
  'senderEmail' => 'Informação Retirada XXXXX',
  'senderHash' => '81fe67c55b9a2cf8e812e82c3a7ac9ac83fb3ff277597bee75505b8912834d0e',
  'senderCPF' => '',
  'senderAreaCode' => '11',
  'senderPhone' => 'Informação Retirada XXXXX',
  'isSandbox' => '',
  'senderIp' => '187.38.63.188',
  'shippingAddressStreet' => 'Rua Diamante Preto',
  'shippingAddressNumber' => '525',
  'shippingAddressComplement' => 'Fundos ',
  'shippingAddressDistrict' => 'Chᣡra Calif󲮩a',
  'shippingAddressPostalCode' => '03317040',
  'shippingAddressCity' => 'S㯠Paulo',
  'shippingAddressState' => 'SP',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '3',
  'shippingCost' => '15.10',
  'billingAddressStreet' => 'Rua Diamante Preto',
  'billingAddressNumber' => '525',
  'billingAddressComplement' => 'Fundos ',
  'billingAddressDistrict' => 'Chᣡra Calif󲮩a',
  'billingAddressPostalCode' => '03317040',
  'billingAddressCity' => 'S㯠Paulo',
  'billingAddressState' => 'SP',
  'billingAddressCountry' => 'BRA',
  'creditCardHolderName' => '',
  'creditCardHolderBirthDate' => '01/01/1970',
  'creditCardHolderCPF' => '',
  'creditCardHolderAreaCode' => '11',
  'creditCardHolderPhone' => 'Informação Retirada XXXXX',
  'installmentQuantity' => '1',
  'installmentValue' => '65.10',
)

**Comment by r-martins** [comment]
@rafafl35 por favor envie as informações **[por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new)**, informando o url da loja.
Ficará mais fácil e melhor para lhe ajudar.
