### ISSUE TITLE
Razão Um erro ocorreu em seu pagamento. CPF ou CNPJ do titular do cartão é obrigatório. (53118) 

### ISSUE THREAD

**Issue by rafafl35** [r-martins/PagSeguro-Magento-Transparente#304]
Olá Ricardo,

Eu uso o modelo de assinatura.
Venho tenho alguns problemas de Falha.

O cliente está escolhendo a opção Boleto Bancário e recebe esse erro.
Razão: Um erro ocorreu em seu pagamento. CPF ou CNPJ do titular do cartão é obrigatório. (53118)
Consegue me auxliar?

Outro erro é apenas a falha:
Razão: Falha ao processar seu pagamento. Por favor, entre em contato com nossa equipe. 

Se puder me auxiliar ficarei grato.
Att.

**Comment by r-martins** [comment]
Olá @rafafl35. Tudo bom?
Dê uma olhada em https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/205603146-CPF-do-Cliente-Como-configurar-.

Caso a dúvida ou problema persista, por favor [entre em contato por aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).
