### ISSUE TITLE
TEF não funciona para operações no celular Banco do Brasil

### ISSUE THREAD

**Issue by guittavares** [r-martins/PagSeguro-Magento-Transparente#308]
Na compra pelo celular escolhendo a opção de TEF com o Banco do Brasil, ao clicar no botão para realizar o pagamento, o cliente é direcionado para o link mpag.bb.com.br/site/mpag e quando clica na opção de "Débito em sua conta", o cliente é direcionado para a loja de aplicativos (Play Store ou Apple Store) e ao abrir o aplicativo e fazer seu login, nada acontece.

**Comment by r-martins** [comment]
Oi @guittavares .
Tentei reproduzir sem muito sucesso. [Video](https://capture.dropbox.com/P73B22VcbFH07JHR)
Pelo que descreve o problema se dá lá no banco do brasil (na url deles), e isso fica fora do controle do PagSeguro ou de nossa integração. No teste que fiz ele não pediu o aplicativo, o que indica ser um comportamento (ruim) do BB e não do PagSeguro ou do módulo.

Sugiro que mande seu feedback pro BB.
Mas obrigado por reportar mesmo assim.

**Comment by guittavares** [comment]
Agradeço o retorno.
Realmente, não tinha me atentado nas requisições que são feitas diretamente pelo Banco do Brasil, apenas onde aparece Loja Conveniada: PAGSEGURO

Vou reportar a eles.

https://user-images.githubusercontent.com/28607297/165966092-f999c441-e439-46d0-a6fb-004efe13c315.mp4
