### ISSUE TITLE
Valor da Parcela Inválido

### ISSUE THREAD

**Issue by thiagoromera** [r-martins/PagSeguro-Magento-Transparente#311]
Bom dia. Parabéns pelo execelente trabalho

Fiz um teste com um valor baixo, tipo, menos de R$ 20,00 e recebo um erro #53041 dizendo que o valor é inválido, porém funciona quando o valor é maior.

Como ajustar isso? Tentei pelo painel do pagseguro, não consegui.

**Comment by r-martins** [comment]
Oi, @thiagoromera. Tudo bom?
Vamos lá...
1. O valor da parcela nunca pode ser menor que 5.00.
2. O valor da parcela deve corresponder ao valor devolvido pela [api de parcelas](https://dev.pagseguro.uol.com.br/v1/reference/transparente-biblioteca-javascript#getinstallments). Esse valor levará em consideração o cartão utilizado, valor total do pedido, e configurações de juros especificadas.
3. O valor da parcela deve corresponder ao valor do pedido (com juros se aplicado), que deve ser igual a soma total dos itens, frete, e extraAmount.

Se ainda tiver dúvidas, entre em contato por [aqui](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new).

Abs
