### ISSUE TITLE
Estorno

### ISSUE THREAD

**Issue by LuanRBLEstetica** [r-martins/PagSeguro-Magento-Transparente#314]
Quero um estorno do valor me arrependi da compra, não foi efetuada por mim, aguardo retorno

**Comment by r-martins** [comment]
Oi, @LuanRBLEstetica .
Neste caso, procure a loja que vendeu o produto pra você ou acione o PagBank e a proteção ao comprador.
Este canal é destinado a desenvolvedores e usuários de nossas integrações.
