### ISSUE TITLE
Problema ao gerar parcelas e enviar pedido

### ISSUE THREAD

**Issue by mferracioli** [r-martins/PagSeguro-Magento-Transparente#315]
Nas últimas semanas passamos a ter problemas na hora finalizar pedidos e gerar as parcelas, principalmente em dispositivos mobile. Notamos que a token  do cartão não é gerada e no console estouram alguns erros:

![image](https://github.com/r-martins/PagSeguro-Magento-Transparente/assets/32615/7302c26f-ea31-4ecf-ab75-03141b070605)
![image](https://github.com/r-martins/PagSeguro-Magento-Transparente/assets/32615/87283e7e-685f-46eb-8536-15de2f9c5e52)
![image](https://github.com/r-martins/PagSeguro-Magento-Transparente/assets/32615/0a42e395-53d5-46eb-a03c-574445855969)

Versão instalada do módulo: 3.18.3
Versão do Magento: 1.9.4
Checkout: Inovarti OSC: 2.0.3

**Comment by r-martins** [comment]
Olá, @mferracioli . Tudo bom?
Notamos que a API antiga do PagBank tem enfrentado problemas com alguns BINs de cartões.
Se possível, teste com outros cartões e me avise se o problema persiste, informando o url da loja em questão (se preferir, faça isso [via chamado](https://pagsegurotransparente.zendesk.com/hc/pt-br/requests/new)).

Infelizmente não temos controle sobre a API antiga, e já abrimos uma investigação com eles sobre o assunto, mas não tivemos retorno até o momento.

👉 **Recomendo que atualize o módulo para [nova geração](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/18319201859469-O-que-%C3%A9-o-PagBank-Connect-e-a-Nova-Gera%C3%A7%C3%A3o)** que utiliza as novas APIs do PagBank e não deverá ter este tipo de problema.
* [Github do novo módulo](https://github.com/r-martins/PagBank-Magento1)
* [Página oficial do novo módulo](https://pagseguro.ricardomartins.net.br/magento1.html)
