### ISSUE TITLE
pedidos cancelados pelo PagSeguro nao voltam com produtos ao estoque

### ISSUE THREAD

**Issue by phdiegues** [r-martins/PagSeguro-Magento-Transparente#33]
Fala Ricardo.
Reparei um probleminha, há duas formas do pedido ser cancelado automaticamente, correto? 
Uma é Pelo PagSeguro e a outra pela instituição bancária.

Acontece que os produtos voltam aos estoque apenas quando é cancelado pela instituição bancária. Quando o próprio PagSeguro cancela os produtos não estão voltando.
Conseguiria, por favor, me ajudar em alguma solução?

Obrigado.

**Comment by rafatriolo** [comment]
Fala Ricardo , tudo bem ? 

Seguinte estou com o mesmo problema do @phdiegues , pois o pagseguro cancelou o pedido, pois o cartão da cliente não passou , só que os produtos não voltaram para o estoque. E quando eu faço o cancelamento manual de qualquer outro pedido , os produtos voltam pro estoque. Tem como me ajudar com isso? 

Abs

Rafael
