### ISSUE TITLE
Problema com Faturas Duplicadas

### ISSUE THREAD

**Issue by deniscsz** [r-martins/PagSeguro-Magento-Transparente#35]
Acontece uma quantidade considerável de vezes: uma segunda fatura está sendo criada, com o valor de R$ 0,00, como se o PagSeguro tivesse enviado uma segunda notificação. Nessa segunda fatura criada, não há produtos faturados (o que justifica o valor de zero reais).

Exemplo de um pedido:
As 03:15 O pedido foi confirmado (state trocado de pending para processing), e a fatura foi criada.
As 04:20 o processo se repetiu.
Isso foi constado observando as mensagens do histórico de comentários geradas pelo próprio módulo.

Como não tenho acesso ao painel do pagseguro, ainda não pude verificar se o retorno de dados também está configurado. Porém analisando o controller controller que recebe as notificações de transações (NotificationController.php) e pela função proccessNotificatonResult, não é feito tratamento de POST de retorno (forma antiga, anterior a API).

Ainda tenho que analisar se há verificação antes de gerar a invoice, e em caso positivo, como é feita.

**Comment by mefornazari** [comment]
estou com o mesmo problema, ALGUMA AJUDA??
