### ISSUE TITLE
Status do pedido retorna à "aguardando" após "confirmar"

### ISSUE THREAD

**Issue by matneves** [r-martins/PagSeguro-Magento-Transparente#42]
Estou com alguns pedidos retornando o estado para "aguardando pagamento", mesmo após ser dado como "pagamento confirmado" pelo próprio pagseguro através do módulo.

Segue foto em anexo.
![captura de tela 2014-09-25 as 14 31 39](https://cloud.githubusercontent.com/assets/2514252/4443095/4cec38c6-47e5-11e4-9795-1724cce146b7.png)

**Comment by marcelloinfoweb** [comment]
Comigo, também, tenho que faturar manual mas depois de conferir no pagseguro!

Alguém com alguma ideia?

**Comment by phdiegues** [comment]
O meu começou com esse problema desde a semana passada também...

**Comment by r-martins** [comment]
Os que testaram a correção, conseguiram sucesso?

**Comment by phdiegues** [comment]
testei e não tive sucesso!

**Comment by artexpressa** [comment]
Aqui sempre foi um problema intermitente, deu uma diminuída boa nas ocorrências mas ainda tem acontecido com um pedido ou outro.

**Comment by r-martins** [comment]
@artexpressa o fluxo de status dos que ainda acontecem, é identico ao anterior ou mudou?

**Comment by phdiegues** [comment]
@r-martins é identico sim, o meu aqui também diminuiu,mas ainda continua com alguns, somente os com cartão.

**Comment by marcelloinfoweb** [comment]
O meu problema voltou, e identifiquei. Na verdade não é um erro e sim uma incompatibilidade com o retorno com domínio em SSL.

Coloquei o domínio em SSL e parou de receber os status do PagSeguro.

Meu módulo esta na versão 1.73 e estava funcionando perfeitamente.

Qual solução posso tomar?

Obrigado!

**Comment by artexpressa** [comment]
Ainda tenho duas situações ocorrendo esse problema.

- Tem pedidos que mesmo aprovados no pagseguro não faturam (tenho que conferir manualmente diariamente todos os pedidos aguardando pagamento no pagseguro e faturar ou cancelar manualmente alguns no magento - isso só acontece com cartão de crédito)

- Tem pedidos que mesmo faturado, o status volta para "aguardando pagamento". Nesse caso pro pedido ficar com status processing, só alterando o status incluindo comentários do pedido.

Num universo da nossa loja que tem de 50 a 100 pedidos por dia, esses problemas acontecem com uns 3 ou 4. O problema é que gera um trabalhão ficar conferindo todos os pedidos manualmente no painel do pagseguro.

**Comment by artexpressa** [comment]
Pessoal, troquei a url de retorno cadastrada no painel do pagseguro para https e parece que resolveu todos os problemas (pelo menos faz 3 dias que não tem acontecido). acredito que seja devido aos acessos https passarem por fora dos caches, indo direto pro webserver.

@r-martins sugere isso no manual de instalação :+1: ou teria algum problema usar dessa forma?

Abs!

**Comment by r-martins** [comment]
@artexpressa dentro do módulo não há distinção nenhuma. E o cache nativo do Magento não afetaria esse retorno, a menos que você tenha algum outro cache, tipo varnish, que esteja configurado pra cachear a url de retorno.

**Comment by artexpressa** [comment]
@r-martins Reduziu mas infelizmente ainda não zerou os problemas. Eu uso nginx e varnish, porém o varnish não cacheia essa parte. Num universo de 500 pedidos acontece com 3 ou 4.

Estou desconfiado que o problema tem relação com a carga do servidor e as respectivas ordens de callbacks da aplicação na comunicação com o pagseguro. Faria algum sentido?

**Comment by mefornazari** [comment]
Comigo está acontecendo o mesmo problema, ele fica faturando o pedido toda hora e alterando o status.. alguma sugestão de como corrigir isso?

**Comment by coringafiles** [comment]
Eu atualizei pra última versão e ainda continuo com o problema de ter que confirmar manualmente em todos os pedidos

**Comment by magnored** [comment]
Vcs usam cloudflare ?


Em 21 de outubro de 2015 11:35, coringafiles <notifications@github.com>
escreveu:

**Comment by coringafiles** [comment]
Eu uso, mas mesmo depois de adicionar a url lá, continua o problema

**Comment by r-martins** [comment]
O problema ainda persiste pra vocês, nas últimas versões?
