### ISSUE TITLE
Incompatibilidade com HHVM 3.2.0 e 3.3.0

### ISSUE THREAD

**Issue by deniscsz** [r-martins/PagSeguro-Magento-Transparente#43]
Apenas utilizando esse canal para avisar de possível incompatibilidade com o HHVM:
https://github.com/facebook/hhvm/issues/3339

A classe Zend_Http_Client parece não está totalmente suportada nas versões atuais do HHVM. Tive o mesmo problema que descrito na issue 3339. Esse é um problema no HHVM e não no módulo, apenas posto aqui para registro de alguém que possa passar pelo mesmo problema.

**Comment by schmite** [comment]
Acabei de testar na versão 3.11.0 do HHVm e está funcionando perfeitamente.
:D
