### ISSUE TITLE
Status dos pedidos

### ISSUE THREAD

**Issue by artexpressa** [r-martins/PagSeguro-Magento-Transparente#46]
Olá,

Seguem algumas dúvidas/possíveis bugs:

Pq alguns pedidos ficam como "pending" e outros como "pending payment"? Qual a diferença real entre os dois status?

Pq a maioria dos pedidos confirmados pelo pagseguro ficam com status "processing e faturado" e uma minoria fica somente "processing não faturado"? A fatura não devia ser pré-requisito para o pedido estar processing? Já enviamos diversos pedidos em duplicidade devido a este bug uma vez que após a entrega o pedido não faturado não para para o status complete :/

**Comment by phdiegues** [comment]
Aqui comigo também acontece. O pedido é pago, o módulo cria a fatura, porém o status do pedido permanece como Novo. segue:

29/01/2015 13:28:48|Aguardando (Novo)
Cliente Notificado  
29/01/2015 13:28:48|Pago
Cliente Sem Notificações 
Valor solicitado de R$427,05.
29/01/2015 13:28:44|Pago
Cliente Não Notificado 
Paga: a transação foi paga pelo comprador e o PagSeguro já recebeu uma confirmação da instituição financeira responsável pelo processamento.
29/01/2015 13:28:44|Pago
Cliente Não Notificado 
Fatura #100006504 criada com sucesso.
29/01/2015 13:28:37|Pago
Cliente Sem Notificações 
1
29/01/2015 13:28:34|Pendente
Cliente Não Notificado 
Aguardando pagamento: o comprador iniciou a transação, mas até o momento o PagSeguro não recebeu nenhuma informação sobre o pagamento.
29/01/2015 13:28:31|Pendente
Cliente Sem Notificações 
1

**Comment by phdiegues** [comment]
Acabei de notar também que quando o pedido é cancelado pelo Pag Seguro o produto não está voltando ao estoque.

**Comment by renancfc** [comment]
Olá Ricardo, tudo bem?

Estou tendo o mesmo problema com a mudança de status na minha loja. Já coloquei os caminhos que indicou no pagseguro mais na minha loja sempre fica como "Processando". Pode me ajudar a resolver esse problema. Abraços e parabéns pelo módulo.

**Comment by r-martins** [comment]
Foi corrigido na 2.0.4. Se alguem usa o PRO, poderia entrar em contato comigo pra testar a correcao?

**Comment by phdiegues** [comment]
Eu uso o PRO

**Comment by phdiegues** [comment]
ph@bigartesanato.com.br

**Comment by phdiegues** [comment]
Na verdade acho que meu e-mail que negociamos foi o bigartesanato@gmail.com

**Comment by gilmr** [comment]
Olá, pelo magento connect não está disponível a atualização para o 2.0.4., vai ser atualizado por lá ou só por ftp?

**Comment by r-martins** [comment]
@phdiegues eu mandei no primeiro email
@gilmr estará no magento connect em breve. Por enquanto só no github mesmo. Até quarta ou quinta estará ok.

**Comment by phdiegues** [comment]
no meu caso não resolveu o problema ainda 
![20150406_092444](https://cloud.githubusercontent.com/assets/6341299/7004272/4b7327b8-dc3f-11e4-8bc8-bfc29b4a3131.jpg)

**Comment by r-martins** [comment]
Atualizou os dois módulos?

Sent from my Android.
Em 06/04/2015 9:31 AM, "phdiegues" <notifications@github.com> escreveu:

**Comment by renancfc** [comment]
Amigos, encontrei uma forma que talvez possa ajudar a todos. Comigo até o momento resolveu.
Em admin  » Sistema » Status do Pedido
Nessa tela estão todos os status do pedido. Por padrão já vem alguns configurados pelo sistema. No meu tem também o pagseguro. Você pode ajustar alguns e definir como padrão (clicando em atribuir status ao estado). Como ele estava pegando os status padrão do sistema eu renomeei o que estava sendo exibido para mim e configurei outros. 
Onde estava em "processing" eu coloquei "pago" e "pending_payment" eu coloquei "aguardando pagamento" entre outros. Não tive problemas porque processing só era exibido quando o pagamento era confirmado. 

Espero ter ajudado.

Abs

**Comment by r-martins** [comment]
É isso mesmo Renato

Sent from my Android.
Em 07/04/2015 12:03 PM, "renancfc" <notifications@github.com> escreveu:
