### ISSUE TITLE
Atualizar o pagamento ao mudar o frete ou endereço no OPC

### ISSUE THREAD

**Issue by MatNeves** [r-martins/PagSeguro-Magento-Transparente#47]
Como no one page checkout é possível alterar o frete, endereço ou outros dados, acho importante colocar um refresh nas parcelas, ou apresentar uma documentação para fazer isso manualmente, já que existem outros vários tipos de checkouts. Note que é necessário ser uma função que possa ser chamada de "qualquer" lugar do magento.

**Comment by r-martins** [comment]
O desafio nesse caso seria encontrar um evento do javascript que fosse padrão pra todos os checkouts, o que eu não consegui encontrar.
As parcelas só conseguem ser calculadas quando temos a bandeira e o valor total do pedido.
O médoto RMPagSeguro.getInstallments(); faria isso.
Outra abordagem seria limpar algum dos campos do cartão nessa atualização, forçando o usuário a preencher novamente, o que imagino dispararia novamente o evento da atualização das parcelas.

**Comment by aleraniere** [comment]
Olá a todos,
Alguma solução para esse erro? 
Uso o OSC Brasil6. Tenho a forma de pagamento depósito bancário com desconto.
Clicando primeiro nela, o desconto vai para o carrinho.
Clicando depois no cartão e inserindo o número, a parcela fica com desconto, pois o valor do desconto continua no carrinho.
Agora quando clicamos em boleto bancário (pagseguro), o desconto do carrinho é removido, ficando o valor correto.
A pergunta: Porque  boleto atualiza o preço no carrinho e no cartão não?
Obrigado!

**Comment by tiagoexe** [comment]
Galera, boa tarde!

eu paguei $300 dolaras hoje por esta correção, não tive saida!
se alguém quiser dividir essa despesa comigo eu envio o arquivo corrigido.

abs

**Comment by magnored** [comment]
Vc conseguiu resolver tiagoexe ?

Estou com o mesmo problema, comecei a usar a extensao hj ... =/

**Comment by magnored** [comment]
quando achei q estava tudo resolvido..tive outro problema

o que acontece eh o seguinte...com o fix:

<script type="text/javascript">
        $j = jQuery.noConflict();
        $j(document).ready(function(){
        if($j('#p_method_pagseguro_cc').is(':checked')){
        if(typeof PagSeguroDirectPayment != "undefined" && PagSeguroDirectPayment.ready){
        RMPagSeguro.getInstallments();
        }
     }
});
</script>

no arquivo totals, ele até atualiza as parcelas, porem, qdo a pessoa tenta clicar em outra parcela (por exemplo 3x) o codigo recalcula tudo e volta sempre para 1x

**Comment by tiagoexe** [comment]
magnored contratei um programador que resolveu o problema.

**Comment by magnored** [comment]
@tiagoexe passa o contato no meu email magnored@gmail.com ou fala vc comigo caso tenha interesse em rachar o custo...abs

**Comment by LBCorr** [comment]
Desculpa a demora pessoal, ainda estou em localhost e como eu disse, meu osc é diferente, então a solução pode variar...
No caso da aleraniere creio que o problema não é no módulo e sim no osc, provavelmente você precisa atualizar as formas de pagamento ao alterar, no meu caso tive que fazer isso, é chato porque toda vez que muda a forma de pagamento eles atualizam, mas foi a única maneira que achei de calcular os descontos sem problemas, meu código (no final de onepagecheckout\onepage\payments\methods.phtml) é:

<?php $paymentMethodUsed = Mage::getSingleton('checkout/session')->getQuote()->getPayment()->getMethodInstance()->getCode(); ?>
       <script type="text/javascript">
       $j = jQuery.noConflict();
	  $j(function($) {
      $j(document).ready(function(){
		  	  var ls_pmet = "<?php echo $paymentMethodUsed; ?>";
		  	  var ls_pmetb = $("input:radio[name*='payment[method]']:checked" ).val();
			if (ls_pmetb != ls_pmet) {
                        checkout.update({
                  		'review': 1,
					})
            }
			})
            });
    </script>

**Comment by LBCorr** [comment]
desculpa, abaixo do php o script:

       $j = jQuery.noConflict();
	  $j(function($) {
      $j(document).ready(function(){
		  	  var ls_pmet = "<?php echo $paymentMethodUsed; ?>";
		  	  var ls_pmetb = $("input:radio[name*='payment[method]']:checked" ).val();
			if (ls_pmetb != ls_pmet) {
                        checkout.update({
                  		'review': 1,
					})
            }
			})
            });

**Comment by LBCorr** [comment]
no caso do magnored  você diz aparecer as parcelas no totals? No caso de juros etc, atualizar o valor total? Se for, eu realmente nem tentei mexer nessa parte ainda, no meu caso o total permanece o valor normal, só no módulo mostro as parcelas, se for esse o caso me avise que posso procurar um jeito de mostrar no totals....

**Comment by LBCorr** [comment]
Pessoal, fiz mais uma alteração que pode melhorar a seleção. Quando a pessoal mudava o frete, no meu caso, atualizava o valor das parcelas, mas selecionava sempre em 1x. Ou seja, se o cliente escolhe pagar em 5x e depois muda o frete, alteraria para 1x e ele poderia concluir sem perceber, no meu caso, em pagseguro.js logo abaixo de RMPagSeguro.getInstallments = function(){ adicionei:

    var pag_sel =jQuery( "select#pagseguro_cc_cc_installments option:selected").val();
    if(pag_sel != ''){
    var pag_selb = ((abc.charAt(0))-1);
    }

e logo abaixo de parcelsDrop.add(option); adicionei:

if(pag_sel != ''){
                       jQuery('select#pagseguro_cc_cc_installments>option:eq('+pag_selb+')').attr('selected', true); //atualiza parcela selecionada
                       }


o script detecta as parcelas selecionadas antes de atualizar, da update no valor e seleciona a parcela que estava. Não sei se ajuda, mas comentem se funcionou com vocês.. Abraço

**Comment by magnored** [comment]
@lbcorr, o q acontecia comigo após o fix era exatamente o bug de 1x na parcela....ele calculava o valor certo mas sempre voltava com 1x... Eu nao to com o note agora para testar....mas tem um camarada freela tentando fazer um POST ao clicar na opcao CARTAO DE CREDITO...de qualquer forma amanha eu vou fazer um teste e vou dando um feedback aqui

**Comment by LBCorr** [comment]
magnored se é só esse o problema usando o código acima no pagseguro.js já resolve, ele volta pra parcela selecionada antes de atualizar, se der certo me avisa, qualquer coisa só chamar

**Comment by LBCorr** [comment]
Desculpa denovo, os testes estavam com abc etc... então vamos ao código final funcionando:

Em pagseguro.js logo abaixo de RMPagSeguro.getInstallments = function(){ adicionei:

var pag_sel =jQuery( "select#pagseguro_cc_cc_installments option:selected").val();
    if(pag_sel != ''){
    var pag_selb = ((pag_sel.charAt(0))-1);
    }

depois, abaixo de parcelsDrop.add(option); adicionei:

if(pag_sel != ''){
                       jQuery('select#pagseguro_cc_cc_installments>option:eq('+pag_selb+')').attr('selected', true); //atualiza parcela selecionada
                       }

**Comment by davidbedore** [comment]
Boa tarde a todos!

Vi os tópicos aqui e estou com o mesmo problema.
Uso OSC Brasil 6 do Deivison e o PagSeguro Transparente do Ricardo Martins. Ambos muito bons!

Porém, em meu caso, ao chegar a página de checkout, com o endereço selecionado e com a forma de entrega também selecionada e preencher os dados do cartão de crédito, tudo correto. 

Porém se eu alterar o endereço selecionado, a forma de entrega, ou se no final do pedido eu incluir um cupom de desconto e calcular o desconto, a forma de pagamento recarrega novamente com os dados do cartão preenchidos, mas o parcelamento fica com a mensagem inicial: "Informe os dados do cartão para calcular".

E percebi que ele só calcula o novo valor do parcelamento quando eu apago o nº do cartão, saio do campo Número do Cartão de Crédito, volto novamente para o campo e entro com nº do cartão outra vez.

Não sei se mais alguém tem este mesmo problema. Fiz as alterações que o @MatNeves e o @lbcorr sugeriram, mas infelizmente não funcionou para mim.

Quando alterar a forma de entrega, endereço ou utilizar o cupom de desconto ele recalcular ou recarregar com os dados corretos, segundo as alterações?

Se alguém puder ajudar eu agradeço.

Obrigado!

**Comment by diegoborba** [comment]
@davidbedore Conseguiu evoluir algo a respeito?

Estou enfrentando problema similar.

**Comment by r-martins** [comment]
@davidbedore,
Experimente acrescentar o codigo abaixo no final do cc.phtml do modulo:
```
<script type="text/javascript">
//<![CDATA[
    RMPagSeguro.getInstallments();
//]]
</script>
```
Vou realizar mais alguns testes em outros cenarios e se der tudo ok, subo com isso na proxima versão.
Sobre os demais casos, não vejo uma forma genérica de resolver o problema. Cada checkout e cada modulo trazem eventos diferentes que atualizam o total, e que muitas vezes não atualizam o bloco de pagamento.
De qualquer forma, documentei isso em https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/206609375.

Se alguém tiver alguma ideia melhor, é só re-abrir ou fazer um pull request.
E senhores, Muito Obrigado pelas contribuições até aqui.

**Comment by mefornazari** [comment]
Alguém conseguiu resolver? Já tentei tudo que foi falado aqui e nada.. :(

**Comment by tavinus** [comment]
Esse último código do @r-martins resolveu o problema do "Informe os dados do cartão para calcular" (igual o do @davidbedore). Mas infelizmente o total do carrinho não recebe o valor dos juros das parcelas, embora ele seja recarregado quando algum parcelamento é selecionado. O Hack de salvar as parcelas pra reexibir não funcionou pra mim.

Se eu desligo o OSC o total do pedido também não recebe o valor do juros, mas como ele mostra a informação do passo anterior, dá pra ver que ele salvou o valor da parcela e dos juros. Mas o total, nada.

Acho que vou tentar atualizar o módulo do PagSeguro. Acha que pode resolver? Pra atualizar tem algum procedimento especial? Basta instalar? Precisa desinstalar?

Por padrão o magento não mostra mesmo o total com os juros do pagseguro?

**Comment by r-martins** [comment]
O módulo mostra o total no drop das parcelas, não no total do carrinho.
Isso é  normal, pois o seu relatório não deve constar o valor dos juros.

Sent from my Android.
Em 5 de abr de 2016 6:51 AM, "tavinus" <notifications@github.com> escreveu:

**Comment by tavinus** [comment]
É então. Eu percebi isso. Vou fazer alguma modificação pra informar o cliente. Algo como uma seção extra no REVIEW informando o valor das parcelas e o total, com a mensagem: Parcelamento pelo PagSeguro UOL, ou algo assim. Pois do jeito atual o cliente não consegue ver o total que ele vai pagar em nenhum momento, somente o valor das parelas com juros.

Vou tentar debugar o JS do hack de recarregar as parcelas também. Lembro que joguei as vars salvas no log e elas estavam sempre em branco. Mas os nomes dos elementos batiam com os do script. Talvez seja algum problema com o JQuery, não sei.

**Comment by diegoborba** [comment]
@tavinus, deixei essa informação direto no lugar das parcelas. E não tenho problemas disso com meus clientes. 

![image](https://cloud.githubusercontent.com/assets/868495/14412773/7e97f87e-ff40-11e5-8408-c5aa460d5927.png)

**Comment by tavinus** [comment]
@diegoborba Sim, foi basicamente o que eu fiz também. Inseri o total direto no form e coloquei um texto informando que o total deles não compõe o total da loja. Essa imagem dos cartões é versão nova ou você quem fez? Ficou legal.

**Comment by fchiqueto** [comment]
Olá @diegoborba você poderia passar como foi feito o total parcelado com juros no drop para vir em uma atualização se o @r-martins aprovar a ideia? Ou postar aqui para gente, tive problemas com um cliente e não consegui colocar isso em minha loja :(

**Comment by tavinus** [comment]
Não é difícil. Eu atualizei o módulo hoje e tive de refazer.
Basicamente basta adicionar uma linha no arquivo `js/pagseguro/pagseguro.js`, na função `RMPagSeguro.getInstallments`.
**Antes:**
`                    option.text = b[x].quantity + "x de R$" + b[x].installmentAmount.toFixed(2).toString().replace('.',',');
                    option.text += (b[x].interestFree)?" sem juros":" com juros";
                    option.value = b[x].quantity + "|" + b[x].installmentAmount;
                    parcelsDrop.add(option);`
**Depois:**
`                    option.text = b[x].quantity + "x de R$" + b[x].installmentAmount.toFixed(2).toString().replace('.',',');
                    option.text += (b[x].interestFree)?" sem juros":" com juros";
                    option.text += b[x].quantity > 1 ? " | Total R$ " + b[x].totalAmount.toFixed(2).toString().replace('.',',') : "";
                    option.value = b[x].quantity + "|" + b[x].installmentAmount;
                    parcelsDrop.add(option);`
No caso eu usei, "|" pra separar, ao invés de "-".

Pra adicionar um texto informando ou mesmo aumentar o tamanho do select de parcelas você precisa mudar o arquivo `app/design/frontend/base/default/template/ricardomartins_pagseguro/form/cc.phtml`. Eu adicionei um `<p>` depois do select do cartão (procure por `_cc_installments_div`.

**Comment by fchiqueto** [comment]
Valeu @tavinus funcionou certinho aqui muito obrigado! Acredito que deveria vir em uma atualização com opção de ativar ou não, aqui uso o OSC 6 e não deu problema :)

**Comment by tavinus** [comment]
Legal que você conseguiu!
Agora estou com o antigo problema de não atualizar o valor quando muda a forma de pagamento. O lance é que dependendo da sequência ele não atualizava as parcelas do pagseguro, mesmo que atualizasse a revisão do pedido. 

Um exemplo que consegui reproduzir diversas vezes foi selecionar boleto (10% desconto) de primeira, ele aplica o desconto. Aí você muda pra cartão e coloca um número de cartão inválido mas que reconhece (ex: 5454545454545454 - master) ele vai calcular as parcelas erradas, com base no preço com desconto. Aí depois você preenche todos os dados corretos do cartão. Ele vai atualizar a review.phtml mas não vai mudar o valor das parcelas do pagseguro.

No fim, coloquei o código da cc.phtml que chama `RMPagSeguro.getInstallments();` na `app/design/frontend/base/default/template/onestepcheckout/onestep/form/review/cart/totals.phtml`. Fiquei pensando se só chamo ele ou uso a checagem `if ('undefined' !== typeof RMPagSeguro)`. Também fiquei pensando se não devia remover da cc.phtml pra não rodar 2 vezes.

Parece resolver, apesar de demorar de 1 a 2 segundos pra repopular as parcelas do pagseguro depois que atualiza a review.phtml e de rodar isso sempre que atualiza a review.

Mas como sou teimoso vou continuar procurando como fazer atualizar a review ao se clicar na opção de pagamento de cartão do pagseguro (não somente depois de digitar dados corretos do cartão). Já tentei tudo aqui nesse post algumas vezes sem sucesso. Pior de tudo é que mesmo com o onestepcheckout desligado, se voce selecionasse boleto e depois voltasse atrás, também dava o mesmo problema. engraçado que qualquer outra opção ele muda tudo na hora, mas as estas outras não tem formulário pra preencher.

Uma coisa que eu realmente queria saber é qual evento ou função dispara a atualização da review.phtml e/ou do carrinho em geral. Bastaria chamar isso quando o radio do pagseguro fosse clicado. Mas não acho por nada. Ou se desse pra mandar o `RMPagSeguro.getInstallments()` fazer a mesma coisa que ele faz ao receber todos os dados de cartão válidos (mas sem pegar as parcelas, só atualizando o valor total do carrinho na review).

Porque da forma que eu vejo, o `RMPagSeguro.getInstallments()` só vai atualizar algo se tiver dados de cartão válidos. Se não, não faz nada. E o que precisa é justamente que ele atualize sem dados preenchidos, ao se clicar na opção. E veja bem, ele precisa atualizar o carrinho somente, não os installments (esses sim só podem ser calculados depois dos dados do cartão mesmo). 

Talvez a lógica fosse pro `getInstallments()` atualizar a review se não tiver dados de cartão, ou tudo se tiver (execução normal). Cansado..

**Comment by tavinus** [comment]
Bom, primeiro desculpa o double-post mas é muita coisa pra anexar ali em cima.

Continuo tentando e estudando esse problema da review no checkout. Lembrando que eu tive problemas com isso mesmo com o OSC desligado, se o cliente voltasse alguns passos. Chamar o `RMPagSeguro.getInstallments()` na review.phtml usada resolve uma boa parte do problema, mas nem sempre e nem todos.

Aliás respondendo minha própria pergunta, sim, o ideal é rodar com a checagem `if ('undefined' !== typeof RMPagSeguro)`, pois vai falhar de qualquer jeito se ela for falsa. E agora que travei o gradTotal do pagseguro (leia abaixo), comentei a chamada de cc.phtml e deixei somente na review.phtml.

Eu digo que nem sempre resolve porque testei bastante e em alguns casos eu insisti em ficar mudando as opções do checkout, dados de cartao, etc e em algum momento ficava os valores do desconto no menu de parcelas do pagseguro.

E digo que nem todos pois o checkout continua mostrando o preço errado até que todos os dados do cartão sejam inseridos.

Eu gastei um bom tempo no github do OSC também, tentando coisas que foram postadas lá. Pretendo inclusive atualizar meu módulo, mas preciso extrair ele e fazer um diff com o original pra ver se algo foi mudado. De qualquer forma eles introduziram patches pra ajudar no reload e uma função pra forçar o SavePayment. Mas como foi dito lá, isso não resolve em muitos casos de formas de pagamentos com formulários com campos requeridos. Só vai atualizar o valor do checkout quando tudo for válido no formulário do cartão mesmo. Tentei dezenas de coisas, nada muito bom até agora.

**No fim, eu "resolvi" resolver o problema na raiz. **
Fiz um hack no arquivo `app/code/community/RicardoMartins/PagSeguro/controllers/AjaxController.php`, substituindo a função `getGrandTotalAction()`. Na real eu mudei o nome dela pra `getGrandTotalActionOld()` e depois comentei. 

Mas sim, estou fazendo ela enviar o valor grandTotal sem o desconto pra API do pagseguro. Claro que tem o problema de que se eu quiser dar descontos, não vou conseguir. Mas no caso meu problema é inverso, não quero descontos ali e às vezes vai. Como já estou pagando 3 meses dos juros, o preju é grande se for com 10% de desconto. Sempre dá pra inverter a função no arquivo também, voltando a original.
```php

    /**
     * Returns the order grand total without discounts, used to get installments of CC method
     */
    public function getGrandTotalAction()
    {
        $quote              = Mage::helper('checkout/cart')->getQuote();
        $grandTotal         = $quote->getGrandTotal();
        $quote_data         = $quote->getData();
        //$base_subtotal      = $quote_data['base_subtotal'];
        $subtotal           = $quote_data['subtotal'];
        //$base_subtotal_disc = $quote_data['base_subtotal_with_discount'];
        $subtotal_disc      = $quote_data['subtotal_with_discount'];
        
        $disc_diff = (double)$subtotal - (double)$subtotal_disc;
        if ($disc_diff !== 0) {
            $grandTotal = $grandTotal + $disc_diff;
        }

        $this->getResponse()->setHeader('Content-type', 'application/json', true);
        $this->getResponse()->setBody(json_encode(array('total'=>$grandTotal)));
    }
```
Assim, mesmo que o carrinho esteja errado, ele sempre recebe o valor "certo" pro calculo das parcelas.

Uma coisa que eu tentei sem sucesso foi fazer o módulo do pagseguro carregar um cartão "dummy" logo de início (Dados semi-validos) e pegar um token com isso, permitindo atualizar o valor do carrinho. Aí se tem dados válidos no form usa o token certo, se não usa o dummy. Claro que ele vai carregar parcelas pra uma bandeira específica, mas tudo bem, pega Visa/Master e boa.

Porque com os dados preenchidos ele atualiza normal se troca a forma de pagamento. E se eu apago somente alguns campos, muitas vezes também mudava o valor do carrinho normal na review. Mas anda ainda e nem sei se pode isso, mas julgando que ele faz calls a cada preenchimento de form, acho que 1 a mais no começo, seria ok.

Te falar que eu nem sei o que fiz que a review tá atualizando até quando muda de campo no form dos cartões, mas o desconto não sai, obviamente. Preciso desligar isso, só carrega a toa.

Enfim, se alguém quiser fixar o valor total do pagseguro tá aí o código.

**Comment by tiagoexe** [comment]
Hi,

I've just read some interesting news about our friend, just look at him, he is a star! Please read here <http://frabuntufri.nycpod.com/lnozb>

Kind regards, tiago@tiagomartins.com.br

**Comment by tiagoexe** [comment]
Yo! 

I've got some news for you, please read  it, this really matters a lot! Please read  here <http://gostidaqui.bradhenson.com/lnkcv>

Rushing, tiago
