### ISSUE TITLE
Após realizar pedido com Boleto, o pedido não é listado na lista de pedidos

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#50]
Nos pedidos de boleto ou transferência o comum é ele permanecer em segurado até o cliente realizar o pagamento e isso ser comprovado pelo PagSeguro, porém o pedido segurado não aparece na listagem do cliente, no admin dele. Eu não acredito que seja um erro no template, já que puxei o collection de pedidos na marra e mesmo assim a página especifica do pedido retorna para o history.

Reportado por Mateus Neves.

**Comment by phdiegues** [comment]
também tenho este problema Ricardo, poderia me enviar, por favor?

**Comment by phdiegues** [comment]
também adquiri o modulo Pro

**Comment by r-martins** [comment]
@MatNeves, funcionou pra você?
@phdiegues pode mandar por chamado? Não lembro seu e-mail.

**Comment by phdiegues** [comment]
bigartesanato@gmail.com
