### ISSUE TITLE
Falha ao processar pagamento junto ao PagSeguro...

### ISSUE THREAD

**Issue by tainazao** [r-martins/PagSeguro-Magento-Transparente#61]
Olá esse é meu primeiro post, desculpas antecipadas pela inexperiência.

Estou com problemas na hora de finalizar o pedido pelo PagSeguro Transparente em minha loja. A loja retorna uma mensagem que está em anexo no print. Sobre a loja:

* Loja 1.9.0.1
* Chechout OSC 6 do Deivdson
* Tema SNS Nazic
* Link: cvidaskateshop.com.br
* refiz a instalação 3x com o mais atual do github limpei todos os caches e atualizei os indices =/
* O token está funcionando de acordo com link: http://r-martins.github.io/PagSeguro-Magento-Transparente/faq/
* O LOG está retornando  **Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário.**

Não sei se tem a ver, mas minha loja foi instalada na raiz do meu "public_html" porém é sempre reescrito /index.php na barra de endereços. Já tive problemas com plugin da OSC 6 Brasil onde a validação não funcionava, portanto inspecionando a página coloquei o /index.php/ antecedendo os arquivos de validação e funcionou. Fiz algo similar no Pagseguro. JS pra me retornar o session ID do consumidor que não estava retornando, segue abaixo alteração na linha 154:

```
RMPagSeguro.updateSessionId = function() {
       var _url = RMPagSeguroSiteBaseURL + '/index.php/pseguro/ajax/getSessionId';
        new Ajax.Request(_url, {
            onSuccess: function (response) {
                var session_id = response.responseJSON.session_id;
                PagSeguroDirectPayment.setSessionId(session_id);
            }
        });
    }
```

Isso consertou o problema do session ID do consumidor, ao executar no browser ele me retornava um ID, só que agora está dando esse erro conforme foto abaixo:

![erro](https://cloud.githubusercontent.com/assets/10166384/5412032/aef10b3e-81ef-11e4-8ee0-b513643df9e2.png)

![erros](https://cloud.githubusercontent.com/assets/10166384/5412136/b00e25a0-81f0-11e4-917e-d9cc1049fbef.JPG)

exception.log
```
2014-12-12T16:34:40+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Falha ao processar pagamento junto ao PagSeguro. Por favor, entre em contato com nossa equipe.' in /home/cvida/public_html/app/Mage.php:595
Stack trace:
#0 /home/cvida/public_html/app/code/community/RicardoMartins/PagSeguro/Model/Payment/Cc.php(87): Mage::throwException('Falha ao proces...')
#1 /home/cvida/public_html/app/code/core/Mage/Sales/Model/Quote/Payment.php(160): RicardoMartins_PagSeguro_Model_Payment_Cc->validate()
#2 /home/cvida/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(631): Mage_Sales_Model_Quote_Payment->importData(Array)
#3 /home/cvida/public_html/app/code/community/Inovarti/Onestepcheckout/controllers/AjaxController.php(240): Mage_Checkout_Model_Type_Onepage->savePayment(Array)
#4 /home/cvida/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Inovarti_Onestepcheckout_AjaxController->savePaymentMethodAction()
#5 /home/cvida/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('savePaymentMeth...')
#6 /home/cvida/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /home/cvida/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/cvida/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /home/cvida/public_html/index.php(87): Mage::run('', 'store')
#10 {main}
```
Qualquer ajuda é bem vinda, obrigado!

**Comment by marquinhusgoncalves** [comment]
módulos pagseguro transparente e o OSC e estou tendo problemas ao digitar o CEP ele carrega os outros módulos com valores porém ele não carrega o ato preenchimento do endereço fica carregando ai tenho que digitar manualmente porém a bolinha continua girando e ao fechar o pedido ele da erro no e-mail do Sandbox pedindo um e-mail válido sendo que usei o mesmo do sandbox e tb pede o CPF mesmo eu digitando dizendo que é obrigatório.
A msg no log é Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualização de blocos via ajax nao se preocupe.
Fiz os testes com os módulos do Correios e do Pedro Teixeira.
Não usei nenhum outro módulo e também não estou usando nenhum plugin, versão 1.7.0.2

**Comment by marcelloinfoweb** [comment]
Resolvi um problema parecido, que resultou na resolução de outros e assim funcionando tudo direitinho. Fiz o seguinte: Usei o Firefox e uma extensão chamada HttpFox e percebi que estava chamando um arquivo em httpS sendo que na loja que administro é toda em http.
[SOLUÇÃO] Fui no backend da loja e troquei a URL SEGURA, retirando o httpS e substitui por http sem o "S".
Espero que resolva.

**Comment by marquinhusgoncalves** [comment]
marcelloinfoweb fiz a verificação e ela já estava sem o "s" muito obrigado pela resposta. Se tiver mais alguma sugestão pode mandar direto no meu e-mail marquinhusgoncalves@hotmail.com.
Obrigado.

**Comment by r-martins** [comment]
@marquinhusgoncalves o problema do e-mail valido no ambiente Sandbox ocorre, pq ao realizar testes neste ambiente, o e-mail do cliente(comprador) deve ser qualquercoisa@sandbox.pagseguro.com.br.

@marcelloinfoweb o ideal é que seja tudo feito dentro de https. Alguns erros as vezes acontecem quando há elementos não-https dentro da pagina https. Ex: imagens, js, css, etc que não estão com https.

**Comment by cassolatto** [comment]
Eu tenho o mesmo erro, estou pastando aqui pra conseguir achar uma solução, habilitei o log, mas nada acontece, tento processar e ele dá esta mensagem?

Falha ao processar pagamento junto ao PagSeguro

Preciso muito corrigir isso, mas sou newbie no assunto, peço a ajuda de vocês !

Obrigado.

![image](https://cloud.githubusercontent.com/assets/17692639/15275614/b17ab94e-1aa6-11e6-917d-f69319d41df2.png)
