### ISSUE TITLE
Script de validação do cartão não é executado

### ISSUE THREAD

**Issue by marcelodearaujopedro** [r-martins/PagSeguro-Magento-Transparente#62]
Ao digitar o numero do cartão, não está sendo executado o script de validação do cartão, que informa qual bandeira que é, e em seguida mostra o valor parcelado atualizado... O que pode ser?

**Comment by marcelloinfoweb** [comment]
Comigo mostra a mesma mensagem. Não valida cartão e nao atualizar ou mostra pasrcelas.

**Comment by portuga86** [comment]
Você foi convidado!

No Airbnb você pode descobrir lugares únicos no mundo inteiro para se hospedar com anfitriões locais.


Basta se cadastrar até 21 de Julho de 2015 para receber um desconto de R$ 79 em sua primeira viagem de R$ 237 ou mais.





Aceitar convite
http://www.airbnb.com.br/c/mpedrodewes?eluid=0&email=reply%2b009b35aa4fe158c84fdcc7c1a63ab77dcb922a544ffa71f492cf0000000110a445ac92a169ce03177168%40reply.github.com&euid=f4adc4ec-e756-2d1d-4b48-981cc111933b&ri=23737973&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA5YjM1YWE0ZmUxNThjODRmZGNjN2MxYTYzYWI3N2RjYjkyMmE1NDRmZmE3MWY0OTJjZjAwMDAwMDAxMTBhNDQ1YWM5MmExNjljZTAzMTc3MTY4QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiJmNGFkYzRlYy1lNzU2LTJkMWQtNGI0OC05ODFjYzExMTkzM2IifQ==&mac=zFhL_02k2RBAyTXj5gHJ53-Y5aM=

### Airbnb ###
