### ISSUE TITLE
Shipping address number invalid length

### ISSUE THREAD

**Issue by arnonsoares** [r-martins/PagSeguro-Magento-Transparente#64]
Olá,

Quando o cliente tenta realizar a compra no meu site, aparece a seguinte mensagem:

"Problemas ao processar seu pagamento. shipping address number invalid length: Rua Ernesto Pasqualucci(53027)"

E o cliente não consegue prosseguir com a compra. 
Como resolver esse problema?

Obrigado,
Arnon Soares.

**Comment by r-martins** [comment]
Olá @arnonsoares,
Parece que vc mapeou o campo de número do endereço apontando para o campo da rua.
O campo Rua, Numero, Complemento e Bairro devem ser campos distintos.
