### ISSUE TITLE
Problemas ao processar seu pagamento.

### ISSUE THREAD

**Issue by marcelloinfoweb** [r-martins/PagSeguro-Magento-Transparente#66]
Aparece esse erro no Magento 1.7: Problemas ao processar seu pagamento. invalid transactionCode value:  notifications(13003)

**Comment by r-martins** [comment]
Parece ser vestigio de outro modulo do PagSeguro ou configuração da conta e url de retorno no pagseguro.

**Comment by fabiofermo** [comment]
Olá Ricardo, estamos enfrentando uma situação similar, contudo não é constante. Em alguns pedidos temos esse retorno.

**Comment by r-martins** [comment]
Se conseguir me ajudar a simular o problema, posso tentar ajudar...
Do contrário, é como se o Pagseguro enviasse um código de notificação inválido pra sua loja/e-mail configurado no módulo...
