### ISSUE TITLE
Atualização Automática do Status do Pedido

### ISSUE THREAD

**Issue by EdRolla** [r-martins/PagSeguro-Magento-Transparente#67]
Oi, Ricardo!

Cara, primeiro de tudo, parabéns pelo trabalho. Está FENOMENAL!!!

Dei uma lida na sua documentação e estou apanhando um pouco aqui na última parte. Mata uma dúvida rápida? A notificação automática enviada pelo PagSeguro muda automaticamente o status do pedido no backend? 

Pergunto isso pois, a notificação chega normalmente e um comentário é adicionado ao histórico do pedido. Mas, o status permanece inalterado. Não consegui achar nada de errado nas minhas configurações e tudo parece estar correndo bem nos logs....

Obrigadão pela força!

Forte abraço,
Ed

**Comment by r-martins** [comment]
Oi @EdRolla 
Obrigado pelos comentários.

Sim, a notificação volta e altera o status do pedido conforme configurado no admin nas configurações do modulo.

Abraços.

**Comment by EdRolla** [comment]
Muito obrigado pelo retorno, Ricardo!

Alguma sugestão sobre o que pode estar ocorrendo para o status dos pedidos não estarem sendo alterados?

Abraço!
