### ISSUE TITLE
Desinstalar completamente o módulo

### ISSUE THREAD

**Issue by robsonolivesa** [r-martins/PagSeguro-Magento-Transparente#68]
Boa tarde!

Fiz a instalação do módulo, porém o pagseguro está demorando para liberar o checkout transparente. Eu instalei o módulo oficial do pagseguro porém creio que esteja em conflito pois não está funcionando (dando forbidden). Quando eu desinstalo pelo magento connect e instalo o modulo oficial, ele aparece com as informações do módulo que não é o oficial e que ja foi desistalado.

Alguém pode me ajudar a limpar completamente pra ver se o do pagseguro funciona?

Obrigado
Robson

**Comment by r-martins** [comment]
Oi @robsonolivesa 
Para remover meu modulo basta remover os arquivos que adicionou dele. A lista você encontra aqui no github mesmo clicando em "code" nos icones laterais.
Ou pode simplesmente desabilitar ele completamente alterando de true para false no arquivo app/modules/RicardoMartins_*.xml.

Grande abraço e boas vendas.

**Comment by LHD2000** [comment]
Olá, eu desinstalei o módulo e agora o backend e o frontend estão inacessíveis!!!
o log gerou a seguinte mensagem:
a:4:{i:0;s:80:"Module "RicardoMartins_PagSeguroPro" requires module "RicardoMartins_PagSeguro".";i:1;s:905:"#0 /var/www/html/meusite.com.br/web/loja/app/code/core/Mage/Core/Model/Config.php(849): Mage::throwException('Module "Ricardo...')
#1 /var/www/html/meusite.com.br/web/loja/app/code/core/Mage/Core/Model/Config.php(812): Mage_Core_Model_Config->_sortModuleDepends(Array)
#2 /var/www/html/meusite.com.br/web/loja/app/code/core/Mage/Core/Model/Config.php(315): Mage_Core_Model_Config->_loadDeclaredModules()
#3 /var/www/html/meusite.com.br/web/loja/app/code/core/Mage/Core/Model/App.php(405): Mage_Core_Model_Config->loadModules()
#4 /var/www/html/meusite.com.br/web/loja/app/code/core/Mage/Core/Model/App.php(336): Mage_Core_Model_App->_initModules()
#5 /var/www/html/meusite.com.br/web/loja/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#6 /var/www/html/meusite.com.br/web/loja/index.php(80): Mage::run('', 'store')
#7 {main}";s:3:"url";s:16:"/loja/index.php/";s:11:"script_name";s:15:"/loja/index.php";}

O que eu faço agora???? por favor me ajude!!!!

**Comment by r-martins** [comment]
Voce desinstalou apenas o modulo principal e manteve o Pro.

**Comment by LHD2000** [comment]
na verdade eu fiz a desinstalação pelo downloader, só havia um instalado e eu usei o uninstall!!!

 

A versão do magento é a 1.6

 

De: Ricardo Martins [mailto:notifications@github.com] 
Enviada em: quarta-feira, 6 de maio de 2015 16:00
Para: r-martins/PagSeguro-Magento-Transparente
Cc: LHD2000
Assunto: Re: [PagSeguro-Magento-Transparente] Desinstalar completamente o módulo (#68)

 

Voce desinstalou apenas o modulo principal e manteve o Pro.

**Comment by LHD2000** [comment]
Opa, fiz o que você recomendou acima alterando de true para false no arquivo app/modules/RicardoMartins_*.xml e tudo voltou ao normal!!!!
Caso eu reinstale o módulo, preciso fazer alguma coisa antes para não dar problema ou posso instalar direto por cima?

**Comment by LHD2000** [comment]
O site e o admin voltaram a funcionar, mas o downloader não, quando tento acessar aparece no alto da página: Module "RicardoMartins_PagSeguroPro" requires module "RicardoMartins_PagSeguro".
O que posso fazer para resolver isso?

**Comment by r-martins** [comment]
Veja https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203584779

**Comment by r-martins** [comment]
Se não quiser desinstalar, e sim deixar os dois funcionando, você precisa instalar o modulo principal.
Instruções aqui: http://r-martins.github.io/PagSeguro-Magento-Transparente/#instalao

**Comment by cassolatto** [comment]
Como eu desinstalo completamente o módulo ? Tipo ate´apagar ele do magento, pelo magendo connect normal posso fazer isso ?

Vou começar do ZERO !

**Comment by r-martins** [comment]
@cassolatto no link acima... https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203584779

**Comment by cassolatto** [comment]
amigo, o pagseguro mandou uma mensagem dizendo que estava autorizado, fiz
tudo de novo, e continuo na mesma !

uma luz por favor !


*RICARDO CASSOLATTO*

Business Consultant
sintetik@gmail.com / 21 98196-0504

*FastMobile*
http://fastmobile.info
Rua Farani, 23 - apto. 403 - Botafogo - CEP 22231-020 - RJ - BRASIL

<http://www.facebook.com/ricardo.cassolatto>
<https://br.linkedin.com/in/ricardo-cassolato-9ba225>

2016-05-16 21:37 GMT-03:00 Ricardo Martins <notifications@github.com>:
