### ISSUE TITLE
"Dados do cartão inválidos" (PagSeguro Transp. + OSC)

### ISSUE THREAD

**Issue by MatosS** [r-martins/PagSeguro-Magento-Transparente#69]
Estou utilizando o modulo junto do OSC Brasil 6 Pro, meu problema ocorre quando é necessário preencher novamente os dados da forma de pagamento, por exemplo, quando altera-se a forma de entrega, por default as parcelas não mudam, é necessário apagar os dados e preencher novamente para que o ajax que preenche as parcelas seja chamado, porém quando preencho os dados novamente, com as mesmas informações que antes haviam dado certo, ele emite o erro: "Dados do cartão inválidos", o erro ocorre no retorno do metodo "RMPagSeguro.updateCreditCardToken" que por sua vez chama o "PagSeguroDirectPayment.createCardToken".

Eu já usei console.log em todas as variaveis que são enviadas no método, e sempre envia a mesma coisa, se eu atualizar a pagina, preencher os dados novamente e finalizar a compra vai normal, mas se eu preencher, alterar a forma de entrega, preencher os dados do cartão novamente, ele já da o erro "Dados do cartão inválidos", na verdade o mais estranho é que as vezes da o erro, as vezes não, sempre com os mesmos dados.

Eu fiz umas alterações para quando mudar a forma de entrega chamar o metodo "RMPagSeguro.getInstallments" e "RMPagSeguro.updateCreditCardToken" em seguida, para não precisar ficar preenchendo novamente, mas não consegui resolver o problema do "Dados do cartão inválidos", se alguém puder me dar uma ajuda ...

Segue algumas imagens das requisições:
![parametros1](https://cloud.githubusercontent.com/assets/4741238/5820754/3f62263a-a0ae-11e4-8e98-427b10b664f8.png)
![resposta1](https://cloud.githubusercontent.com/assets/4741238/5820756/4434d1f8-a0ae-11e4-8be5-eec0cbc6ec28.png)
![parametros2](https://cloud.githubusercontent.com/assets/4741238/5820759/49c94a4a-a0ae-11e4-9e9c-3d6704ddcf13.png)
![resposta2](https://cloud.githubusercontent.com/assets/4741238/5820760/4e05e0aa-a0ae-11e4-894c-0f1def7b8001.png)

Os parametros e resposta da primeira requisição que deu certo, e os parametros e resposta da segunda requisição que retorna o erro.

**Comment by hiuryanderson** [comment]
Tive o mesmo problema só que não foi com o OSC, foi com o checkout padrão do magento. E tentei fazer os mesmos passos que você colocou acima para resolver, mas a única maneira que consegui resolver foi removendo o PagSeguroDirectPayment.setSessionId da  lugar e colocando ele no js que é chamado somente uma vez na página, veja as modificações que eu fiz abaixo:

https://github.com/r-martins/PagSeguro-Magento-Transparente/pull/65/files

Espero que funcione para você

**Comment by MatosS** [comment]
Realmente, o problema é com a Session, o trecho de codigo que seta a Session é chamado sempre que a forma de pagamento é atualizada, isso que da o problema na hora de pegar o Token novamente. É só mudar para um local que chame uma vez só mesmo.
