### ISSUE TITLE
Valores parcelamento não aparecem

### ISSUE THREAD

**Issue by marcelloinfoweb** [r-martins/PagSeguro-Magento-Transparente#70]
Venho trazer uma questão muito perigosa e complicada para qualquer empresa.

Estou passando por complicações depois que instalei o módulo, não estou dizendo que ele é ruim, o módulo é ótimo, melhor que muitos que ja usei, mas hj depois de quase duas semanas usando.

[PROBLEMA] uma cliente comprou pelo pagseguro transparente e logo em seguida entrou em sua conta, no pagseguro, e viu que nao foi divido em 3 vezes como ele queria, mas somente em 1vez. Recebi um Chamado do pessoal de suporte, entrei na conta da empresa e vi que realmente estava somente em 1 vez, simulei uma compra e vi que não mostra as parcelas e nem qual o cartão usado, fica como se nao tivesse digitado o numero do cartão, simplesmente nao faz nada, e assim, ele seleciona 1x e envia.

Obs.: Testei em minha versão local em sandbox e funciona mas na loja online não, minha falha nao ter testado antes, infelizmente.

Uso Magento 1.7.0.1
Tema mobileShoppe

Por favor gostaria de uma possível solução.

Att.,

**Comment by r-martins** [comment]
Oi @marcelloinfoweb,
Nas versões beeem antigas do modulo, não tinha exibição e seleção de parcelas.
Receio que seu tema ou algum css esteja escondendo o dropdown de parcelamento, que é populado após o preenchimento dos 6 primeiros digitos do cartao.

**Comment by marcelloinfoweb** [comment]
Mas tenho um clone do site online em um servidor local, e funciona normal.

**Comment by diogodaluz** [comment]
Mesmo problema aqui.. EM dois temas distintos do Magento aconteceu a mesma coisa. :( Nao aparece o parcelamento.

**Comment by diogodaluz** [comment]
Sempre aparece  mensagem:
Cartão Inválido
Verifique os dados do cartão digitado.

E nao popula as opçoes de parcelamento. ( o cartão está digitado corretamente, testei alguns cartoes meus já e sempre a mesma coisa e dois temas diferentes Magento)

**Comment by lhcarvalho** [comment]
@diogodaluz , você conseguiu resolver este problema? Estou tendo a mesma dificuldade por aqui...

**Comment by mefornazari** [comment]
Alguém conseguiu resolver esse problema? Estou tendo o mesmo problema, o valor total não conta com o valor total do parcelamento..
