### ISSUE TITLE
Links quebrados por espaço

### ISSUE THREAD

**Issue by rafaelstz** [r-martins/PagSeguro-Magento-Transparente#72]
Links **versão PRO** e **aqui** no sandbox estão quebrados por um espaço gerado entre http://, o tornando http: //.

**Comment by r-martins** [comment]
Fala mestre!
Eu percebi isso ontem. Já corrigi na versão 2.0 que devo lançar entre hoje e amanhã.
Por alguma razão o magento quebra o último link do CDATA quando tem mais de um link. Resolvi criando um terceiro link pra lugar nenhum rs.

Valeu pelas contribuições!
