### ISSUE TITLE
RMPagSeguro is not defined

### ISSUE THREAD

**Issue by marcelloinfoweb** [r-martins/PagSeguro-Magento-Transparente#74]
Estou tendo esse erro: ReferenceError: RMPagSeguro is not defined no inspecionador

No Firefox 35
"PagSeguro ready"                                                             idecheckoutvm:649
ReferenceError: RMPagSeguro is not defined                   idecheckoutvm:652
ReferenceError: RMPagSeguro is not defined                   prototype.js line 612 
"PagSeguro ready"                                                             prototype.js line 612
 
E no Google Chrome 39
PagSeguro ready
Uncaught ReferenceError: RMPagSeguro is not defined           (index):652 
(anonymous function)                                                                 (index):652 
E leva a esse: RMPagSeguro.updateSenderHash();

Uncaught ReferenceError: RMPagSeguro is not defined             VM520:10
(anonymous function)                                                                   VM520:10
Tbm leva ao mesmo lugar no script: RMPagSeguro.updateSenderHash();

O site é esse: http://assistemas.com.br/loja/
Não consigo ver as parcelas depois de preencher os dados do cartão, e se envia vai, mas somente em uma parcela.

Espero que possa resolver, Obrigado!

**Comment by marcelodeandrade** [comment]
Qual foi a solução, @marcelloinfoweb ?
