### ISSUE TITLE
Erro checkout Pagseguro Pro

### ISSUE THREAD

**Issue by gilmr** [r-martins/PagSeguro-Magento-Transparente#76]
Eu instalei o pagseguro pro e quando finalizo o pedido para redirecionar ao pagseguro para pagar com boleto ou transação eletronica, não é redirecionado e dá o erro:
Desculpe, infelizmente, houve um erro durante o checkout. Entre em contato com o administrador da loja, se o problema persistir.
Como faço para resolver?

**Comment by r-martins** [comment]
Olá @gilmr 
Precisava de mais detalhes. Analise os logs no momento do fechamento do pedido e veja se há algum erro logado.
