### ISSUE TITLE
Cartão inválido e parcelamento

### ISSUE THREAD

**Issue by luizasangalli** [r-martins/PagSeguro-Magento-Transparente#77]
Olá a todos, 

primeiramente, um grande agradecimento ao Ricardo pelo módulo, excelente.

Bom, estava utilizando o módulo tranquilamente, meu token está ok para transparente.

Após migração e atualização do magento reinstalei o módulo na versão mais recente, via git.

Porém, agora, assim que digitamos o cartão de crédito ele imprime na tela "Cartão inválido" e nao exibe as parcelas.

No log temos:
DEBUG (7): Falha na autenticação com API do PagSeguro. Verifique email e token cadastrados. Retorno pagseguro: Unauthorized

Porém sabemos que esse erro  Unauthorized é um erro do sistema e não do pagseguro. e o token já foi testado para transparente.

Sem erros de js e outros problemas aparentes, enfim, não estou conseguindo descobrir a causa. Na mesma instalaçao tentei mudar para o tema default, e mesmo assim não funcionou.

Magento 1.9 / Apache/ AWS.

http://54.94.136.111/

Alguma dica?

Obrigada!

**Comment by deniscsz** [comment]
Existe um controller que gera uma ID de session para fazer o ajax das parcelas, o action em questão é o `getSessionIdAction`. [a link](https://github.com/r-martins/PagSeguro-Magento-Transparente/blob/master/app/code/community/RicardoMartins/PagSeguro/controllers/AjaxController.php)

Dá uma explorada se esse ajax tá sendo acontecendo.

**Comment by Thalles** [comment]
Bom dia luizasangalli,
você conseguiu resolver o problema?

**Comment by luizasangalli** [comment]
Bom dia Thales,

Ainda não conseguimos, conversei com outros deve magento também e nada. Aparentemente esta tudo OK, mas o erro se repete. Se puder ajudar agradeço.

bannerja.com.br

Obrigada

**Comment by r-martins** [comment]
Vc disse que foi após migrar... A key do local.xml foi migrada junto?
Do contrario, tente colocar o token novamente nas configs do modulo no
painel, e salvar novamente as configurações.

Sent from my Android.
Em 09/02/2015 11:42, "luizasangalli" <notifications@github.com> escreveu:

**Comment by luizasangalli** [comment]
Olá Ricardo, 

Mantive a key, gerei um novo token no pagseguro, mas mesmo assim nada. 

Quando termino de colocar os números do cartão ele já exibe cartao inválido

**Comment by Thalles** [comment]
Bom dia Ricardo no meu ocorre o mesmo problema, eu percebi que o parâmetro tk que é passado via ajax está indo vazio

**Comment by luisgennari** [comment]
Talvez isso ajude: https://github.com/r-martins/PagSeguro-Magento-Transparente/issues/69

**Comment by luizasangalli** [comment]
Obrigada @luisgennari mas já havia testado e, mais uma vez, sem sucesso.

**Comment by r-martins** [comment]
Olá @luizasangalli,
Visitando o endereço da loja que passou na primeira mensagem, e inserindo no console (firebug) o seguinte codigo javascript:

    RMPagSeguro.updateSessionId()

Notei que o sistema não conseguiu capturar o sessionId. Isso ocorre em 99% das vezes porque o token está incorreto ou não habilitado pra usar pagseguro transparente.
Teste o seu token na [pagina de FAQ](http://r-martins.github.io/PagSeguro-Magento-Transparente/faq/) do modulo.

**Comment by luizasangalli** [comment]
Olá @r-martins, 

Muito obrigada pela resposta, mas já havia testado o token, inclusive testei novamente agora e ele está sim habilitado para transparente.

**Comment by luizasangalli** [comment]
Após colocar os dados do cartão tenho essa resposta no console:

Resource interpreted as Image but transferred with MIME type text/html: "https://pagseguro.uol.com.br/checkout/nc/log-event.jhtml?type=invalid_respo…6+(KHTML%2C+like+Gecko)+Chrome%2F37.0.2062.94+Safari%2F537.36&jsversion=v3".

Mas acredito que não seja o problema.


Obrigada
