### ISSUE TITLE
Retorno Inválido na chamada da api (método callApi)

### ISSUE THREAD

**Issue by deniscsz** [r-martins/PagSeguro-Magento-Transparente#78]
Eventualmente o retorno do pagseguro ao envio dos parâmetros da transação tem sido o mostrado abaixo.

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

Percebi que isso pode ser a causa de problemas de deadlock que estou tendo, nos quais ao finalizar compra o cliente fica aguardando a finalização até dar timeout que resulta em um alert de erro avisando que o pedido não pode ser processado.

```php
try{
    $response = curl_exec($ch);
    curl_close($ch);
}catch(Exception $e){
    //Para logar o retorno, criei um log de $response aqui. Ele nunca é executado mesmo com erro 400 (citado acima)
    Mage::throwException('Falha na comunicação com Pagseguro (' . $e->getMessage() . ')');
}

//Para logar o retorno, criei um log de $response aqui. Aqui sim eu vi o erro 400 citado acima.
```

Observando o try que faz o envio dos parâmetros é possível ver que caso o response exista (o envio foi feito), mas a resposta não seja a esperada (página HTML retornada citada acima), a execução não passará pelo catch e por tanto a execução continua sem o pagamento devidamente processado, gerando um grande problema.

Eu mesmo mudei recentemente o código para cURL no lugar de usar a classe Zend_Http_Client. O tratamento (apenas try) que existia anteriormente não satisfaz para a utilização de cURL. O que ainda não ficou claro é porque o pagseguro retorna, a primeira vista, de forma intermitente esse erro 400.

**Comment by deniscsz** [comment]
Testei utilizando novamente a classe Zend_Http_Client de volta e o Exception é gerado, com a seguinte mensagem: "Unable to read response, or response is empty".

Alguém está tendo algum problema de comunicação com pagseguro?

**Comment by deniscsz** [comment]
Após o dia em que criei a issue, parou de acontecer.
Acredito que o problema foi de algo relacionado a infra, pois estava em um servidor local, mesmo que tendo um link e ip dedicado. Desde então não aconteceu novamente.

**Comment by r-martins** [comment]
Obrigado pelo feedback @deniscsz
