### ISSUE TITLE
Cliente vai para página de sucesso mesmo com cartão negado na hora

### ISSUE THREAD

**Issue by artexpressa** [r-martins/PagSeguro-Magento-Transparente#79]
Na grande maioria dos e-commerces, quando o cartão é automaticamente negado, o site informa isso ao cliente e sugere que ele tente uma nova forma de pagamento.

Usando o modulo, todos os clientes vão para a página de sucesso (até quando se digita um cartão qualquer). 

Isso é muito ruim pois a loja perde muitas vendas, além de sacanear o google analytics que fica mostrando dados de transações que não foram realizadas.

**Comment by r-martins** [comment]
Olá @artexpressa,
Para atender essa sugestão eu teria que processar o pedido com o pagseguro antes de gerar o pedido na sua loja, o que não seria legal, por pelo menos dois motivos: 1) se houver um problema na geracao do pedido (magento), você ficará com transações órfãs no pagseguro 2) ficaria mais dificil enviar ou identificar um pedido no pagseguro que não possui um order id.
Como você imaginaria esse processo sem gerar o pedido?

Há ainda casos onde a transação demora alguns segundos para ser negada e dá a impressão de que foi 'na hora'. Fazer o cliente esperar nem que seja 5 segundos a mais por uma resposta imediata pode não ser uma boa também.
