### ISSUE TITLE
Blocked a frame with origin "https://pagseguro.uol.com.br" from accessing a frame with origin...

### ISSUE THREAD

**Issue by luisgennari** [r-martins/PagSeguro-Magento-Transparente#80]
Pessoal,
O módulo está funcionando 100% na minha loja teste. Utilizo magento versão 1.9.1 tema RWD padrão. No entanto, no console de erro do browser mostra a seguinte mensagem:

Blocked a frame with origin "https://pagseguro.uol.com.br" from accessing a frame with origin "https://www.meusite.com.br". Protocols, domains, and ports must match.

Bom, como eu disse anteriormente, o módulo funciona normalmente, mas mesmo assim gostaria de resolver esse problema para remover essa mensagem. Alguém pode me ajudar com isso?

**Comment by r-martins** [comment]
Parece ser um problema do Pagseguro.
Veja em http://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame.

**Comment by luisgennari** [comment]
Já que o módulo está funcionando,.. vamos deixar assim mesmo! 
:)
