### ISSUE TITLE
Cartão Inválido

### ISSUE THREAD

**Issue by thiagoromera** [r-martins/PagSeguro-Magento-Transparente#81]
Quando eu faço uma compra fora do modo de teste, ao digitar um cartão corretamente, ele diz que o cartão é inválido.

Alguém passou por isso? Resolveu?

**Comment by LBCorr** [comment]
Thiago, no sandbox funciona normalmente? Alterou seu Token para conta principal? Eu já tivesse esse problema mas na verdade era minha conexão com o pagseguro que não estava acontecendo, então ele não retonava o tipo de cartão. O log retona alguma mensagem de erro?

**Comment by thiagoromera** [comment]
No sandbox funciona. Não entendi a questão do token para conta principal. Eu mandei email pro pagseguro pedindo a liberação do recurso como descrito. Mas ainda não tive resposta. 

Será por isso?

Thiago 

Enviada do meu iPad

**Comment by r-martins** [comment]
@thiagoromera 
Isso ocorre geralmente porque o token está incorreto.
Veja em https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203585029--Cart%C3%A3o-inv%C3%A1lido-aparece-para-qualquer-cart%C3%A3o-digitado

**Comment by thiagoromera** [comment]
Olá Ricardo, desculpe a demora, estava no aguardo do PagSeguro. Eles disseram que o checkout transparente está resolvido, mas fui tentar fazer uma compra e ainda recebo a msg de que o cartão é inválido.

**Comment by r-martins** [comment]
Olá Thiago,
Qual url da loja com dificuldade?

2015-03-04 14:20 GMT-03:00 thiagoromera <notifications@github.com>:

**Comment by thiagoromera** [comment]
Oi Ricardo, é esta:
http://www.venerare.com.br/

**Comment by r-martins** [comment]
Pode enviar um print da area onde configurou a licença do modulo?

**Comment by thiagoromera** [comment]
Segue o print
http://snag.gy/rQBub.jpg
Obrigado

**Comment by thiagoromera** [comment]
Olá Ricardo, lhe mandei o print, pode analisar este caso?

Abs

**Comment by BernardinoGomes** [comment]
Também estou com esse mesmo problema.Já teve alguma solução Thiago Romera ?

**Comment by bnubruno** [comment]
Bom dia, utilizei o modelo de aplicação e consegui fazer duas compras. Limpei o campo do Token e selecionei novamente assinatura, e agora ta sempre cartão inválido.
