### ISSUE TITLE
Módulo "comendo" valores terminados em 0

### ISSUE THREAD

**Issue by guztavoalves** [r-martins/PagSeguro-Magento-Transparente#82]
Fala galera, 
notei um probleminha no módulo, que está me dando uma dor de cabeça aqui, quando o preço de uma parcela termina com 0, o módulo "come" esse 0 deixando o preço estranho, veja na imagem abaixo:

http://prntscr.com/66zxt9

Como posso alterar para que isso não ocorra?

Preciso que fique no padrão R$ 00,00

Vlw galera.

**Comment by artexpressa** [comment]
@guztavoalves Em teoria essa correção está no último update do módulo. Você já está com a versão 2.0.0?

Abs

**Comment by guztavoalves** [comment]
Lembro de ter instalado a ultima versão aqui do Git, agora baixei novamente e instalei, limpei todos os caches e agora está tudo certinho, não está mais "comendo" zero. :)
