### ISSUE TITLE
Invalid Creditcard Owner name

### ISSUE THREAD

**Issue by tiarly** [r-martins/PagSeguro-Magento-Transparente#84]
//file app/code/community/RicardoMartins/PagSeguro/Helper/Params.php
Code that may generate validations erros:
'creditCardHolderName'      =>  $payment['additional_information']['credit_card_owner'];

Caso o usuário preencha o nome com espaços duplos teremos problema na validação do Pagseguro impedindo a finalização da compra.

Neste caso sugiro colocar um trim para evitar possíveis erros do usuário

Code that may generate  no validations erros:
'creditCardHolderName'      =>  trim($payment['additional_information']['credit_card_owner']);

**Comment by artexpressa** [comment]
Aqui além do trim eu coloquei um str_replace (dois espaços, um espaço). Muitos clientes sei lá pq colocam espaços duplos.
