### ISSUE TITLE
Erro ao criar pedido pelo Admin

### ISSUE THREAD

**Issue by fuza** [r-martins/PagSeguro-Magento-Transparente#85]
Ao tentar criar um pedido pelo admin obtemos o erro:
Problemas ao processar seu pagamento. sender hash is required.(53150)

**Comment by r-martins** [comment]
Oi @fuza,
Realmente não contemplei muito a criação de pedidos com cartão de crédito via admin por uma questão legal e de segurança mesmo.
Pra fazer por lá entende-se que você teria pedido os dados do cartão por telefone, ou armazenou ele em outro lugar de alguma forma.
É isso mesmo ou entendi errado?

**Comment by fuza** [comment]
Olá Ricardo
O cartão seria obtido por telefone, já o boleto não vejo problemas em permitir ser gerado pelo admin.
Você irá considerar esta funcionalidade?
Obrigado.
