### ISSUE TITLE
Envio ao Pagseguro sem complemento de endereço ?

### ISSUE THREAD

**Issue by renatofig** [r-martins/PagSeguro-Magento-Transparente#86]
Fala Ricardo tudo bem ?
 
Cara, estou te contatando de novo pois de uns tempos pra cá quando baixei a última versão começou a aparecer um problema no envio dos dados de endereço do cliente, parece que o complemento não vai ou o Pagseguro corta os campos.
Isto fez com que tivesse que tratar 3 casos de entregas não efetuadas pois o Correio não sabia pra qual apto era...
Veja que anexei os dados do admin do Magento com o apto 62 mas no cadastro do Pagseguro esta info não vai...e na etiqueta gerada pelo sistema deles tb não...
 
Pode dar um help ? Será que o problema é lá :
 
Abs
 
Renato Figueiredo
11 98333-7111
renato.figueiredo@gmail.com

**Comment by r-martins** [comment]
Oi @renatofig,
Você deve configurar os campos de endereço, complemento, etc nas configurações do modulo no seu painel Magento.
Também é possível ver os dados de endereço que são enviados ao PagSeguro vendo o arquivo de log (pagseguro.log).
Qualquer coisa abre um ticket com o print das suas configs, anexando o pagseguro.log e com print do que chegou no painel do PagSeguro.
Grande abraço.

**Comment by renatofig** [comment]
Ok
Segue abaixo o log, note que o campo complemento realmente não vai preenchido e no admin do Magento tá tudo lá correto...


3-30T00:28:55+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><transaction><date>2015-03-29T21:29:01.000-03:00</date><code>09C58211-E764-4253-A7B7-C648FB3A08E0</code><reference>200000935</reference><type>1</type><status>1</status><lastEventDate>2015-03-29T21:29:01.000-03:00</lastEventDate><paymentMethod><type>1</type><code>102</code></paymentMethod><grossAmount>45.70</grossAmount><discountAmount>0.00</discountAmount><feeAmount>2.68</feeAmount><netAmount>43.02</netAmount><extraAmount>0.00</extraAmount><installmentCount>2</installmentCount><itemCount>1</itemCount><items><item><id>2649</id><description>Brinco EAR CUFF flores</description><quantity>1</quantity><amount>29.00</amount></item></items><sender><name>Eliane de Barros Kaiser</name><email>eliane.kaiser@unimedguarulhos.coop.br</email><phone><areaCode>11</areaCode><number>24962375</number></phone></sender><shipping><address><street>Estrada do Sacramento</street><number>440  </number><complement></complement><district>Cidade Tupinambá</district><city>Guarulhos</city><state>SP</state><country>BRA</country><postalCode>07263000</postalCode></address><type>3</type><cost>16.70</cost></shipping></transaction>'
2015-03-30T22:30:19+00:00 DEBUG (7): Parametros sendo enviados para API (/transactions): array (
  'email' => 'penelope_375@hotmail.com',
  'token' => 'A33AE81B782D4AD799DF162EE4629C3F',
  'paymentMode' => 'default',
  'paymentMethod' => 'creditCard',
  'receiverEmail' => 'penelope_375@hotmail.com',
  'currency' => 'BRL',
  'creditCardToken' => '2adfa3afe61f41c0876efc4da5b1b0ea',
  'reference' => '200000936',
  'extraAmount' => '0.00',
  'notificationURL' => 'http://penelopeacessorios.com.br/pseguro/notification/',
  'itemId1' => '2650',
  'itemDescription1' => 'Brinco GOTA verde esmeralda',
  'itemAmount1' => '39.00',
  'itemQuantity1' => '1',
  'senderName' => 'gislene carneiro',
  'senderEmail' => 'gislene.carneiro@gmail.com',
  'senderHash' => '0207db7794ec4cad302b9e51627a9afe6c7ada66eb6fb09b3b1cf8b5e069bb4d',
  'senderCPF' => '69114080168',
  'senderAreaCode' => '61',
  'senderPhone' => '35563575',
  'shippingAddressStreet' => 'Quadra ',
  'shippingAddressNumber' => '202',
  'shippingAddressComplement' => '',
  'shippingAddressDistrict' => 'Sul (Águas Claras)',
  'shippingAddressPostalCode' => '71937720',
  'shippingAddressCity' => 'Taguatinga',
  'shippingAddressState' => 'DF',
  'shippingAddressCountry' => 'BRA',
  'shippingType' => '1',
  'shippingCost' => '20.60',
  'billingAddressStreet' => 'Quadra ',
  'billingAddressNumber' => '202',
  'billingAddressComplement' => '',
  'billingAddressDistrict' => 'Sul (Águas Claras)',
  'billingAddressPostalCode' => '71937720',
  'billingAddressCity' => 'Taguatinga',
  'billingAddressState' => 'DF',
  'billingAddressCountry' => 'BRA',
  'creditCardHolderName' => 'gislene e carneiro',
  'creditCardHolderBirthDate' => '19/03/1975',
  'creditCardHolderCPF' => '69114080168',
  'creditCardHolderAreaCode' => '61',
  'creditCardHolderPhone' => '35563575',
  'installmentQuantity' => '1',
  'installmentValue' => '59.60',
)
2015-03-30T22:30:23+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><transaction><date>2015-03-30T19:30:28.000-03:00</date><code>63A06C08-A469-4215-8E34-FC1551B78844</code><reference>200000936</reference><type>1</type><status>1</status><lastEventDate>2015-03-30T19:30:28.000-03:00</lastEventDate><paymentMethod><type>1</type><code>101</code></paymentMethod><grossAmount>59.60</grossAmount><discountAmount>0.00</discountAmount><feeAmount>3.37</feeAmount><netAmount>56.23</netAmount><extraAmount>0.00</extraAmount><installmentCount>1</installmentCount><itemCount>1</itemCount><items><item><id>2650</id><description>Brinco GOTA verde esmeralda</description><quantity>1</quantity><amount>39.00</amount></item></items><sender><name>gislene carneiro</name><email>gislene.carneiro@gmail.com</email><phone><areaCode>61</areaCode><number>35563575</number></phone></sender><shipping><address><street>Quadra </street><number>202</number><complement></complement><district>Sul (Águas Claras)</district><city>Taguatinga</city><state>DF</state><country>BRA</country><postalCode>71937720</postalCode></address><type>1</type><cost>20.60</cost></shipping></transaction>'
![complemento_ok](https://cloud.githubusercontent.com/assets/2308563/6931242/3360bd64-d7e1-11e4-8cec-b962896b2132.png)
![modulo](https://cloud.githubusercontent.com/assets/2308563/6931280/8b4a8b22-d7e1-11e4-8844-9b33b9450739.png)
![pagseguro](https://cloud.githubusercontent.com/assets/2308563/6931286/a6d15060-d7e1-11e4-9f1f-a83d486cfa74.png)
