### ISSUE TITLE
Erro 53021

### ISSUE THREAD

**Issue by juurata** [r-martins/PagSeguro-Magento-Transparente#87]
Tive o problema em receber o pedido de um cliente e recebi a mensagem "Problemas ao processar o seu pagamento. Telefone do comprador inválido: 247561 (53021)
esse 247561 é parte do telefone do cliente porem o cliente o preencheu corretamente. com 8 digitos.
O que devo fazer para isso não ocorrer novamente? o telefone foi colocado sem o DDD mas isso eu posso saber pelo estado de residencia do cliente.

**Comment by r-martins** [comment]
Oi @juurata 
O telefone deve ir num campo só com ddd e numero juntos.
Se utiliza de forma diferente, voce deve editar o metodo _extractPhone no Params.php.
