### ISSUE TITLE
Retorno inválido. Referência do pedido não encontrada.

### ISSUE THREAD

**Issue by cassiohalmeida** [r-martins/PagSeguro-Magento-Transparente#89]
Olá Ricardo, primeiro parabéns pelo módulo! Encontrei um problema e acho que vale a pena reportar.
Eu estou no ambiente de SandBox, e quando altero o status de um pedido e mando a notificação via API, o PagSeguro só recebe essa informação:

Retorno inválido. Referência do pedido não encontrada.

E o código retornado fica como 503. Porém no log, o erro é o seguinte:

Retorno do Pagseguro para notificationCode "codigo_aqui": Unauthorized

O estranho é que eu tenho essa mesma aplicação em outro servidor (de teste) e lá as notificações chegam normalmente. Os ambientes são idênticos já que trabalho com replicação.

Obrigado!

**Comment by r-martins** [comment]
Olá Cássio,
Obrigado pelos comentários.
Você usa modelo de aplicação ou assinatura? Se for aplicação, a sandbox
ainda não está disponível.

Aparentemente o pagseguro esta mandando um "codigo_aqui" como
notificationCode. Se isso nao foi um teste seu, o pagseguro está mandando o
que nao devia.

Abs

Sent from my Android.
Em 04/04/2015 17:06, "Cássio Almeida" <notifications@github.com> escreveu:

**Comment by cassiohalmeida** [comment]
Ricardo, uso modelo de aplicação. Mesmo com esse retorno errado no ambiente de SandBox, resolvi subir o módulo em produção. Está funcionando. Pode fechar.
