### ISSUE TITLE
Problema Multi Store

### ISSUE THREAD

**Issue by thiagoromera** [r-martins/PagSeguro-Magento-Transparente#90]
Olá Rícardo, eu tive um problema recente de Cartão Inválido e depois de uma verificação com o PagSeguro sobre a liberação da conta está funcionando.
Acontece que essa loja é multiAmbiente, eu tenho duas lojas (dois domínios) usando o mesmo assim. As configurações da conta do PagSeguro serão as mesmas, ou seja, as duas lojas faturarão na mesma conta do PagSeguro. Por eles, disseram que não tem problema.

Acontece que a integração transparente só funciona na loja principal. Na outra loja da o erro de cartão inválido. Eu já tentei setar as configurações da loja e do PagSeguro como sendo a segunda loja a principal, mas não funcionou.

Tem algo que possa me ajudar?

**Comment by r-martins** [comment]
Pode anexar prints das suas configs em todos os escopos disponiveis?

2015-04-13 10:10 GMT-03:00 thiagoromera <notifications@github.com>:

**Comment by thiagoromera** [comment]
Segue os prints, a configuração está no escopo todas as lojas. Os demais herdam apenas.
Thiago

Date: Mon, 13 Apr 2015 06:26:10 -0700

**Comment by r-martins** [comment]
Oi @thiagoromera 
Acho que os prints não vieram.
No pagseguro.log foi logado alguma coisa?

**Comment by thiagoromera** [comment]
No pagseguro.log da loja principal joiaunica.com.br vem este retorno:
2015-04-09T18:38:55+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulÃ¡rio. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualizaÃ§Ã£o de blocos via ajax nao se preocupe.2015-04-09T18:38:56+00:00 DEBUG (7): Falha na autenticaÃ§Ã£o com API do PagSeguro. Verifique email e token cadastrados. Retorno pagseguro: Unauthorized
Obrigado
Thiago
Date: Tue, 14 Apr 2015 16:04:43 -0700

**Comment by edmarholanda** [comment]
thiagoromera,

Eu estou com um problema similar. No meu caso são dois websites na mesma instalação. 

No meu website 1, que seria o domínio principal, o módulo parece não se comunicar com o PagSeguro. Após preencher todos os dados de pagamento, as opções de parcelamento não são exibidas. No campo "Parcelas" é exibida a mensagem "Informe os dados do cartão para calcular".

No website 2, que funciona num subdomínio do principal, tudo funciona perfeitamente.

Meu log retorna isso:

Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulÃ¡rio. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualizaÃ§Ã£o de blocos via ajax nao se preocupe.

**Comment by thiagoromera** [comment]
É o mesmo problema que acontece no meu, mas ao contrário. Funciona perfeito no primário e não no secundário. Com o mesmo erro.
Ricardo poderia nos dizer se o módulo e a solução é compatível com  ambientes multiStore?
Thiago

Date: Thu, 23 Apr 2015 08:17:43 -0700

**Comment by edmarholanda** [comment]
Num determinado momento, depois de limpar cache (navegador e Magento) e fazer algumas alterações de teste no index.php, consegui fazer o módulo funcionar no domínio principal (Website 1), mas a animação durou pouco. Fui testar no subdomínio (Website 2) e agora lá tinha parado de funcionar. Desfiz todas as alterações. Website 2 voltou a trabalhar corretamente com o módulo e Website 1 parou.

Ou estamos configurando algo errado ou o módulo não trabalha com multi-websites.

**Comment by edmarholanda** [comment]
thiagoromera,

O Ricardo conseguiu resolver meu problema. No meu caso, era erro na URL Base do HTTPS, que não estava configurado adequadamente. Espero que também seja o seu caso :)

**Comment by thiagoromera** [comment]
Como assim? O que pode estar errado na configuração?

Ricardo, pode me ajudar?

Como conseguiu contato com ele? 

Enviado via iPhone

Em 23/04/2015, às 20:34, "edmarholanda" <notifications@github.com> escreveu:

**Comment by r-martins** [comment]
@thiagoromera 
Por favor anexe a imagem do print da configuração nas duas visões.
Se possivel, informe o url delas para que eu possa verificar.

**Comment by thiagoromera** [comment]
Olá Ricardo, eu mandei elas por emails e não tinha visto que não apareceram aqui no Git.

As duas lojas usam o mesmo email de configuração e o mesmo token, pois usam a mesma config no PagSeguro.

As URL são www.joiaunica.com.br e www.venerare.com.br, mas o módulo está desativado para não haver reclamações com os clientes.

Segue os prints, a configuração está no escopo todas as lojas. Os demais herdam apenas.

![visaotodaslojas](https://cloud.githubusercontent.com/assets/4664163/7335299/fe00f73e-eb8a-11e4-81cc-dfd4048d93f0.jpg)
![websiteju](https://cloud.githubusercontent.com/assets/4664163/7335300/fe049a42-eb8a-11e4-972c-30625233780e.jpg)
![websiteva](https://cloud.githubusercontent.com/assets/4664163/7335301/fe07d630-eb8a-11e4-899a-16461b1a893d.jpg)

**Comment by marcelodeandrade** [comment]
@thiagoromera Conseguiu resolver? Estou com um problema similar.

**Comment by thiagoromera** [comment]
Não cara, não resolveu.

**Comment by r-martins** [comment]
@thiagomera,
Você pode mandar um login e senha do painel pra pagseguro-transparente@ricardomartins.net.br ?
Só dá uma lembrada lá sobre o topico e os url's de acesso.
Se possivel, envie também o token que está usando.

Abraços.

**Comment by renatoaleksander** [comment]
Boa Noite @r-martins 
Em relação ao este assunto em minha loja virtual tenho duas visões diferentes uma a principal é destinada para Clientes e outra destinada para revendedores.

Hj saiu um pedido de revenda a qual gerou o Pedido 200000001 e na forma de boleto mas acontece que não gerou o pedido no pagseguro e ao tentar exibir o boleto abre-se uma nova aba mas acaba por voltar a tela do pedido diferentemente da visão do cliente que funciona corretamente.

Gostaria de contribuir com informações para sua análise sobre este problema.

**Comment by marcelodeandrade** [comment]
@renatoaleksander 1)Verifique o log do pagseguro e qual erro ocorreu; 2) Verifique as URL e a forma de pagamento na sua multiloja e se estão corretas;

**Comment by renatoaleksander** [comment]
Olá, @marcelodeandrade verifiquei o log de erro e deu este abaixo alterei o nome do cliente na loja de revendedores e  foi gerado normalmente o boleto.

Agradeço a sua disposição em ajudar a comunidade

Pode ser que os problemas relatados acima tenham algum problema neste sentido.

Notificando o @r-martins 

Att,
Renato Aleksander www.fator5.net

2015-08-05T15:10:49+00:00 DEBUG (7): Retorno PagSeguro (/transactions): '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>sender name invalid value: Mxxxa de Fxxxxx Lxxx Mxxxx</message></error></errors>'

**Comment by r-martins** [comment]
Senhores,
Realizei o teste em um ambiente multi-loja, com 2 websites e url's diferentes, e funcionou ok.
Em prol de outro problema, hoje comecei a realizar mais testes no Chrome, e percebi alguns problemas com relação às chamadas em ajax, e que acredito ser o problema de vocês.
No meu ambiente eu tenho URL's diferentes, sendo que em um dos casos eu tinha um URL Seguro com https, e outro nao seguro, sem httpS, apenas com http configurado no painel (Web).
No entanto, eu havia configurado pra NAO usar http seguro no frontend. E isso causava alguns problemas de CORS nas chamadas do prototype, que sempre buscava o url seguro, ignorando se o checkout era seguro ou não.
Resolvi o problema na versão 2.2.0 que devo lançar esta semana.
Por ora, desejarem, basta modificar o metodo \RicardoMartins_PagSeguro_Helper_Data::getPagSeguroScriptBlock pelo codigo abaixo:

```
public function getPagSeguroScriptBlock()
    {
        $scriptBlock = Mage::app()->getLayout()->createBlock('core/text', 'js_pagseguro');
        $secure = Mage::getStoreConfigFlag('web/secure/use_in_frontend');
        $scriptBlock->setText(
            sprintf(
                '
                <script type="text/javascript">var RMPagSeguroSiteBaseURL = "%s";</script>
                <script type="text/javascript" src="%s"></script>
                <script type="text/javascript" src="%s"></script>
                ',
                Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, $secure),
                Mage::helper('ricardomartins_pagseguro')->getJsUrl(),
                Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, $secure) . 'pagseguro/pagseguro.js'
            )
        );
        return $scriptBlock;
    }
```

Qualquer novidade voltamos a falar.
Grande abraço e boas vendas a todos.
