### ISSUE TITLE
Número limitado de ano de vencimento de cartão

### ISSUE THREAD

**Issue by kimtiago** [r-martins/PagSeguro-Magento-Transparente#91]
Olá,

O Sandbox do PAGSEGURO me deu um numero de cartão de credito para testes com vencimento em 2030

Porém o modulo permite informar o ano somente até 2025. Solicito que aumente pelo menos até 2030

**Comment by r-martins** [comment]
Olá @kimtiago 
Isso é calculado no metodo \Mage_Payment_Model_Config::getYears  do magento.
Até onde sei não se emite cartões com mais de 10 anos de validade.
Se desejar alterar em sua loja, fique à vontade. Não sei se o PagSeguro negará a transação por isso.
