### ISSUE TITLE
Erro ao Processar Pedido Pessoa Juridica

### ISSUE THREAD

**Issue by VandoCosta** [r-martins/PagSeguro-Magento-Transparente#92]
Boa tarde,

Quando o Cliente se cadastra como Pessoa Juridica  "CNPJ"  e  finaliza a compra, acontece o seguinte erro:

Problemas ao processar seu pagamento. sender cpf invalid value: xxxxxxxxxxxxx (53017).
Lembrando que o cliente está se cadastrando com CNPJ

Utilizando a Versão Pro

**Comment by r-martins** [comment]
Olá @VandoCosta 
Por favor veja [este link](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/204916395).
