### ISSUE TITLE
Número de Pedidos

### ISSUE THREAD

**Issue by thiagoromera** [r-martins/PagSeguro-Magento-Transparente#93]
Durante a homologação da loja, fiz diversos testes de pedidos pelo PagSeguro e estava retornando com erro porque não estava devidamente configurado o CPF do usuário e ele retornava com uma mensagem pro carrinho.
Dias depois fui notar que houve um pulo do pedido 12 para o pedido 21, o que me leva a crer que essas tentativas que geraram falhas. A impressão que deu é que esses erros geraram pedidos, mas não concretizaram. E estes foram excluídos.
Como eram testes, tudo bem, mas ontem, depois que vários pedidos aconteceram, isso voltou a acontecer, com dois pedidos (talvez retentativas). Acontece que eu não tinha ligado log do módulo para saber o motivo.
Quero saber se realmente pedidos com falhas de processamento e erros são excluídos (a minha sequência de pedidos está 38, 39, 41, 42, 43, 44, 47, 48). Existe uma forma de não excluir os pedidos que tiveram erros para o cliente ter ciência disso e tentar resgatar a compra?

**Comment by r-martins** [comment]
@thiagoromera 
Os pedidos nunca são 'excluidos' (pelo menos não pelo modulo).
Tivemos um problema de infraestrutura na semana que você comentou, e que pode ter afetado a entrada de pedidos para quem usa modelo de aplicação, mas já foi solucionado com a troca de servidores.

**Comment by thiagoromera** [comment]
Eu não uso modelo de aplicação. Talvez excluído não seja o termo, ele não grava as tentativas falhas no sistema.
Se houve uma tentativa e ela não foi concluída, isso não fica registrado no admin.
E todos as tentativas não sucedidas no teste foram pelo módulo.

**Comment by r-martins** [comment]
@thiagoromera 
Se não usa modelo de aplicação então a instabilidade foi do Pagseguro mesmo.
O pedido entrou no Pagseguro?

**Comment by thiagoromera** [comment]
Não entrou. Ele não foi finalizado pela loja, ele ia para uma página em branco com uma mensagem de erro (de sender hash, por exemplo) e depois dava redirect para o checkout novamente. Mas a cada tentativa dessa, mesmo que não bem sucedida, ele incrementava o número do pedido.

**Comment by r-martins** [comment]
Entendi..
Se não gerou o pedido em lugar nenhum, e mostrou ao cliente que deu erro, então o unico problema é o sequencial do pedido.

Ok. Vou deixar em aberto pra análise.

**Comment by thiagoromera** [comment]
Ok, Obrigado Ricardo.
Se eu optar por usar o modelo de aplicação, usa-se um outro módulo? Algum suporte diferente além deste aqui pelo git? Algum canal de comunicação direto?

**Comment by r-martins** [comment]
Oi @thiagoromera 
O modulo é o mesmo, desde que o PRO seja superior a versao 2.0.
Em nenhuma situação/plano há suporte. O suporte é uma cortesia, pois faço isso tudo no meu tempo livre. Não sou empresa. ;)

**Comment by r-martins** [comment]
@thiagoromera,
Se o problema ainda persiste, peço que reabra e me ajude a tentar reproduzir.
Desde a última interação não tive casos parecidos com o seu. Esta semana estou dando uma geral no modulo, mas não saberia nem por onde começar pra poder reproduzir seu problema.

Espero que esteja vendendo bastante, e sem erros é claro.

Grande abraço!
