### ISSUE TITLE
Ambiente de produção - Cartão inválido independente do cartão 

### ISSUE THREAD

**Issue by BernardinoGomes** [r-martins/PagSeguro-Magento-Transparente#94]
Amigos,Boa noite.
Estou com um problema similar de alguns tópicos,porém eles estão fechados.

Teu Token está habilidado para usar no checkout transparente,porém no ambiente de produção aparece a mensagem de cartão inválido.Isso ocorre com qualquer cartão que eu coloque.

Alguém poderia me dar uma solução ?
Já re-coloquei o token,limpei a cache,porém sem sucesso

log.
2015-04-29T22:58:53+00:00 DEBUG (7): Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulÃ¡rio. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualizaÃ§Ã£o de blocos via ajax nao se preocupe.

**Comment by leonambernini** [comment]
Estou com o mesmo problema :x

**Comment by r-martins** [comment]
Veja https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203585029--Cartão-inválido-aparece-para-qualquer-cartão-digitado

e também

https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/203585169-Como-sei-se-minha-conta-tem-suporte-ou-está-habilitada-pra-usar-o-checkout-transparente-

Se não resolver, informem o url.

Abs boas vendas.

**Comment by apzeiro** [comment]
Eu estava com o mesmo problema e resolvi simplesmente recolocando o valor to token.
Qualquer modificação na tela de Formas de Pagamento do Magento, o campo salvará desconfigurado porque há um valor padrão no input desse campo:

`<input id="payment_pagseguro_token" name="groups[pagseguro][fields][token][value]" value="******" class=" input-text" type="password">
`
Ao submeter (salvar a tela) o asteriscos são enviados no lugar do token. Isso acontece mesmo quando o módulo não é alterado diretamente. Salvou a tela desconfigura. Deveria resgatar o valor do token no banco de dados e não inserir asteriscos.

@r-martins @leonambernini @BernardinoGomes
