### ISSUE TITLE
Notificação de retorno do PagSeguro gera erro 502

### ISSUE THREAD

**Issue by chicao-affero** [r-martins/PagSeguro-Magento-Transparente#96]
Oi,

O pagamento está sendo processado normalmente. Eu cadastrei o endereço da minha loja para notificação de retorno mas o pagseguro diz que recebeu um erro 502 ao enviar a notificação.

Preciso colocar alguma credencial para acessar a URL?

![erro pagseguro](https://cloud.githubusercontent.com/assets/4906359/7639971/7791ccb6-fa56-11e4-9980-d41ff979d3d5.png)

**Comment by r-martins** [comment]
Experimente tirar a / do final e ver os logs de erro do apache e do magento.
reabra se nao resolver.
