### ISSUE TITLE
Botão e Link "Imprimir Boleto" aparecem, mas não imprimem nada

### ISSUE THREAD

**Issue by elielcezar** [r-martins/PagSeguro-Magento-Transparente#97]
Olá,

Estou usando a versão Pró e, após finalizar uma venda com opção de pagamento via boleto, sou direcionado para a tela com a mensagem de sucesso e o botão "Clique aqui para imprimir seu boleto". Porém esse botão não excuta nenhuma ação. Inspecionei o html e está assim:

<input onclick="popWin('','payment','');" value="Clique aqui para imprimir seu boleto" type="button">

Da mesma forma, quando o usuário vai para a sua página prória e visualiza a compra (Ex.: sales/order/view/order_id/6/)  o link direciona o usuário para esta mesma página, sem exibir nenhum boleto.

Notei que o mesmo ocorre com a loja de testes (http://pagseguro-exemplo.ricardomartins.net.br/sales/order/print/order_id/17/)

**Comment by r-martins** [comment]
Olá @elielcezar,
Problema corrigido na versão 2.2.0.
Envie um e-mail para pagseguro-transparente@ricardomartins.net.br pedindo a nova versão.
