### ISSUE TITLE
Erro na finalização do pagamento

### ISSUE THREAD

**Issue by Josiberto** [r-martins/PagSeguro-Magento-Transparente#98]
Olá, instalei o PagSeguro Magento Transparente segui o passo-a-passo do video de nosso amigo Ricardo Martins, porem ao fazer os teste com o Sandbox do PagSeguro liguei o debug do chrome aparece assim:
http://www.lollitamodas.com.br/onestepcheckout/ajax/check_email/ 404 (Not Found)
http://www.lollitamodas.com.br/onestepcheckout/ajax/check_taxvat/ 404 (Not Found)

e nos campos email e cpf mesmo estando corretamente preenchidos apareceo  Alerta "Campo obrigatório".

Em seguida abri o Log do PagSeguro em /var/log que diz assim
Falha ao obter o token do cartao ou sender_hash. Veja se os dados "sender_hash" e "credit_card_token" foram enviados no formulário. Um problema de JavaScript pode ter ocorrido. Se esta for apenas uma atualização de blocos via ajax nao se preocupe.

Sei muito pouco de programação por isso vim em busca de Ajuda, espero poder contar com vocês!!

**Comment by r-martins** [comment]
Olá @Josiberto,
Dá uma olhada no [hc](https://pagsegurotransparente.zendesk.com/hc/pt-br/articles/204283145-Falha-ao-obter-o-token-do-cart%C3%A3o-ou-sender-hash). Tem muita coisa que pode lhe ajudar a resolver esse e outros problemas.
