### ISSUE TITLE
Pagseguro não processa pagamento

### ISSUE THREAD

**Issue by BernardinoGomes** [r-martins/PagSeguro-Magento-Transparente#99]
Amigos,
Estou tendo dificuldade perante o pagseguro e gostaria de saber se alguém passou por esse mesmo problema.

Em fase de testes efetuava pagamentos com cartões reais no ecommerce e sempre tinha sucesso nas transações,porém de uma hora pra outra parou de funcionar as transações e agora elas ficam com o status "cancelada" com a seguinte mensagem:
O pagamento de R$ x,xx feito por xxxxx não foi autorizado e foi cancelado pelo PagSeguro.

- O pagseguro está alegando que seria algo errado no meu módulo,porém os logs estão normais.
- A operadora falou que não foi ela que cancelou e sim o Pagseguro.
- Não estou usando meu cartão.
Alguém teria alguma solução?pois pelo visto o pagseguro não vai solucionar esse problema.

**Comment by r-martins** [comment]
Oi @BernardinoGomes,
No retorno do Pagseguro, logado no pagseguro.log, existe um nó chamado <cancellationSource>, que pode ser

￼￼￼￼￼￼￼￼￼INTERNAL
PagSeguro

￼￼￼￼￼￼￼EXTERNAL
Instituições Financeiras

PS: Vamos usar esse canal apenas para reporte de bugs. Suporte e outras duvidas pode-se usar foruns ou canal de suporte.
